### ISSUE TITLE
Error: assignment to invalid subscript range

### ISSUE THREAD

**Issue by nstetter** [Aloxaf/fzf-tab#1]
When trying to trigger the completion with pressing `TAB` I get this error:
```
_compadd_wrapper:53: compcap_list: assignment to invalid subscript range
```

My system:
Kernel: 5.4.2-1-MANJARO x86_64
zsh 5.7.1

**Comment by Aloxaf** [comment]
Does this happen on a specific command or all commands?
If it only happens on a specific command, can you provide the command's completion function?

**Comment by nstetter** [comment]
It happens on all commands. Even on simple path complete for `ls`.

**Comment by Aloxaf** [comment]
I can't reproduce it, can you provide your `~/.zshrc`?

**Comment by nstetter** [comment]
I narrowed it down to this minimal zshrc:

```
# Check if zgen is installed
if [[ ! -d ~/.zgen ]]; then
	git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"
fi

# automatically reset (create new initscript) when ~/.zshr has changed
ZGEN_RESET_ON_CHANGE=(${HOME}/.zshrc)

# load zgen
source "${HOME}/.zgen/zgen.zsh"

#Plugins

zgen oh-my-zsh
zgen load Aloxaf/fzf-tab
zgen load softmoth/zsh-vim-mode

zgen save
```

Though I get 
```
_compadd_wrapper:53: bad floating point constant
```
using this setup.

My whole zshrc can be found here:
https://gitlab.com/nstetter/dotfiles/blob/master/zshrc

Thank you for looking into this!

**Comment by Aloxaf** [comment]
Found the reason: OMZ binds '^I' to its own completion widget, while fzf-tab's hook is still there. If you run `enable-fuzzy-complete` manually, fzf-tab will start work properly.
I'm not sure why fzf-tab's binding is overwritten by OMZ.
This bug couldn't be fixed by fzf-tab, I can only add a check in the hook to ensure that your completion system won't be broken when this happens

**Comment by nstetter** [comment]
Maybe it is time to finally ditch OMZ.

Thank you for the quick response

**Comment by Aloxaf** [comment]
@nstetter I'm so sorry, I make a mistake.
It not caused by OMZ but by zsh-vim-mode, and can be fixed by let fzf-tab initialize after zsh-vim-mode.

**Comment by nstetter** [comment]
Loading fzf-tab as last plugin works for me.
Thanks for your effort!
