### ISSUE TITLE
[FR] Support the print-query fzf option

### ISSUE THREAD

**Issue by Systemcluster** [Aloxaf/fzf-tab#102]
I would like to apply my input when no match was found. fzf provides the `print-query` option for this, but this plugin does not support it yet. 

**Is your feature request related to a problem? Please describe.**

The input disappears when no selection is applicable, and has to be re-typed again on the regular prompt. 
An example use-case is trying to auto-complete a path, and wanting to mkdir it if it doesn't exist yet. It would be useful to be able to just accept the non-matching input so mkdir can be appended.

When using the `--print-query` or the `--bind=ctrl-d:print-query` option for fzf, an error is thrown:

`_fzf_tab_complete:54: bad set of key/value pairs for associative array`

I assume this is because the printed query is not part of the `_fzf_tab_compcap` array.

**Comment by Aloxaf** [comment]
Nice idea.

**Comment by Aloxaf** [comment]
You can try #106 now. Does it work as expected?

**Comment by Systemcluster** [comment]
It works great, thank you for the quick update!
