### ISSUE TITLE
[FR] Including dotfiles in the search prompt if there are

### ISSUE THREAD

**Issue by hangg7** [Aloxaf/fzf-tab#104]
**Is your feature request related to a problem? Please describe.**
Currently fzf-tab cannot search for dotfiles in their results, while under the same case the default completion would do. An screenshot for describing this visually:
![image](https://user-images.githubusercontent.com/10098306/88135100-1cb1b880-cb9b-11ea-9f4c-64862ade1b69.png)
![image](https://user-images.githubusercontent.com/10098306/88135129-2affd480-cb9b-11ea-9702-220b4458ed4b.png)

This behavior is specifically undesirable when user would like to first see the directories under current path and deside whether or not navigate one level back the directories:
![image](https://user-images.githubusercontent.com/10098306/88135295-8df16b80-cb9b-11ea-98dc-052caa162d37.png)

**Describe the solution you'd like**
Adding dotfiles in the search prompty -- an example would be seeing both `dir{1,2}` and `.`, `..` in my last screenshot above.

**Describe alternatives you've considered**
https://github.com/junegunn/fzf/issues/634 might be related, but cannot get it to work with the suggested configuration.

Having the issue solved / adding this feature could largely improve the experience. And from my own perspective, this is the only thing stop me using fzf-tab as a real file explorer :)

**Comment by Aloxaf** [comment]
To list all hidden files, you can use `glob_dots` option: `setopt glob_dots`
To list both `.` and `..`, you can use `special-dirs` tag: `zstyle ':completion:*' special-dirs true`

**Comment by hangg7** [comment]
Thanks for your quick reply! But in my case it does not really works:
![image](https://user-images.githubusercontent.com/10098306/88201144-f839f880-cbfb-11ea-8321-8b2243548bc7.png)
![image](https://user-images.githubusercontent.com/10098306/88201182-01c36080-cbfc-11ea-8dce-9e96ac478fcf.png)

**Comment by Aloxaf** [comment]
![图片](https://user-images.githubusercontent.com/17017672/88252575-568cd700-cce1-11ea-8d02-ea9e97f5a87f.png)
That's strange.

Can you provide your zshrc?

**Comment by Aloxaf** [comment]
Close due to a lack of information.
