### ISSUE TITLE
[FR] Allow selecting multiple items

### ISSUE THREAD

**Issue by ReekyMarko** [Aloxaf/fzf-tab#11]
Sorry for spamming the issue tracker, this is the last one for a while I promise

FZF allows selecting multiple items using the tab key. I don't know the ins and outs of this plugin but I suspect that the tab key is captured by ZSH and not passed to FZF.

There is a conflict because most people probably expect to be able to cycle completions using the tab key, so could we maybe use ctrl-tab or ctrl-return?

**Comment by Aloxaf** [comment]
Please feel free to submit issues :)

This is an interesting feature, I'll manage to implement it.
