### ISSUE TITLE
[Q]How to disable sorting of candicates of `git checkout <tab>`

### ISSUE THREAD

**Issue by shunlir** [Aloxaf/fzf-tab#110]
Tried `zstyle ':completion:complete:*:options' sort false`, doesn't help
Take `git checkout <TAB>` in a repo as example:
Actual:
![image](https://user-images.githubusercontent.com/14887081/89735697-f6df4b80-da96-11ea-8abd-b8e27db85bed.png)
Expected (order):
![image](https://user-images.githubusercontent.com/14887081/89735775-6c4b1c00-da97-11ea-81e4-ce811a0da5a8.png)

**Comment by Aloxaf** [comment]
Try this:
```zsh
zstyle ':completion:complete:git-checkout:argument-rest' sort false
```

**Comment by shunlir** [comment]
@Aloxaf Thanks, it works!
