### ISSUE TITLE
[Q] zstyle extra-opts for command alias

### ISSUE THREAD

**Issue by mmqmzk** [Aloxaf/fzf-tab#111]
I'd like to alias `k` for `kill` for everyday use, but I have problems configuring fzf-tab. After I type k and a space key then a tab key, completion shows preview using my default fzf options (eg `--preview-window right:70%:wrap`), not like that fzf-tab configured for `kill` command. I tried to use the followed code, but it seems to take no effect.

```
zstyle ':fzf-tab:complete:k:argument-rest' extra-opts --preview-window='down:15%:warp' --preview=$extract'ps --pid=$in[(w)1] -o cmd --no-headers -w -w'
```

Any ideas?

**Comment by Aloxaf** [comment]
how about this?
```zsh
zstyle ':fzf-tab:complete:kill:argument-rest' extra-opts --preview=$extract'ps --pid=$in[(w)1] -o cmd --no-headers -w -w' --preview-window=down:15%:wrap
```

**Comment by mmqmzk** [comment]
Thanks for the reply.
So just configure exactly for the origin command, it will work for the alias too, right?

I have another problem, my configure as followed, there always an extra line `0`, any tricks to debug it?

```bash
zstyle ':completion:*:*:*:*:processes' command 'ps -ef --no-headers -w -w'
zstyle ':fzf-tab:complete:kill:argument-rest' extra-opts \
  --preview=$extract';ps --pid=$in[(w)2] uww' --preview-window='down:15%:wrap'
```

![image](https://user-images.githubusercontent.com/2217694/89846658-6139de00-dbb4-11ea-905d-646f1540c21d.png)

**Comment by Aloxaf** [comment]
This is the process group id which always exists even in the default configuration.

You can hide it with `zstyle ':completion:*:kill:*' ignored-patterns '0'`.

**Comment by mmqmzk** [comment]
Thanks a lot.
