### ISSUE TITLE
[Q] ZSH Caching

### ISSUE THREAD

**Issue by jef** [Aloxaf/fzf-tab#120]
**Describe your question**

Does `fzf-tab` support `zstyle ":completion:*" use-cache on`? I guess this more of a question for `fzf` as I write this, but curious if you know.

Thanks!

**Comment by Aloxaf** [comment]
Yes. fzf-tab is built on the top of compsys(zsh's default completion system).

**Comment by jef** [comment]
Awesome, thanks!
