### ISSUE TITLE
[Q] How do you get git completion like in the README example?

### ISSUE THREAD

**Issue by BirkhoffLee** [Aloxaf/fzf-tab#124]
In https://asciinema.org/a/293849 you get git completion with different categories, I wonder how'd you get it?

This is what I have here:

<img width="673" alt="CleanShot 2020-10-07 at 17 07 50@2x" src="https://user-images.githubusercontent.com/8148095/95311016-a9793200-08bf-11eb-89f1-1fb10c74c275.png">

Yours:

<img width="593" alt="CleanShot 2020-10-07 at 17 08 40@2x" src="https://user-images.githubusercontent.com/8148095/95311150-d0376880-08bf-11eb-93e8-70ee2cdffcdb.png">

Thanks in advance.

**Comment by solarizedalias** [comment]
You're likely be using different `_git` (the one shipped with [git](https://github.com/git/git/blob/master/contrib/completion/git-completion.zsh), not with [zsh](https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Command/_git)).

After invoking the completions (to resolve autoload), what does `print ${functions_source[_git]}` show for you?

**Comment by BirkhoffLee** [comment]
@solarizedalias `/usr/local/share/zsh/site-functions/_git` is what I get.

**Comment by BirkhoffLee** [comment]
Running the following resolved the issue

```console
$ rm /usr/local/share/zsh/site-functions/_git
$rm /usr/local/share/zsh/site-functions/git-completion.bash
```

Thanks for the hint @solarizedalias, I appreciate it
