### ISSUE TITLE
[FR] integration with tmux popup

### ISSUE THREAD

**Issue by Aloxaf** [Aloxaf/fzf-tab#128]
https://github.com/tmux/tmux/issues/1842

That would be useful if the current pane is too small to show the full candidate list.

**Comment by NightMachinary** [comment]
This already works:
![image](https://user-images.githubusercontent.com/36224762/96614975-94fc5700-130d-11eb-91e8-a70223097d40.png)

Just use `fzf-tmux -p90% "$@" | sponge` instead of `fzf`.

**Comment by Aloxaf** [comment]
That's nice. But I want the popup to show just above or below the current line, not always in the center (like a completion popup in IDE).

**Comment by solarizedalias** [comment]
fzf-tmux has `-x COL` and `-y ROW` but that is not relative to the current tmux pane.
So I think we need to tell fzf-tmux the values with offsets depending on the current layout.

**Comment by Aloxaf** [comment]
Yes, but I haven't found a simple way to get the cursor position in window.

**Comment by solarizedalias** [comment]
I tweaked around and end up in this. This roughly gets the cursor position.
`$ tmux run-shell 'echo #{e|+:#{cursor_x},#{e|+:#{window_offset_x},#{pane_left}}} #{e|+:#{cursor_y},#{e|+:#{window_offset_y},#{pane_top}}}'`

**Comment by solarizedalias** [comment]
This displays a small popup under cursor, but it's getting more and more nested.

`tmux run-shell 'tmux display-popup -w 100 -h 10 -x "#{e|+:#{e|+:#{cursor_x},#{e|+:#{window_offset_x},#{pane_left}}},10} " -y " #{e|+:#{e|+:#{cursor_y},#{e|+:#{window_offset_y},#{pane_top}}},10}" '`

**Comment by solarizedalias** [comment]
Sorry for many posts.
This is finally a decent result.
`$ aaa=( $(tmux run-shell 'echo #{e|+:#{cursor_x},#{e|+:#{window_offset_x},#{pane_left}}} #{e|+:#{cursor_y},#{e|+:#{window_offset_y},#{pane_top}}}') ) && fzf-tmux -w 100 -h 30 -x $(( ${aaa[1]} + 1 )) -y $(( ${aaa[2]} + 30 + 1 ))`

This needs some tricks. When you change the window size, you also have to adjust the position especially for height and row.

**Comment by Aloxaf** [comment]
@solarizedalias 

Thanks for your code.
I finish a basic demo in #130. You can take a look at it.
