### ISSUE TITLE
[Q] How do I exclude `./` and `../` from the results?

### ISSUE THREAD

**Issue by NightMachinary** [Aloxaf/fzf-tab#129]

**Comment by NightMachinary** [comment]
I created a hack that removes these two by brute-force, by it's rather inelegant and inefficient, especially since it happens after the ANSI colors have been applied:
```
function fztab() {
   # github.com/NightMachinary/prefixer
   prefixer rm --rm-ansi --rm-x -- './' '../' '\x00.\x00/' '\x00..\x00/' | fzf "$@"
}
FZF_TAB_COMMAND=( fztab "$FZF_TAB_OPTS[@]" )
```

**Comment by Aloxaf** [comment]
By default, zsh won't add `.` and `..` to possible completions, unless you have set `zstyle ':completion:*' special-dirs true`.

Please check your configutation and remove that line or overwrite it with `zstyle -d ':completion:*' special-dirs`.
