### ISSUE TITLE
directory completion with "." in the $PATH

### ISSUE THREAD

**Issue by kakulukia** [Aloxaf/fzf-tab#131]
**Describe the bug**
Im trying to execute a command not in the $PATH, thus im trying to complete the full path like `dir1/dir2/command`.

I start typing the first two letters of the directory and hit `<tab>`:
<img width="282" alt="Bildschirmfoto 2020-10-22 um 12 26 56" src="https://user-images.githubusercontent.com/96352/96859716-1e24a280-1462-11eb-8645-d4c316fd5cda.png">

I get two entries one being the folder and due to "." in the $PATH the second one is the executable folder.
fzf is mixing things up tho. This is visible when disabling it.
ZSH  actually reports three groups:
<img width="145" alt="Bildschirmfoto 2020-10-22 um 12 27 36" src="https://user-images.githubusercontent.com/96352/96860365-f550dd00-1462-11eb-857c-fbbe128285e4.png">

And choosing the 'executable file' here actually gives me "ghar/" as  expected and i can continue typing.

*NOTE:* This does not happen while completing "cd g`<tab>`". But also there the  group header reads 'local directory', unlike the above  example.

**Steps to reproduce the behavior:**
1. `export PATH=.:$PATH`
1. Start typing one of your directories like 'd' for Desktop and Downloads inside your home folder.
2. Press `<TAB>`
4. Choose the entry with a trailing slash
5. At least i end up with just the directory name without slash.

**Expected behavior:**
I expect to get what i chose in the fzf menu.

**Environment (please complete the following information):**
 - OS: OSX 10.15
 - zsh version 5.8
 - fzf-tab version [e.g. https://github.com/Aloxaf/fzf-tab/commit/0915bf591a5e38c189d8d971a4e35b711cfc373f]

**zshrc**
I stripped down my .zshrc to this:

    zstyle ':prezto:load' pmodule-dirs $HOME/.zprezto-contrib
    zstyle ':prezto:load' pmodule \
      'completion' \
      'fzf-tab' \
      'directory'
    
    source "$HOME/.zprezto/init.zsh"
    zstyle ':completion:*:descriptions' format '[%d]'
    
    export PATH=.:$PATH

**Comment by Aloxaf** [comment]
A minimal zshrc to reproduce:

```zsh
setopt path_dirs
mkdir test
export PATH=.:$PATH
```

The line of code which causes this bug:
https://github.com/Aloxaf/fzf-tab/blob/7f8254a184d159016587f586c13f6686c17f3e7a/fzf-tab.zsh#L462

Both `ghar` in `directory in path` and in `executable file` starts with `ghar` so fzf-tab can't distinguish them.

It may take some time to find a good way to fix it.

**Comment by kakulukia** [comment]
Does the group merge play a role here?
Thank god this is not disrupting my daily workflow .. fzf-tab works like a charm otherwise!

**Comment by kakulukia** [comment]
I just updated the plugin and the category merging is not an issue any more, well done!

![Bildschirmfoto 2020-10-23 um 16 38 57](https://user-images.githubusercontent.com/96352/97017593-67522080-154e-11eb-9be6-b6621f9291b4.png)

**Comment by AlphaNecron** [comment]
You can close this issue now.

**Comment by Aloxaf** [comment]
In fact, this hasn't been fixed. See #191.
