### ISSUE TITLE
Not worked popup

### ISSUE THREAD

**Issue by webmastak** [Aloxaf/fzf-tab#135]
Not worked popup.

Terminal:
Tilix: 1.9.1
VTE: 0.62
GTK: 3.24.5

[tmux 3.2-rc](https://github.com/tmux/tmux/releases/tag/3.2-rc)

How to make popup work?

**Comment by MaienM** [comment]
It still defaults to the non-popup version, you need to enable it specifically:

``` zsh
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
```

(This is mentioned directly underneath the image showcasing this feature on [the wiki](https://github.com/Aloxaf/fzf-tab/wiki/Configuration#fzf-command).)

**Comment by Aloxaf** [comment]
As MaienM said, This is not enabled by default because the stable version of tmux is 3.1 now.

**Comment by webmastak** [comment]
I was doing:
```
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
```

**Comment by Aloxaf** [comment]
@webmastak Does `tmux popup -KE -R 'fzf'` work?

**Comment by webmastak** [comment]
unknown command: popup

**Comment by Aloxaf** [comment]
@webmastak 
What's your output of `tmux -V`?
BTW, you need to kill/exit the old server after upgrade.

**Comment by webmastak** [comment]
tmux 3.1b

**Comment by Aloxaf** [comment]
> tmux 3.1b

That's not correct. That should be "tmux 3.2-rc2" if you're using https://github.com/tmux/tmux/releases/tag/3.2-rc

> `tmux popup -KE -R 'fzf'` - no server running on /tmp/tmux-1000/default

That's really strange. Do you have tmux started? What's the value of `$TMUX` variable?

**Comment by webmastak** [comment]
I can not figure out how to properly start the tmux server?

**Comment by Aloxaf** [comment]
> I can not figure out how to properly start the tmux server?

Just type `tmux` and press enter. It's something like a terminal emulator which will wrap you shell.

You can also put this line to your ~/.zshrc to start it automatically:

```zsh
[[ -z $TMUX ]] && exec tmux
```

**Comment by webmastak** [comment]
Thanks, I figured it out, it worked.

Disable the status bar:
![20201026203347-731x37](https://i.imgur.com/PHEiSNM.png)
?

**Comment by Aloxaf** [comment]
> Colors differ. When the window pops up, the selection bar is black.
> How to make it the same color as without the popup.

I don't know how fzf-tab choose the color of current line. But you can specify it explicitly with `zstyle ":fzf-tab:*" fzf-flags '--color=bg+:23'`


> And I also didn't understand how to enable scrolling as in the terminal using `Shift+PageUp/PageDown` and `Shift+Home/End`

You should first enter copy mode with `C-b [`. Then you can use `PageUp/PageDown`.

As for `Home/End`, you should bind it manually. Put these lines to you ~/.tmux.conf

```bash
bind-key -T copy-mode 'Home' send-keys -X history-top
bind-key -T copy-mode 'End' send-keys -X history-bottom
```

**Comment by webmastak** [comment]
Thanks for the answer, but tmux does not suit me, there are too many pitfalls with hotkeys.
Can't disable tmux context menu when mouse scrolling is enabled.

**Comment by Aloxaf** [comment]
Then you must take a look at https://github.com/romkatv/zsh4humans/issues/35#issuecomment-716172250.

@romkatv creates a custom tmux that can use popup but doesn't need to tolerate other drawbacks of tmux.

I think I can also add it as a way to use popup for those who don't like tmux when the feature is finally stablized.

**Comment by webmastak** [comment]
Is it possible to use tmux only when we use fzf-tab, then disconnect from the server? And work just in the terminal.

**Comment by Aloxaf** [comment]
No, it's not a standalone tool to provide popup, it's a terminal emulator. So you must run your shell in it.

**Comment by webmastak** [comment]
I made friends tmux and terminal with fzf-tab, thanks to [zsh4humans](https://github.com/romkatv/zsh4humans/)
![popup](https://i.imgur.com/bxyhYsV.png)
