### ISSUE TITLE
Installation issue? fzf-tab not working [Q]

### ISSUE THREAD

**Issue by tkolleh** [Aloxaf/fzf-tab#137]
Installed fzf-tab following instructions in the README document with no success. type `git <tab>` shows  a completion menu (options) without a fzf. Any suggestions on how to debug this issue?

### Setup
<img width="762" alt="Screen Shot 2020-10-25 at 9 31 25 PM" src="https://user-images.githubusercontent.com/3095197/97125336-00796680-170a-11eb-91ed-f3c7a9123864.png">

**Comment by Aloxaf** [comment]
How about run `enable-fzf-tab` manually?

Can you give the results of the following code:

```zsh
bindkey "^I"
```

**Comment by tkolleh** [comment]
Running `enable-fzf-tab` manually works. Prior to manually enabling fzf-tab, executing `bindkey "^I"` command returns:

```c
"^I" fzf-completion
```

after enabling it the same command returns:

```c
"^I" fzf-tab-complete
```

**Comment by tkolleh** [comment]
Looks like its coming from fzf's [completion.zsh file](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh). Findings are a result of executing:

```
$ zle -lL fzf-completion
$ type fzf-completion
```

**Comment by Aloxaf** [comment]
https://github.com/Aloxaf/fzf-tab#compatibility-with-other-plugins

You should make sure fzf-tab is loaded after completion.zsh
