### ISSUE TITLE
[BUG] fzf-tmux popup in 3.3 tmux next

### ISSUE THREAD

**Issue by jeeeem** [Aloxaf/fzf-tab#140]
**Describe the bug**
I tried tmux-popup with fzf-tab but its not working.

**Expected behavior**
It will show tmux-popup with fzf-tab

 - OS:  Arch Linux
 - zsh version 5.8
- tmux version: tmux next-3.3
- terminal: alacritty 0.6.0-dev

**Comment by jeeeem** [comment]
Do I really need to install 3.2 to make it work? but from what I heard it has been merged to master. or am I wrong?

**Comment by Aloxaf** [comment]
> I tried tmux-popup with fzf-tab but its not working.

Make sure you have set `zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup`



> Do I really need to install 3.2 to make it work? but from what I read it has been merged to master.

Yes it has been merged to master, but tmux hasn't released the new version so you have to use tmux-git.

**Comment by jeeeem** [comment]
> Make sure you have set zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup

I already exec `zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup` but whenever I tab nothing happens until I `ctrl-c` again. I think it works but the pop-up not showing up.

> Yes it has been merged to master, but tmux hasn't released the new version so you have to use tmux-git.

Yup thats why I said I have next 3.3 version. 

What do you think happening here? Should I try install the 3.2 not the master one?

**Comment by Aloxaf** [comment]
> I already exec `zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup` but whenever I tab nothing happens until I `ctrl-c` again. I think it works but the pop-up not showing up.

Did you start tmux？See https://github.com/Aloxaf/fzf-tab/issues/135#issuecomment-716702075

**Comment by jeeeem** [comment]
Nvm its okay now. I just source the plugin.zsh `source ~/.oh-my-zsh/custom/plugins/fzf-tab/fzf-tab.plugin.zsh`
