### ISSUE TITLE
[BUG] $realpath does not expand named directories

### ISSUE THREAD

**Issue by NICHOLAS85** [Aloxaf/fzf-tab#141]
**Describe the bug**
When a user attempts to complete a command containing a named directory created via `hash -d`, If the fzf preview command uses $realpath, the preview command will fail as the directory isn't expanded correctly.

**To Reproduce**
1. Define a directory name ex: `hash -d docs=~/Documents`
2. cd ~docs<tab> 
4. See error in the preview window

**Expected behavior**
Named directories expanded correctly for use in $realpath variable

**Screenshots**
![image](https://user-images.githubusercontent.com/15698885/97534435-5eb77b00-1990-11eb-8aaa-694b513887cd.png)

**Environment (please complete the following information):**
 - OS: Bedrock Linux 0.7.18 Poki 
 - zsh version: 5.8
 - fzf-tab version: https://github.com/Aloxaf/fzf-tab/commit/da952d141de497faa842d0b52b862d7f8be54023

**zshrc**
Can provide upon request.

**Comment by Aloxaf** [comment]
Thanks for your report.

This has been fixed in https://github.com/Aloxaf/fzf-tab/commit/0f5622a64b273d203046b570e76ba5baef84be58. Please update and try again.

**Comment by NICHOLAS85** [comment]
Ahh, the latest commits indeed fix the issue. Should've updated before reporting! Thanks, I'm really liking fzf-tab. Its greatly improved config.
