### ISSUE TITLE
[BUG] Permission denied on /tmp/fzf-tab with multiple fzf-tab users

### ISSUE THREAD

**Issue by wolfo** [Aloxaf/fzf-tab#142]
**Describe the bug**
When multiple users use fzf-tab (like normal and super user), there's a permissions conflict on /tmp/fzf-tab

**To Reproduce**
1. run a shell with fzf-tab as root
2. from a non-root shell with fzf-tab, type ls <tab>

```
user@example:~$ ls
-ftb-fzf:37: permission denied: /tmp/fzf-tab/compcap.3694
-ftb-fzf:38: permission denied: /tmp/fzf-tab/groups.3694
```

**Expected behavior**
No warnings or errors. User-specific locations in /tmp

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 10, Linux 5.8.14, aarch64
 - zsh 5.7.1
 - fzf-tab most recent from master
**zshrc**
If applicable, add a minimal zshrc to help us analyze.

**Comment by Aloxaf** [comment]
Thanks for your report!

Please update and try again.
