### ISSUE TITLE
[FR] Use $TMPDIR instead of /tmp

### ISSUE THREAD

**Issue by NICHOLAS85** [Aloxaf/fzf-tab#143]
**Is your feature request related to a problem? Please describe.**
I see that /tmp/fzf-tab and /tmp/fzf-tab-(username) are created when I use fzf-tab. It seems this plugin ignores my $TMPDIR variable and instead creates these directories with a hardcoded /tmp value

**Describe the solution you'd like**
Create directories with respect to $TMPDIR and fallback to /tmp if it's not set

**Comment by Aloxaf** [comment]
Fixed. It will now respect `$TMPPREFIX`, which is zsh's standard.

**Comment by NICHOLAS85** [comment]
Thanks! I'll adjust my config accordingly
