### ISSUE TITLE
[BUG] Zsh crash when completing after build-fzf-tab-module

### ISSUE THREAD

**Issue by NICHOLAS85** [Aloxaf/fzf-tab#144]
**Describe the bug**
After building the fzf-tab module with `build-fzf-tab-module`, anytime I attempt to complete a command, zsh will crash

**To Reproduce**
run `build-fzf-tab-module`
restart your shell
type a command and complete ex: `$ ls <tab>`

**Expected behavior**
Shell to not crash

**Environment (please complete the following information):**
 - OS: `Bedrock Linux 0.7.18 Poki`
 - zsh version: `5.8`
 - fzf-tab version: 9980c3763b3c8ccd55eae36651ba6c1fa49d26a5

**zshrc**
Can send upon request

Attached is a strace log up until zsh crashes
[log.txt](https://github.com/Aloxaf/fzf-tab/files/5466911/log.txt)

**Comment by Aloxaf** [comment]
Thanks for your report.

Please update and check again.

**Comment by NICHOLAS85** [comment]
Issue fixed! Thanks
