### ISSUE TITLE
[Q] take away back slash

### ISSUE THREAD

**Issue by webmastak** [Aloxaf/fzf-tab#146]
How to take away back slash if the name of the directory has spaces as in the screenshot?
![1](https://i.imgur.com/CsZ0GvS.png)

**Comment by Aloxaf** [comment]
As far as I know, this is impossible. Considering that there may be special characters in the file name, escaping is necessary.

**Comment by webmastak** [comment]
It's strange how it's done here [zsh-interactive-cd](https://github.com/changyuheng/zsh-interactive-cd) there is no backslash.

**Comment by Aloxaf** [comment]
They are different plugins. fzf-tab's result will be consistent with compsys's if there is no special reason.

![图片](https://user-images.githubusercontent.com/17017672/97797085-d87f8b00-1c54-11eb-94f9-64e2d020e9bd.png)

![图片](https://user-images.githubusercontent.com/17017672/97797087-e208f300-1c54-11eb-93a1-ba48807798c5.png)

![图片](https://user-images.githubusercontent.com/17017672/97797198-1b8e2e00-1c56-11eb-84e6-463893a43ff9.png)
