### ISSUE TITLE
[BUG] Too few completion results are displayed

### ISSUE THREAD

**Issue by xWillQ** [Aloxaf/fzf-tab#147]
**Description**
Hi, after [`629417f`](https://github.com/Aloxaf/fzf-tab/commit/629417fd2aa3bb1d9ca310a9ac658e72d0d54551) there are less results displayed on one screen, even if there are enough space. This is most frustrating when I try to find a file in directory with 4 files and have to scroll down a few times, although all of them could be displayed at once.

**To Reproduce**
1. Type `vim` in folder with four files
2. Press <kbd>Tab</kbd>
3. See that list of completions has only 2 items, while taking much less space that it could.

**Expected behavior**
Being able to see more completion results, or, ideally, being able to set maximum height of selection menu to fixed amount of lines.

**Screenshots**
Problematic version is on the left:
![Screenshot (5)](https://user-images.githubusercontent.com/38136135/97803013-ee537700-1c79-11eb-8a95-deb57005b83c.png)
![Screenshot (6)](https://user-images.githubusercontent.com/38136135/97803015-f14e6780-1c79-11eb-9fa4-c2948e629dd2.png)
![Screenshot (7)](https://user-images.githubusercontent.com/38136135/97803017-f3182b00-1c79-11eb-89f2-d595c4914c12.png)

**Environment:**
 - OS: Ubuntu 20.04.1 LTS on Windows 10 x86_64
 - zsh version: 5.8
 - fzf-tab version: commit [`629417f`](https://github.com/Aloxaf/fzf-tab/commit/629417fd2aa3bb1d9ca310a9ac658e72d0d54551) and later

**Comment by Aloxaf** [comment]
Oh sorry. I made a mistake when calculating the fzf windows' height.

Thanks for your report! Please update and try again.

Feel free to reopen the issue if it still doesn't work.

**Comment by xWillQ** [comment]
It works, thanks for quick reply!

**Comment by nabn** [comment]
Hey, I'm seeing a similar issue— the scroll offset seems to be a bit off. When I'm in a directory with too few directories (<4) and try `cd <TAB>`, the options list is one option tall. Rest are still accessible when tabbed.

In this screen recording, I'm progressively adding directories and checking what the completion prompt gives me:

https://user-images.githubusercontent.com/1693287/210297440-8a7062d8-ac56-4856-862e-fa0cbaf33c2c.mp4



I'd expect that when there's enough room for all options, all of them are displayed on the screen. Was that the intention?

Also, please advise if you'd prefer a new issue for this.

**Comment by vFones** [comment]
@Aloxaf any updates? I've got the same problem as @nabn
With ZSH i cannot see properly $FZF_PREVIEW_LINES and $FZF_PREVIEW_COLUMNS. Is this related?

**Comment by iamhrigved** [comment]
Hey guys I have the exact same problem as @nabn is there a way to solve this?
