### ISSUE TITLE
[Q] use current word as initial query

### ISSUE THREAD

**Issue by IainVM** [Aloxaf/fzf-tab#151]
Given you have a directory like this:
```
/
  test1/
    file1
  test2/
    file2
  file3
```

Given a command like `cd` if I do `cd <tab>` fzf-tab offers completions for the command. 

So that if I did `cd file<tab>` the query box is filled with `file` already, is this possible?

I tried `zstyle ':fzf-tab:*' query-string input` but this doesn't seem to work.

**Comment by Aloxaf** [comment]
Umm, I can't understand.

In your example, file{1,2,3} are not directories, so `cd file<tab>` won't get any results.

**Comment by IainVM** [comment]
Sorry, yeah `cd` was likely not the best command. `cat` might have made this a bit easier. 

I have many git projects on my machine, so I wrote an function `dev` with completion that offers a list of all my git projects. 
So I can do stuff like `dev <tab>` and then search through all my git projects and select one to open.

Sadly they have to show the entire filepath, since there might be 2 projects of the same name.
So I might have a list like below:

```
/home/iain/dev/gitlab.com/aloxaf/fzf-tab
/home/iain/dev/gitlab.com/junegunn/fzf
/home/iain/dev/github.com/another/project
```

I want to be able to `dev fzf<tab>` and the `fzf-tab` query start out with `fzf` as the word it's searching for. Thus only showing

```
/home/iain/dev/gitlab.com/aloxaf/fzf-tab
/home/iain/dev/gitlab.com/junegunn/fzf
```

**Comment by Aloxaf** [comment]
This is something beyond fzf-tab's ability.
By default, compsys will only do a prefix match, so no results will be passed to fzf-tab.

Here are two solutions:

1. Use `_match` completer. It will turn prefix match to pattern match, so that you can use something like `dev *fzf<tab>`.
```zsh
zstyle ':completion:*' completer _complete _match
```

2. Use `matcher-list` tag to control how the match will be done.
```zsh
zstyle ':completion:*' matcher-list 'b:=*'
```

You can change `:completion:*` to a more precise context so that it will only work for certain commands.

**Comment by IainVM** [comment]
That seems to work perfectly, thanks. I tried reading throughs so much of the zsh completion stuff to get this to work. Seems I didn't quite understand the matcher-list part. 

docs: http://zsh.sourceforge.net/Doc/Release/Completion-Widgets.html#Completion-Matching-Control
for anyone else who might want this behaviour.
