### ISSUE TITLE
[BUG] `print-query` clears commandline if pressed with an empty buffer

### ISSUE THREAD

**Issue by NICHOLAS85** [Aloxaf/fzf-tab#152]
**Describe the bug**
This is a little hard to describe but, hopefully, it's apparent in the video.
Basically, if no string is entered and `print-query` is used, the whole suggestion disappears, instead of leaving behind what has already been accepted.

**To Reproduce**
Enter a long completion using `continuous-trigger`. Enter a character and press `print-query`.
Compare this to:
Enter a long completion using `continuous-trigger`. Do not enter anything and press `print-query`.

**Expected behavior**
`print-query` should leave the buffer unaltered when no text has been entered.

**Screenshots**
https://asciinema.org/a/qHHC0a6FnKT9xAmZcvE2Dtriz

**Environment (please complete the following information):**
 - OS: Bedrock Linux 0.7.19beta1 Poki
 - zsh version: 5.8
 - fzf-tab version: 78b4cefb27dc2bef5e4c9ac3bf2bd28413620fcd

**zshrc**
Can provide upon request.

**Comment by Aloxaf** [comment]
Detected.

It can be reproduced without `continuous-trigger`

**Comment by NICHOLAS85** [comment]
```diff
diff --git a/fzf-tab.zsh b/fzf-tab.zsh
index ac859d0..edca0a2 100644
--- a/fzf-tab.zsh
+++ b/fzf-tab.zsh
@@ -129,9 +129,13 @@
         IPREFIX=$v[IPREFIX] PREFIX=$v[PREFIX] SUFFIX=$v[SUFFIX] ISUFFIX=$v[ISUFFIX]
         # NOTE: should I use `-U` here?, ../f\tabcd -> ../abcd
         builtin compadd "${args[@]:--Q}" -Q -- $choices[1]
-
-        compstate[list]= compstate[insert]='2'
-        [[ $RBUFFER == ' '* ]] || compstate[insert]+=' '
+        compstate[list]=
+        if [[ -n $choices[1] ]]; then
+            compstate[insert]='2'
+            [[ $RBUFFER == ' '* ]] || compstate[insert]+=' '
+        else
+            compstate[insert]=
+        fi
         return
       fi
       choices[1]=()
```
I found the above diff fixes the issue however, when using zdharma/fast-syntax-highlighting, upon pressing `print-query` with an empty selection the line loses syntax highlighting until you type or delete a character:
https://asciinema.org/a/37XN8IpzuwdUonDXEZqj7Lbc0

**Comment by Aloxaf** [comment]
> I found the above diff fixes the issue. However when using zdharma/fast-syntax-highlighting, upon pressing `print-query` with an empty selection the line loses syntax highlighting until you type or delete a character:
> [asciinema.org/a/37XN8IpzuwdUonDXEZqj7Lbc0](https://asciinema.org/a/37XN8IpzuwdUonDXEZqj7Lbc0)

Nice! This is a known issue of f-sy-h (https://github.com/zdharma/fast-syntax-highlighting/issues/183) and I think it is acceptable.

**Comment by Aloxaf** [comment]
> I found the above diff fixes the issue. However when using zdharma/fast-syntax-highlighting, upon pressing `print-query` with an empty selection the line loses syntax highlighting until you type or delete a character:
> [asciinema.org/a/37XN8IpzuwdUonDXEZqj7Lbc0](https://asciinema.org/a/37XN8IpzuwdUonDXEZqj7Lbc0)

This is a known issue of f-sy-h (https://github.com/zdharma/fast-syntax-highlighting/issues/183) and I think it is acceptable.
