### ISSUE TITLE
[BUG] Error when sourcing ls-colors.zsh

### ISSUE THREAD

**Issue by tam1m** [Aloxaf/fzf-tab#154]
**Describe the bug**
I'm getting an error caused by by 93e69c32623d1b1dd9fa7bbfef063d994c071e8e
`/home/xxxx/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-Aloxaf-SLASH-fzf-tab/lib/zsh-ls-colors/ls-colors.zsh:34: parse error: condition expected: ${2[1]}` 

Reverting 93e69c32623d1b1dd9fa7bbfef063d994c071e8e fixes the issue

**To Reproduce**
1. Enable fzf-tab in Antibody
2. start zsh

**Environment (please complete the following information):**
 - OS: Arch Linux
 - zsh version: 5.8
 - fzf-tab version https://github.com/Aloxaf/fzf-tab/commit/93e69c32623d1b1dd9fa7bbfef063d994c071e8e
 - Pluginmanager: [Antibody](https://github.com/getantibody/antibody) 6.1.1

**Comment by Aloxaf** [comment]
Thanks for your report. I have reverted this commit.
