### ISSUE TITLE
[Q] fzf-tab randomly fails displaying strange chars like "2;13R"

### ISSUE THREAD

**Issue by thugcee** [Aloxaf/fzf-tab#158]
### Example of problematic behaviour

In zsh I type:
```
> ls .co
```
Then I press a `<TAB>`. Usually instead of fzf search UI I get something like:
```
> 
> ls .co2;13R
```

`2` and `13` are not constant, `R` is a constant.

There is some text displayed for a fraction of a second, but it is replaced by a shell's prompt. It ends with `tty` - this is all what I'm able to read.

### My observations

For some prefixes it works for 10/10 times, for other 1-2/10.

The first number has always one digit and increases with every failure. The second one changes depending on prefix.

I don't know how to debug this problem. Any ideas?

**Comment by Aloxaf** [comment]
> 2;13R

This is an ANSI escape sequence. It represents the position of your current cursor.

The error message may be `failed to read /dev/tty`.
This is an old bug, I still don't know what causes it. 

Please try #160, which changes the way to get results from fzf. Hope it will work.

**Comment by thugcee** [comment]
> Please try #160, which changes the way to get results from fzf. Hope it will work.

It works!
Thank you :)
Your plug-in is brilliant, BTW.
