### ISSUE TITLE
[Q] How to configure key bindings?

### ISSUE THREAD

**Issue by henrebotha** [Aloxaf/fzf-tab#164]
The wiki is very terse and doesn't give much guidance for how to set up key bindings. I would like to configure <kbd>→</kbd> (the right arrow key) to accept the selected completion (i.e. the same thing that <kbd>Enter</kbd> does). How can I achieve this?

**Comment by Aloxaf** [comment]
```zsh
zstyle ':fzf-tab:*' fzf-bindings 'right:accept'
```

fzf-tab just passes this setting to fzf. So, for the detail of key bindings, you should see the man page of fzf.

**Comment by henrebotha** [comment]
Ah! That clarifies it. I'll update the wiki accordingly.
