### ISSUE TITLE
[FR] Support variables $word and $realpath in tag fzf-bindings

### ISSUE THREAD

**Issue by psicho2000** [Aloxaf/fzf-tab#165]
**Is your feature request related to a problem? Please describe.**
Up to commit 966e7b4, it was possible to use the current selection within a keybinding, using the somewhat hacky (but working) solution described in https://github.com/Aloxaf/fzf-tab/tree/966e7b47cd937014e8a0ec7de5273d3c60ffbeeb#configure. This way it was possible to copy the current search result to clipboard (useful for filenames, git hashes) or open the result in an editor (useful for files and directories).

**Describe the solution you'd like**
I would like to have the special variables `$word` and `$realpath`, which are now available for tag fzf-preview only, also for tag fzf-bindings.

**Describe alternatives you've considered**
No known workaround using the newest version of fzf-tab.

**Additional context**
Example configuration using fzf-tab until commit 966e7b4 can be found in my former dotfiles:
https://gitlab.com/psicho/dotfiles/-/blob/c9884be07ea9b19e787119ff7166c89cfcbc0575/lib/zsh/01-completion.zsh#L23

**Comment by Aloxaf** [comment]
Nice idea!

Implemented in https://github.com/Aloxaf/fzf-tab/commit/8584ed59107f37996b977a499ea0d536d851920d.

Example:
```zsh
zstyle ':fzf-tab:complete:*' fzf-bindings \
	'ctrl-v:execute-silent({_FTB_INIT_}code "$realpath")' \
    'ctrl-e:execute-silent({_FTB_INIT_}kwrite "$realpath")'
```

Do you have any other suggestions?

**Comment by psicho2000** [comment]
Works like a charm! Thanks for the quick implementation.
I suggest to add that in the docs for future readers.
