### ISSUE TITLE
[Q] How to start fzf-tab exactly after pressing / or ~

### ISSUE THREAD

**Issue by ahmadie** [Aloxaf/fzf-tab#166]
I would like to start fzf-tab exactly after pressing / or ~ to save me <tab> key press ! especially after cd or vim commands etc !

Thank you for this amazing plugin

**Comment by Aloxaf** [comment]
You can define a custom zle widget and bind it to <kbd>/</kbd> <kbd>~</kbd>.

a simple example:
```zsh
insert-and-complete() {
   zle self-insert
   # check if string "vim" or "cd" exists in the left of cursor
   if (( $LBUFFER[(I)(vim|cd)] != 0 )); then
       zle fzf-tab-complete
   fi
}
zle -N insert-and-complete
bindkey "/" insert-and-complete
bindkey "~" insert-and-complete
```

**Comment by ahmadie** [comment]
Thanks !!!
