### ISSUE TITLE
[BUG] fzf-tab does not respect colors set with $LS_COLORS

### ISSUE THREAD

**Issue by paradoxsupreme** [Aloxaf/fzf-tab#168]
fzf-tab does not read colors from $LS_COLORS.  Used zinit to install fzf-tab with 
`zinit ice atclone"dircolors -b LS_COLORS > clrs.zsh" \
atpull'%atclone' pick"clrs.zsh" nocompile'!' \
atload='zstyle ":completion:*" list-colors ${(s.:.)LS_COLORS}' \
zinit light trapd00r/LS_COLORS
`

**Environment:**
- Arch Linux
- zsh 5.8
- fzf-tab version https://github.com/Aloxaf/fzf-tab/commit/8584ed59107f37996b977a499ea0d536d851920d

**Comment by Aloxaf** [comment]
```zsh
zinit ice atclone"dircolors -b LS_COLORS > clrs.zsh" \
 atpull'%atclone' pick"clrs.zsh" nocompile'!' \
 atload='zstyle ":completion:*" list-colors ${(s.:.)LS_COLORS}' # <- no `\` here
zinit light trapd00r/LS_COLORS
```

Don't write everything in one line

**Comment by paradoxsupreme** [comment]
Still not working correctly though...
I tried this 
zinit ice atclone"dircolors -b LS_COLORS > clrs.zsh" \
 atpull'%atclone' pick"clrs.zsh" nocompile'!' \
 atload='export LS_COLORS="$(vivid generate plasticdreams)"' \
 atload='zstyle ":completion:*" list-colors ${(s.:.)LS_COLORS}' # <- no `\` here
zinit light trapd00r/LS_COLORS`
`
