### ISSUE TITLE
[BUG] Prompt Flashes on making a selection

### ISSUE THREAD

**Issue by acdifran** [Aloxaf/fzf-tab#172]
Frequently when making a selection from the list of options, the entire prompt line flashes. This doesn't occur on every selection though and never occurs if standard tab completion is triggered instead. It happens both when pressing "enter" and pressing "/" for continuation. You can see in the video, that it completes the first selection fine without "flashing" the prompt, but the next match causes it to flash.

![flashing_prompt](https://user-images.githubusercontent.com/25591626/104108705-a190ab80-527b-11eb-8e48-503b834eca51.gif)

1. Make a selection from the matches with either "enter" or "/"

 - OS: [macOS Big Sur 11.1]
 - zsh version 5.8
 - fzf-tab version latest

zshrc settings related to completion and fzf-tab:

```shell
zstyle ":completion:*" matcher-list \
  'b:=*' \
  "m:{a-zA-Z}={A-Za-z}" \
  "r:|[._-]=* r:|=*" \
  "l:|=* r:|=*"

zstyle ":completion:*:git-checkout:*" sort false
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':fzf-tab:*' single-group color header
zstyle ':fzf-tab:*' group-colors $FZF_TAB_GROUP_COLORS
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'exa -1 --color=always $realpath'
zstyle ':fzf-tab:complete:_zlua:*' query-string input
zstyle ':completion:*:*:git:*' script ~/.git-completion
```

Thanks for the awesome plugin!

**Comment by Aloxaf** [comment]
Does this happen when you disable other plugins?
Can you provide your plugin list and their load order?

**Comment by acdifran** [comment]
@Aloxaf thanks for the quick response! I've pasted all my plugins below, but it still happens even if I don't load any other plugins and remove the p10k theming and just use a bare prompt (see below).

![flashing_prompt2](https://user-images.githubusercontent.com/25591626/104117109-5dc99080-52d3-11eb-85d1-d6b070a6a02b.gif)

```shell
source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='fg=#8aff80'
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND='fg=#ff9580'
function _history_substring_search_config() {
    bindkey '^[[A' history-substring-search-up
    bindkey '^[[B' history-substring-search-down
}

zinit wait lucid light-mode for \
  atinit"zicompinit; zicdreplay" \
      Aloxaf/fzf-tab \
      zdharma/fast-syntax-highlighting \
  atload"_zsh_autosuggest_start" \
      zsh-users/zsh-autosuggestions \
  blockf atpull'zinit creinstall -q .' \
      zsh-users/zsh-completions
# NOTE The order is important here since it should be loaded before zsh-history-substring-search:
# https://github.com/zsh-users/zsh-history-substring-search#usage

# History substring search
zinit ice wait lucid atload'_history_substring_search_config' \
  ver'dont-overwrite-config'
zinit light 'ericbn/zsh-history-substring-search'
zinit light 'skywind3000/z.lua'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

zinit ice depth=1; zinit light romkatv/powerlevel10k
```

**Comment by Aloxaf** [comment]
Thanks for your report.
Please update and try again.

**Comment by acdifran** [comment]
Awesome! That fixed it! thank you
