### ISSUE TITLE
[BUG] fzf-tab doesn't work together with zsh-history-substring-search

### ISSUE THREAD

**Issue by Melkster** [Aloxaf/fzf-tab#177]
**Describe the bug**
fzf-tab doesn't trigger most of the time when [zsh-history-substring-search](https://github.com/zsh-users/zsh-history-substring-search) is also loaded.

**To reproduce**

1. Use the following `.zshrc` (or similar one that loads both plugins):

   ```zsh
   source /path/to/antigen.zsh

   antigen bundles << EOBUNDLES
     zsh-users/zsh-history-substring-search
     Aloxaf/fzf-tab
   EOBUNDLES

   antigen apply
   ```

1. Run `zsh`
1. Autocomplete a command like `cd ` with `Tab`
1. Nothing happens. (For some reason it does sometimes work, if so, repeat from **2.** and after at most a couple of tries it shouldn't work)

**Expected behavior**
Pressint `Tab` should complete using fzf as expected

**Environment (please complete the following information):**

- Arch Linux
- zsh version: zsh 5.8 (x86_64-pc-linux-gnu)
- latest

**Comment by Aloxaf** [comment]
I can't reproduce it. Can you make sure that this is the minimal zshrc that can reproduce this bug?

**Comment by Melkster** [comment]
Yes. I have confirmed that is the minimal `.zshrc` to reproduce the bug.

The odd thing is that any change to my `.zshrc` (including just adding a comment and saving) makes fzf-tab work as expected when I run zsh the first time, even with the apparently conflicting plugin. However after closing it and running a new instance of zsh, fzf-tab never works if `zsh-users/zsh-history-substring-search` (or [`zsh-users/zsh-syntax-highlighting`](https://github.com/zsh-users/zsh-syntax-highlighting) as well) are sourced from `.zshrc`.

So that yields the following steps to reproduce:

1. Use the following `.zshrc`:

   ```zsh
   source /path/to/antigen.zsh

   antigen bundles << EOBUNDLES
     zsh-users/zsh-history-substring-search
     Aloxaf/fzf-tab
   EOBUNDLES

   antigen apply
   ```

2. Run `zsh`.
3. Autocomplete a command like `cd ` with `Tab`.
4. It works. Now exit `fzf` and `zsh`.
5. Run `zsh` again.
6. Autocomplete a command like `cd ` with `Tab` again.
7. Nothing happens.

**Comment by Aloxaf** [comment]
https://github.com/Aloxaf/fzf-tab/blob/168cd530ba3c511cd9dd6e2932a995f262453994/README.md#L31

You forget to call compinit before init fzf-tab. The correct zsh is:

```zsh
source /path/to/antigen.zsh

autoload -Uz compinit
compinit

antigen bundles << EOBUNDLES
  zsh-users/zsh-history-substring-search
  Aloxaf/fzf-tab
EOBUNDLES

antigen apply
```

**Comment by Melkster** [comment]
Thank you, that solved it! I totally missed that.
