### ISSUE TITLE
[BUG] cursor not visible on fzf line editor

### ISSUE THREAD

**Issue by ashish-yadav11** [Aloxaf/fzf-tab#179]
When tab completing the cursor becomes invisible and remains so on the fzf line editor.

1. Type 'a'
2. Press <kbd>Tab</kbd>
4. The fzf window appears but the cursor doesn't show up on the line editor.

One would expect the cursor to become visible on the fzf line editor because it being invisible hampers editing.

 - OS: Arch Linux
 - zsh version: 5.8
 - fzf-tab version: latest

**Comment by Aloxaf** [comment]
Thanks for your report!

**Comment by ysl2** [comment]
+1
