### ISSUE TITLE
Missing descriptions

### ISSUE THREAD

**Issue by romkatv** [Aloxaf/fzf-tab#18]
To reproduce:

1. Install zsh 5.7.1 (I haven't tried any other version).
2. Run `git clone https://github.com/Aloxaf/fzf-tab.git ~/fzf-tab`.
3. Run `zsh -df`.
4. Run `autoload compinit && compinit`.
5. Type `grep --` and hit `TAB` and `y`.
6. Observe descriptions for on all completion candidates:
```text
adam% grep --
--after-context                   -- specify lines of trailing context
--basic-regexp                    -- use basic regular expression
--before-context                  -- specify lines of leading context
...
```
7. Hit Ctrl-C twice and run `source ~/fzf-tab/fzf-tab.zsh`.
8. Type `grep --` and hit `TAB`.
9. Observe the **unexpected** lack of descriptions:
```text
adam% grep --
> --                                                                                  
  46/46                                                                               
> --after-context                                                                     
  --basic-regexp                                                                      
  --before-context                                                                    
...
```

**Comment by Aloxaf** [comment]
Detected

**Comment by Aloxaf** [comment]
Fixed in https://github.com/Aloxaf/fzf-tab/commit/c58f11e4e5244a4681de9b61c0795f2ca698a6c3.
Please take a look~

**Comment by romkatv** [comment]
Works :+1: Thanks for the speedy fix!
