### ISSUE TITLE
[BUG] A command is not displayed correctly when performed with accept-line

### ISSUE THREAD

**Issue by dobrovolsky** [Aloxaf/fzf-tab#180]
#### Describe the bug

A command is not displayed correctly when performed with accept-line

#### .zshrc

```zsh
source $HOME/.dotfiles/deps/antigen/antigen.zsh

antigen bundle Aloxaf/fzf-tab

antigen apply

# accept with completion with space for fzf-tab
zstyle ':fzf-tab:*' fzf-bindings 'space:accept'
# execute a command right after pressing enter for fzf-tab
zstyle ':fzf-tab:*' accept-line enter
```

#### To Reproduce

1. Type `cd<space>`
2. Press `Tab`
3. Select some directory and press `enter`
4. Command is not displayed correctly in prompt
     The folder name is placed at the beginning of prompt

#### Expected behavior
A command is displayed fully in prompt

#### Screenshots

![](https://i.imgur.com/AigWuXi.png)

#### Environment:

 - OS: MacOS
 - zsh version: zsh 5.8 (x86_64-apple-darwin19.6.0)

**Comment by Aloxaf** [comment]
Thanks for your report!
