### ISSUE TITLE
[Q] tmux-popup breaks scroll in iTerm2

### ISSUE THREAD

**Issue by ArturZurawski** [Aloxaf/fzf-tab#181]
Hello, I noticed that using tmux-popup breaks scroll in iTerm2. To get it back I have to switch on and off Preferences>Appearance>Windows>Hide scrollbars option. Not sure if this is fzf-tab issue or Iterm, but running nested tmux sessions from command line seems not messing up with scrolling.

**Comment by Aloxaf** [comment]
Does `tmux popup -KE -R 'seq 5 | fzf'` break scroll as well?

**Comment by ArturZurawski** [comment]
Yes. It opens a window and I can scroll from 1-5, but after I close it I cannot scroll in main window anymore.

**Comment by ArturZurawski** [comment]
This one does not break anything.

**Comment by Aloxaf** [comment]
This seems to be a bug of tmux. I suggest submitting an issue to tmux's repo.

**Comment by ArturZurawski** [comment]
Will do. Thank you.
