### ISSUE TITLE
[BUG] Bell beeps after every completion

### ISSUE THREAD

**Issue by Mellbourn** [Aloxaf/fzf-tab#187]
#### Describe the bug
After every successful completion made using fzf-tab, the terminal bell is triggered.

- [ x] I am using the latest version of fzf-tab
- [ x] this is the minimal zshrc which can reproduce this bug
- [ x] fzf-tab is loaded after `compinit`
- [ x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [ x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce

1. Type `cd Do`
2. Press <kbd>Tab</kbd>
3. The alternatives `Documents` and `Downloads` are correctly displayed
4. press <kbd>Enter</kbd> to select `Documents`
5. The command `cd Documents` is correctly typed BUT
4. the bell (i.e. an audible beep) also occurs

I have the `Flash visual bell` option turned on in `iTerm2`, so I actually get both an audible beep and a flashing visual bell, confirming that it is indeed the terminal bell being executed.

(When there is no valid completion at all, and I press <kbd>Tab</kbd>, the bell is also triggered, but that seems normal to me.)

#### Expected behavior
The completion should be finished without making any sound

#### Environment:
 - OS: macOS Big Sur 11.2.1
 - zsh version: 5.8 (arm-apple-darwin20.2.0), also reproduced on x86 hardware

#### Minimal zshrc
```shell
source ~/.zinit/bin/zinit.zsh
autoload -U +X compinit && compinit
zinit load Aloxaf/fzf-tab
```

#### Workaround
I tested [these settings](https://blog.vghaisas.com/zsh-beep-sound/), but they did not help
```
unsetopt LIST_BEEP
unsetopt HIST_BEEP
```
The only thing that did work was this setting
```
unsetopt BEEP
```
But that turns off _all_ bells, which is undesirable to me.

**Comment by Aloxaf** [comment]
Thanks for your report!

Please update and try again.

**Comment by Mellbourn** [comment]
Yes. I can confirm that it is fixed now. 
That was really fast. Thanks!

**Comment by duqcyxwd** [comment]
This issue happened to me as well. I am using the latest version of `fzf-tab`.  

Do you mind @Aloxaf reopen this bug to track this issue? It can be reproduced in same way as @Mellbourn described above.

**Comment by Aloxaf** [comment]
> This issue happened to me as well. I am using the latest version of `fzf-tab`.

Will it happen if you `unsetopt LIST_BEEP`?

**Comment by duqcyxwd** [comment]
> Will it happen if you `unsetopt LIST_BEEP`?


I tested on my machine. Looks like there are two place need to be improved. 

Without `unsetopt LIST_BEEP`, bell beeps when **select a completion** or **exit without selection**.

With `unsetopt LIST_BEEP`, bell beeps only when I **exit without selection**.

**Comment by Aloxaf** [comment]
> With `unsetopt LIST_BEEP`, bell beeps only when I **exit without selection**.

This is expected. If you don't want beep, please `unsetopt beep`.
