### ISSUE TITLE
[BUG] Fuzzy selection not working on Ubuntu in WSL

### ISSUE THREAD

**Issue by Mellbourn** [Aloxaf/fzf-tab#189]
#### Describe the bug
When I press <kbd>Tab</kbd>, instead of showing completions, the same command line is just repeated.

Unambiguous completions are successful. The problem only occurs when there are multiple alternatives, so that the selection should be shown.

This only happens for me on Ubuntu running inside Windows Subsystem for Linux (WSL).
fzf-tab works fine for me on macOS and Raspbian.

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. Type `ls b`
2. Press <kbd>Tab</kbd>
4. Instead of letting me choose between the two available alternatives (`bin` and `backup`) the line with the prompt is duplicated, so a new prompt with the command `ls b` is shown.
5. Also, very briefly the following message flashes
```
unknown action reload(/usr/bin/zsh  /home/mellbourn/.zinit/plugins/Aloxaf---fzf-tab/lib/ftb-switch-group 32409 0 /tmp/zsh-fzf-tab-mellbourn -1)
```
(it is shown so briefly that I'm unsure if that is the exact text, especially the beginning is hard to see)

#### Expected behavior
At 4. above I expected to be able to choose between the two available completion alternatives (`bin` and `backup`) using a fzf-based interface.

#### Environment:
 - OS: Ubuntu inside WSL2. 
 - zsh version: [e.g. 5.8.1]

```
> uname -a
Linux MyComputerName 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> lsb_release -a
 No LSB modules are available.
 Distributor ID: Ubuntu
 Description:    Ubuntu 20.04.2 LTS
 Release:        20.04
 Codename:       focal
```

#### Minimal zshrc
```zsh
source ~/.zinit/bin/zinit.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
autoload -U +X compinit && compinit
zinit load Aloxaf/fzf-tab
```

**Comment by Aloxaf** [comment]
What's the fzf's version?

**Comment by Mellbourn** [comment]
```
> fzf --version
0.17.3 (390b496)   
```

**Comment by Mellbourn** [comment]
That was it! I upgraded to version 0.20.0 (what is installed by `apt`) and now it works. Thanks!
