### ISSUE TITLE
[Q] is it possible to map ctrl-semicolon for accept?

### ISSUE THREAD

**Issue by divramod** [Aloxaf/fzf-tab#192]
Hey, i just stumpled over fzf-tab.
It is awesome!!

Now i wanted to ask, if it is possible to map the following:
```
zstyle ':fzf-tab:*' fzf-bindings 'ctrl-;:accept'
```
I tried it, but everytime i press tab the completion just returns.

**Comment by Aloxaf** [comment]
> It is awesome!!

I'm glad that you like it.

> I tried it, but everytime i press tab the completion just returns.

According to fzf's manual, you can only use `ctrl-{[a-z],space,\,],^,/,alt-[a-z]}`. So it's impossible to map ctrl-semicolon for accept.

**Comment by NICHOLAS85** [comment]
Depending on the terminal multiplexer you use you may be able to rebind the key press to one fzf supports. For example ctrl-; to esc-c or something. I know Konsole supports this and am aware others do too.
