### ISSUE TITLE
[Q] How to show hidden folders?

### ISSUE THREAD

**Issue by dycw** [Aloxaf/fzf-tab#193]
I have `fzf` setup with

```
export FZF_DEFAULT_COMMAND='fd -HL -c=always -E=.git -E=node_modules'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND -t=f -t=d"
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND -t=d"
```

by following the `README` and issues in the `fzf` [repo](https://github.com/junegunn/fzf). [`fd`](https://github.com/sharkdp/fd) is well-known to `fzf` users I believe, and thus the above allows my Ctrl-T and Alt-C to both reveal hidden files/holders.

I'm struggling to see hidden files/folders here.

Whilst I thought this might be a `zsh` issue, some searching (e.g. [link](https://unix.stackexchange.com/questions/308315/how-can-i-configure-zsh-completion-to-show-hidden-files-and-folders)) and playing around still hasn't worked for me. For example, the aforementioned link suggests

```
setopt globdots
```

and 

```
compinit
_comp_options+=(globdots)
``` 

I didn't seem to be getting anywhere. Any ideas?

**Comment by Aloxaf** [comment]
`setopt globdots` should work. How did you test it?

![image](https://user-images.githubusercontent.com/17017672/108942677-6531d700-7692-11eb-95c5-8d47ab393624.png)

**Comment by dycw** [comment]
Suddenly it's working for me again. Most bizarre.

Thanks for a great plugin!

**Comment by wojcraftinho** [comment]
Dear @Aloxaf,

can you tell me how to do same but with files? I solved problem with directories, but I don't know solution with hidden files. It would be very nice 👍🏻

With Regards,
Wojcraftinho
