### ISSUE TITLE
[Q] Not possible to bind switch-group to '^h' '^l'?

### ISSUE THREAD

**Issue by nichobi** [Aloxaf/fzf-tab#194]
`zstyle ':fzf-tab:*' switch-group '^h' '^l'`
The line above causes fzf-tab to crash immediately upon hitting tab, with `unsupported key: ^h` appearing for a brief moment before being overwritten by the prompt. Am I doing something wrong here, is this just not possible, or is it a bug?

**Comment by Aloxaf** [comment]
You should use `ctrl-h` and `ctrl-l`. See fzf's manual for detail.

**Comment by nichobi** [comment]
Ah, I assumed the binding was handled by zsh, thank you!
