### ISSUE TITLE
[Q] How do I get the completion candidates for a given partial command?

### ISSUE THREAD

**Issue by NightMachinary** [Aloxaf/fzf-tab#196]
I want to get the possible completions for a command. This is useful for me because I have a tunnel between a Telegram bot and my server's zsh, which can execute non-interactive commands.

```
get-completions ls -a ./sth
# should return possible completions
```

**Comment by Aloxaf** [comment]
Please check https://github.com/Valodim/zsh-capture-completion

**Comment by NightMachinary** [comment]
> Please check https://github.com/Valodim/zsh-capture-completion

I had tried that before, I remember it not working well. I thought perhaps fzf-tab has improved upon it.

**Comment by Aloxaf** [comment]
> I had tried that before, I remember it not working well.

What problem did you encounter?

> I thought perhaps fzf-tab has improved upon it.

Not much. They do the same thing basically. fzf-tab is mainly optimized for an interactive session.
