### ISSUE TITLE
[Q] fzf-tab & zsh-autocomplete compatibility check?

### ISSUE THREAD

**Issue by fhill2** [Aloxaf/fzf-tab#198]
Can fzf-tab & zsh-autocomplete(https://github.com/marlonrichert/zsh-autocomplete) both work together?

When I load both, `cd<space>`, execute prompt: `fzf-tab-complete` 
fzf isnt showing.

**Comment by Aloxaf** [comment]
Just let fzf-tab hook `compadd` every time.

```zsh
my-fzf-tab() {
  functions[compadd]=$functions[-ftb-compadd]
  zle fzf-tab-complete
}
zle -N my-fzf-tab
bindkey "^I" my-fzf-tab
```

**Comment by fhill2** [comment]
I have just got round to testing this. Works perfect. Thank you.

**Comment by fujianyawa** [comment]
Hello, I'm using zsh-autocomplete too,

I did try to copy this snippet and add it to my zshrc, and fzf-tab didn't seem to working when i press tab nothing happens.
> Just let fzf-tab hook `compadd` every time.
> 
> ```shell
> my-fzf-tab() {
>   functions[compadd]=$functions[-ftb-compadd]
>   zle fzf-tab-complete
> }
> zle -N my-fzf-tab
> bindkey "^I" my-fzf-tab
> ```

Here's my .zshrc config
```sh
source $HOME/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh

pokemon-colorscripts -r --no-title; tput setaf 4 && tput bold; fortune
export "PATH=${PATH}:${HOME}/.local/bin"

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_TMUX_AUTOSTART="true"

plugins=(
  fd
  git
  ripgrep
  tmux
  zsh-autocomplete
  zsh-autosuggestions
  zsh-syntax-highlighting
  fzf
  fzf-tab
)

source $ZSH/oh-my-zsh.sh

source /usr/share/zsh/site-functions/fzf
zstyle ':autocomplete:tab:*' fzf-completion yes

my-fzf-tab() {
  functions[compadd]=$functions[-ftb-compadd]
  zle fzf-tab-complete
}
zle -N my-fzf-tab
bindkey "^I" my-fzf-tab  

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# import custom aliases and function
[ -f $HOME/.zsh_aliasrc ] && source $HOME/.zsh_aliases
[ -f $HOME/.profile ] && source $HOME/.profile

```

**Comment by Aloxaf** [comment]
@fujianyawa
Well, this seems more difficult than it was a year ago. Both plugins do too many hooks to zsh. I suggest you use only one of them.

**Comment by dhorkin** [comment]
> @fujianyawa Well, this seems more difficult than it was a year ago. Both plugins do too many hooks to zsh. I suggest you use only one of them.

Your workaround seems to mostly work for me, but it causes some sort of weird render issue. I mentioned this here: https://github.com/marlonrichert/zsh-autocomplete/issues/501#issuecomment-1446034709

But for your convenience:

With fzf-tab enabled and zsh-autocomplete disabled:
![image](https://user-images.githubusercontent.com/16787581/221533730-49670269-ebcc-42b1-b07d-fa2b5a27fa03.png)

With both enabled and your workaround:
![image](https://user-images.githubusercontent.com/16787581/221533775-5870f012-e772-4f48-b04a-9213a3f6c64a.png)

Incidentally, both of these look different than your example video:
![image](https://user-images.githubusercontent.com/16787581/221534269-19017222-9c07-4521-9990-3faf8c7b07ef.png)

although if I add `zstyle ':fzf-tab:*' show-group brief` it looks close:
![image](https://user-images.githubusercontent.com/16787581/221535703-49a67eee-3ab7-4216-a519-25ac73988603.png)

My guess is zsh-autocomplete is failing to do variable expansion or something, but I was wondering if perhaps there were some zstyle settings that I am missing.

**Comment by dhorkin** [comment]
The dev for zsh-autocomplete [had this to say](https://github.com/marlonrichert/zsh-autocomplete/issues/501#issuecomment-1446344043) about the erroneous %s in the groups:
> @dhorkin No, the problem is that Fzf Tab doesn't know how to parse the [prompt escape sequences](https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html) that are allowed in the completion system's [format style](https://zsh.sourceforge.io/Doc/Release/Completion-System.html#index-format_002c-completion-style). You should file a bug with Fzf Tab about this.
