### ISSUE TITLE
[BUG] Error when source zshrc file

### ISSUE THREAD

**Issue by hao-lh** [Aloxaf/fzf-tab#200]
#### Describe the bug
When install fzf-tab with Oh-My-Zsh and added fzf-tab in plugins, I tried to source .zshrc and get following errors:
~/.oh-my-zsh/custom/plugins/fzf-tab/lib/zsh-ls-colors/ls-colors.zsh:114: parse error near `fi'
~/.oh-my-zsh/custom/plugins/fzf-tab/fzf-tab.plugin.zsh:345: unknown file attribute: \n

#### Screenshots
<img width="794" alt="Screen Shot 2021-03-05 at 4 17 19 AM" src="https://user-images.githubusercontent.com/14138581/110026619-d1d06400-7d6b-11eb-97ae-77a6768cfc7a.png">

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. source .zshrc

#### Expected behavior
source .zshrc would be successfully updated.

#### Environment:
 - OS: macOS 10.11.6
 - zsh version: zsh 5.0.8 (x86_64-apple-darwin15.0)

#### Minimal zshrc
export ZSH="/Users/Apple/.oh-my-zsh"
autoload -U compinit && compinit
plugins=(git
	zsh-completions
	fzf-tab
	zsh-syntax-highlighting
	zsh-autosuggestions
	history-substring-search
	)
source $ZSH/oh-my-zsh.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

**Comment by Aloxaf** [comment]
I guess you need to update your zsh: https://github.com/Aloxaf/fzf-tab/issues/184

**Comment by hao-lh** [comment]
Wonderful insight!

I used zsh 5.0.8 (x86_64-apple-darwin15.0) before on macOS 10.11.6 machine, as homebrew does not provide binary bottle for this package anymore, by default it would not compile from source, and seemed this is the latest zsh version for my machine and got this problem.

Even thought I spent me half a day upgrading `zsh 5.0.8 (x86_64-apple-darwin15.0)` to `zsh 5.8 (x86_64-apple-darwin15.6.0)`, this issue was successfully resolved.

Thank you Aloxaf 😄

**Comment by hao-lh** [comment]
One more comment for those was not able to compile from source and are using iTerm
You can open `Preferences` -> `Profiles` -> `General`
Check `Command` rather than `Login shell` and add `/usr/local/Cellar/zsh/5.8_1/bin/zsh` depending on your actual binary zsh file
