### ISSUE TITLE
When using --border in the default options one result item is clipped

### ISSUE THREAD

**Issue by xbb** [Aloxaf/fzf-tab#201]
#### Describe the bug

When using `--border` in the default options (`FZF_DEFAULT_OPTS`) one result item is clipped when using the default calculated height.

Considering +2 lines in `-ftb-fzf` seems to fix the issue.

#### Screenshots

Without `--border`

![image](https://user-images.githubusercontent.com/239074/110208780-67ade100-7e89-11eb-8778-fc7469fa7bfd.png)

With `--border`

![image](https://user-images.githubusercontent.com/239074/110208738-3a613300-7e89-11eb-8161-70983f357827.png)

**Comment by Aloxaf** [comment]
You can use `zstyle ':fzf-tab:*' fzf-pad 4`

**Comment by xbb** [comment]
That works for me, thanks
