### ISSUE TITLE
[FR] Map TAB to "accept" when there is only one item

### ISSUE THREAD

**Issue by jmgq** [Aloxaf/fzf-tab#202]
This feature is better described with an example:

Let's say that if you go to your home folder and type `less .zsh` and then press <kbd>TAB</kbd>, you will be presented with a list with three options:
- `.zshrc`
- `.zshenv`
- `.zsh_hist`

Every time you press <kbd>TAB</kbd>, it will highlight the next item, as you would expect. However, if you type the letter `r`, the list of suggestions will be filtered, and the only available option will be `.zshrc`. 

In this case, when there is just one option available, I think that if you press <kbd>TAB</kbd> again, it would be good if `.zshrc` was automatically selected, since it's the only available option. But instead, nothing happens until you press <kbd>ENTER</kbd>, in which case the option is selected.

After checking the `fzf` manual, I noticed that there is a flag called `--select-1` under the "Scripting" section, and its description reads "Automatically select the only match". I have tried the following configurations, with no success:
```zsh
zstyle ':fzf-tab:*' fzf-flags --select-1
zstyle ':fzf-tab:*' extra-opts '--select-1'
export FZF_DEFAULT_OPTS="--select-1"
```

I have also tried `zstyle ':fzf-tab:*' fzf-bindings 'tab:accept'`, but that of course removes the cycling with <kbd>TAB</kbd> feature (you'll have to use the arrow keys to navigate through the options).

**Comment by Aloxaf** [comment]
`--select-1` only works on the initial input, like `echo a | fzf --select-1`.

I think there is no way to implement it.

**Comment by jmgq** [comment]
Fair enough, thanks for looking into it anyway. I wish I could help or suggest something, but I wouldn't know where to start, so please feel free to close this issue if it looks like it cannot be done.

**Comment by Andrej-Marsic** [comment]
fzf has the event [one](https://github.com/junegunn/fzf/issues/459#issuecomment-1826150041). So this could be possible.

**Comment by snmaynard** [comment]
Indeed `zstyle ':fzf-tab:*' fzf-bindings 'one:accept'` will automatically accept the completion when there is only one possible result.
