### ISSUE TITLE
empty candidates after type some characters

### ISSUE THREAD

**Issue by tshu-w** [Aloxaf/fzf-tab#203]
#### Describe the bug

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### Describe the bug
empty candidates after type some characters:
<img width="342" alt="Screen Shot 2021-03-10 at 21 02 14" src="https://user-images.githubusercontent.com/13161779/110633608-ee452400-81e3-11eb-859a-440f98ab7e95.png">
<img width="317" alt="Screen Shot 2021-03-10 at 21 02 21" src="https://user-images.githubusercontent.com/13161779/110633622-f0a77e00-81e3-11eb-8336-6df49d96f9b2.png">

I also have an issue when switching groups.
<img width="1576" alt="Screen Shot 2021-03-10 at 21 06 47" src="https://user-images.githubusercontent.com/13161779/110634097-89d69480-81e4-11eb-8932-1957b8d9fd04.png">

#### To Reproduce
1. Type cd
2. Press <kbd>Tab</kbd>
3. Type any directory prefix

#### Environment:
 - OS: Ubuntu
 - zsh version: zsh 5.8 (x86_64-ubuntu-linux-gnu)

#### Minimal zshrc
```
declare -A ZINIT

ZSH_CACHE_DIR=$XDG_CACHE_HOME/zsh
ZINIT_HOME=$XDG_DATA_HOME/zinit
ZINIT[HOME_DIR]=$ZINIT_HOME
ZINIT[ZCOMPDUMP_PATH]=$ZSH_CACHE_DIR/zcompdump

if [[ ! -f $ZINIT_HOME/bin/zinit.zsh ]]; then
  git clone https://github.com/zdharma/zinit.git $ZINIT_HOME/bin
	zcompile $ZINIT_HOME/bin/zinit.zsh
fi
source $ZINIT_HOME/bin/zinit.zsh

autoload -Uz compinit; compinit -D $ZINIT[ZCOMPDUMP_PATH] && zinit cdreplay -q
zstyle ':completion::complete:*' cache-path $ZSH_CACHE_DIR/zcompcache

# emacs completion
# declare -f compdef &>/dev/null && compdef _gnu_generic emacs emacsclient

# fzf
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse'
if  command -v brew &> /dev/null ; then
    [ -f $XDG_CONFIG_HOME/fzf/fzf.zsh ] \
        || $(brew --prefix)/opt/fzf/install --xdg --key-bindings --completion --no-update-rc --no-bash --no-fish
    source $XDG_CONFIG_HOME/fzf/fzf.zsh
else
    source $JUNEST_HOME/usr/share/fzf/key-bindings.zsh
    source $JUNEST_HOME/usr/share/fzf/completion.zsh
fi

zinit light Aloxaf/fzf-tab
zstyle ':fzf-tab:*' default-color $''
# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'
# switch group using `,` and `.`
zstyle ':fzf-tab:*' switch-group ',' '.'
```

**Comment by tshu-w** [comment]
BTW, everything works fine on my macbook

**Comment by Aloxaf** [comment]
which version of fzf are you using?

**Comment by tshu-w** [comment]
> which version of fzf are you using?

I install fzf through pacman recently in Junest so I think its fzf 0.25.1-2(I will check tomorrow). just run fzf works fine on my side.

**Comment by Aloxaf** [comment]
Can you provide the following files?:

1. trigger completion with tab (keep fzf running) and provide `${TMPPREFIX:-/tmp/zsh}-fzf-tab-$USER/completions.$$`
2. trigger completion with `C-x .` and provide the log.

**Comment by tshu-w** [comment]
1. cd, press `tab` and enter `a` like above: [completions.56792.txt](https://github.com/Aloxaf/fzf-tab/files/6121741/completions.56792.txt)（Changed the suffix name for successful upload）
2. cd, enter `a` and press `C-x .` [zsh-56792-fzf-tab-1.log](https://github.com/Aloxaf/fzf-tab/files/6121759/zsh-56792-fzf-tab-1.log)

**Comment by Aloxaf** [comment]
The second log is incomplete.

Does this bug still exist after commenting out this line: `source $JUNEST_HOME/usr/share/fzf/completion.zsh` ?

If still exists, please keep commenting out this line and provide the second log again.

**Comment by tshu-w** [comment]
here is the log: [zsh-228125-fzf-tab-2.log](https://github.com/Aloxaf/fzf-tab/files/6122386/zsh-228125-fzf-tab-2.log)

**Comment by tshu-w** [comment]
BTW, I found a way to reproduce it.
1. git clone https://github.com/fastai/fastmac
2. run linux action
3. ssh remote
4. git clone https://github.com/tshu-w/dotfiles
5. cd dotfiles && make
6. sudo apt install zsh
7. zsh

**Comment by Aloxaf** [comment]
Does this problem exist if you use native fzf instead of which from junest?

**Comment by tshu-w** [comment]
Sorry, I'm such an idiot. The problem is that fzf installed with junest does not get the files in the /tmp directory.
