### ISSUE TITLE
[Q] Different fzf-preview commands for files and directories?

### ISSUE THREAD

**Issue by max-ae** [Aloxaf/fzf-tab#207]
Is it possible to set different preview commands for files and directories?

For example something like:

```
zstyle ':fzf-tab:complete:*:directories' fzf-preview 'exa $realpath'
zstyle ':fzf-tab:complete:*:files' fzf-preview 'less $realpath'
```

At the moment, I do something like this:
```
zstyle ':fzf-tab:complete:*' fzf-preview '
if [[ -d $realpath ]]; 
then 
    exa --color=always $realpath
elif [[ -f $realpath ]];
then
    less $realpath
fi
'
```

but this obviously shows empty preview windows for regular command completion.

**Comment by max-ae** [comment]
Okay, thanks!

**Comment by nlahmi** [comment]
For refernce, I managed to hack my way into making it kinda work by doing something like this:
```
zstyle ':fzf-tab:complete:*:*' fzf-preview 'zsh -c "if [ -e $realpath -a -d $realpath ]; then ls --color $realpath -a; fi; if [ -e $realpath -a -f $realpath ]; then bat --color=always --style=header,grid --line-range :300 $realpath; fi"'
```
(In this case, using zsh and bat - but could be easily changed)

One major problem is that for any other preview that's not files or directories, it still shows the current dir listing on the side (in addition to whatever completion it needs to show)

**Comment by shiftgeist** [comment]
In case anyone finds this in the future, I managed to make it work like this:

```
zstyle ':fzf-tab:complete:*:*' fzf-preview 'bat --color=always --style=numbers --line-range=:500 $realpath 2>/dev/null || eza -la --color=always $realpath'
```

**Comment by infinite-ram** [comment]
> In case anyone finds this in the future, I managed to make it work like this:
> 
> ```
> zstyle ':fzf-tab:complete:*:*' fzf-preview 'bat --color=always --style=numbers --line-range=:500 $realpath 2>/dev/null || eza -la --color=always $realpath'
> ```

@shiftgeist, your awesome thank you.

@Aloxaf, do we need to add this to the docs somewhere?
