### ISSUE TITLE
[BUG] The tmux popup window size is not properly

### ISSUE THREAD

**Issue by HanleyLee** [Aloxaf/fzf-tab#208]
## The tmux popup window size is not properly

I can make sure:
- [x ] I am using the latest version of fzf-tab
- [x ] this is the minimal zshrc which can reproduce this bug
- [x ] fzf-tab is loaded after `compinit`
- [ x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x ] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

### Describe the bug

I love fzf-tab, it make my operation in terminal smoothly.

A few days, I update my tmux to 3.2, this version have a major feature -- popup window. I know fzf-tab have its `ftb-tmux-pop` command to interact with this tmux feature. After I configure like follow:

```bash
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
zstyle ':fzf-tab:*' popup-pad 30 0
```

I can use popup window feature, but the popup window size seems not properly. the window is nested like below:

![image](https://user-images.githubusercontent.com/35610874/115134975-7fab7f80-a047-11eb-85ba-3f1a62b3dc0b.png)

the real window is inner window, the rest area is blank.

And if the count of the list element is small, it will not show all element. Like below:

![image](https://user-images.githubusercontent.com/35610874/115134972-7a4e3500-a047-11eb-8a22-624b9c2cbe0c.png)

This case is only apply to `ftb-tmux-pop`, it will show correct popup window if I invoke fzf default command `C-R` or `C-T`, like below

![image](https://user-images.githubusercontent.com/35610874/115134984-8cc86e80-a047-11eb-9a1b-57345c453565.png)

### Expected behavior

I don't know it's my error in operation or a tiny bug of this tool, I hope I can get a properly popup window.

### Environment:
 - OS: macOS Big Sur 11.2.3
 - zsh version: zsh 5.8 (x86_64-apple-darwin20.0)
 - tmux version: 3.2
 - fzf-tab version: Latest(until 2021-04-18)

### Minimal zshrc

```zsh
FZF_HIDDEN_PREVIEW="fzf-tmux -p 90%,80% --preview-window down:3:hidden:wrap --height 60% --reverse --bind '?:toggle-preview'"
export FZF_DEFAULT_COMMAND="fd --hidden --follow -I --exclude={Pods,.git,.idea,.sass-cache,node_modules,build} --type f"
export FZF_DEFAULT_OPTS="
--color=dark
--color=fg:#707a8c,bg:-1,hl:#3e9831,fg+:#cbccc6,bg+:#434c5e,hl+:#5fff87
--color=info:#af87ff,prompt:#5fff87,pointer:#ff87d7,marker:#ff87d7,spinner:#ff87d7
--height 60%
--layout reverse
--sort
--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -N -C {}) 2> /dev/null | head -500'
--preview-window right:50%:wrap
--bind '?:toggle-preview'
--border
--cycle
"
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
export FZF_CTRL_T_OPTS=$FZF_DEFAULT_OPTS
export FZF_CTRL_R_OPTS="
--layout=reverse
--sort
--exact
--preview 'echo {}'
--preview-window down:3:hidden:wrap
--bind '?:toggle-preview'
--border
--cycle
"

export FZF_ALT_C_OPTS="--preview 'tree -N -C {} | head -500'"
export FZF_TMUX_OPTS="-p 90%,80%" # 控制着fzf的window 是 popup 的还是 split panel 的
export FZF_COMPLETION_TRIGGER='**'

zstyle ':fzf-tab:complete:_zlua:*' query-string input
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
zstyle ':fzf-tab:*' popup-pad 30 0
zstyle ':fzf-tab:*' fzf-flags --preview-window=down:3:hidden:wrap
zstyle ':fzf-tab:*' fzf-pad 4
zstyle ":completion:*:git-checkout:*" sort false
zstyle ':completion:*:exa' file-sort modification
zstyle ':completion:*:exa' sort false

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Common ICE modifiers
@zi_lucid() {
    zinit ice lucid "$@"
}

@zi_w0() {
    @zi_lucid wait'0' "$@"
}

@zi_w1() {
    @zi_lucid wait'1' "$@"
}

@zi_completion() {
    @zi_w1 as'completion' blockf "$@"
}

@zi_w0 atload'_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions

# 语法高亮
@zi_w0 atinit='zpcompinit'
zinit light zdharma/fast-syntax-highlighting

@zi_w0
zinit light zsh-users/zsh-completions

# @zi_w0
# zinit light urbainvaes/fzf-marks

# @zi_w0
# zinit light skywind3000/z.lua

@zi_w0 has'fzf'
zinit light Aloxaf/fzf-tab

# ========

zinit snippet OMZL::git.zsh
zinit snippet OMZL::functions.zsh
zinit snippet OMZL::completion.zsh
zinit snippet OMZL::history.zsh
zinit snippet OMZL::key-bindings.zsh
zinit snippet OMZL::theme-and-appearance.zsh
```

**Comment by Aloxaf** [comment]
Can you use `C-x .` to trigger completion and provide its output?

**Comment by HanleyLee** [comment]
![image](https://user-images.githubusercontent.com/35610874/115256150-8cbc9180-a161-11eb-99f6-fd132f97349c.png)

**Comment by HanleyLee** [comment]
and this is the debug log file, just 3 line
![image](https://user-images.githubusercontent.com/35610874/115256581-ede46500-a161-11eb-81f5-5aad55abd05e.png)

**Comment by Aloxaf** [comment]
Oh, you load fzf-tab with the wrong order. Please fix this and try again.

> NOTE: fzf-tab needs to be loaded after compinit, but before plugins which will wrap widgets, such as zsh-autosuggestions or fast-syntax-highlighting

**Comment by HanleyLee** [comment]
I revise the order of the plugin after you mentioned it, but but the popup window is still not properly as before.

I use `zinit` as my zsh plugin manager, the above is my config file for zsh environment,  and I try to reduce the plugin number to provide a minimal reproducible environment.

```bash
### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

autoload -Uz compinit
compinit

zinit light Aloxaf/fzf-tab
zinit light zsh-users/zsh-autosuggestions
zinit light zdharma/fast-syntax-highlighting
```

Please mention me if find something wrong

**Comment by Aloxaf** [comment]
Can you provide the log again?

**Comment by HanleyLee** [comment]
I generate the log again after I reduce the number of my plugin. While the log file have more than 80k line, I can't attach it to this issue, so I put it in [here](http://sendanywhe.re/IYW4RI44). Please download and review it.

**Comment by Aloxaf** [comment]
Please start tmux before `export FZF_DEFAULT_OPTS...` and try again.

Or remove `--height 60%` from `FZF_DEFAULT_OPTS`.

**Comment by HanleyLee** [comment]
<img width="828" alt="image" src="https://user-images.githubusercontent.com/35610874/115694876-db517200-a393-11eb-9630-595a4b5b6a80.png">

yes! the popup window of `ftb-tmux-popup` is work properly after i remove `--height 60%` from `FZF_DEFAULT_OPTS`. So i can't config `--height 60%`? Is it a bug or my error in operation?

**Comment by Aloxaf** [comment]
The fzf window in the popup must be full height.

I suggest you start tmux before setting these environment variables, so
that tmux's subprocess won't be affected by them.

Hanley Lee ***@***.***> 于 2021年4月22日周四 17:58写道：

**Comment by HanleyLee** [comment]
OK, thanks!

原来是国人开发的, 非常感谢你热心解惑😄!

**Comment by noboruma** [comment]
@HanleyLee could you please describe your fix?
I am running the exact same problem within `tmux`, despite `tmux` starting before `zsh`.
What I noticed is I always have 2 items hidden. If my folder contains 5 files, it will only show 3. If 10, it will show 8, even if there is room to display everything.

**Comment by HanleyLee** [comment]
@noboruma this bug disappeared after i remove `--height` from `FZF_DEFAULT_OPTS`. If you have this bug after do this, you can try `echo FZF_DEFAULT_OPTS` on your shell, and put the results here.
