### ISSUE TITLE
[Q] Highlight color not selected line customizeable?

### ISSUE THREAD

**Issue by uloco** [Aloxaf/fzf-tab#210]
Is the highlight color of the non selected line customizeable? I have tried a lot of stuff (and I don't want to use groups or anything) but it's always white. I want it to be the same color as the highlight in the selected line.
I have customized fzf itself like so but it does not apply to fzf-tab

```
export FZF_DEFAULT_OPTS='
  --color fg:-1,bg:-1,hl:12,fg+:15,bg+:0,hl+:12
'
```

**Comment by Aloxaf** [comment]
How about `zstyle ':fzf-tab:*' fzf-flags --color=fg:-1,bg:-1,hl:12,fg+:15,bg+:0,hl+:12`?

**Comment by uloco** [comment]
How did I miss that? Thanks a lot! Also a really great project :)))
