### ISSUE TITLE
[FR] Change tab keybinding

### ISSUE THREAD

**Issue by himat** [Aloxaf/fzf-tab#214]
**Describe the solution you'd like**

I actually don't want fzf-tab to get called when pressing tab, but for it to instead trigger when I press shift-tab (this is because I use tab to accept the autosuggested history completion in zsh, and pressing the right arrow key is too far compared to easily pressing the tab key).

Is there a way to change the default keybinding?

**Comment by Aloxaf** [comment]
Add these lines to your zshrc:

```zsh
bindkey "^[[Z" fzf-tab-complete
bindkey "^I" expand-or-complete
```

**Comment by rkachach** [comment]
Is it possible to have the **first** "tab" press bring the fzf selection list and then the **second** tab just select the currently selected option(s) instead of having to press Enter key?

**Comment by Aloxaf** [comment]
@rkachach 
```
zstyle ':fzf-tab:*' fzf-bindings 'tab:accept'
```

**Comment by rkachach** [comment]
@Aloxaf works like a charm. Thank you very much :)
