### ISSUE TITLE
[Q] Hitting tab only show dotfiles

### ISSUE THREAD

**Issue by drewauff** [Aloxaf/fzf-tab#217]
when I hit tab it now only shows dot files and nothing else. How can I fix this?

Should note that for some reason setting FZF_DEFAULT_COMMAND has no effect whereas sett FZF_DEFAULT_OPTS does.

I was thinking of remapping tab to the default, but i couldnt find the default command.

**Comment by Aloxaf** [comment]
Both FZF_DEFAULT_COMMAND and FZF_DEFAULT_OPTS are abandoned and won't work. Please make sure you are using the latest version.
