### ISSUE TITLE
[Q] Is there a way to set the minimum width of fzf-tmux-popup?

### ISSUE THREAD

**Issue by tru2dagame** [Aloxaf/fzf-tab#218]
**Describe your question**
I really like the fzf-tmux-popup feature.

But sometimes it seems the width is too small and can't see the whole words.

<img width="608" alt="image" src="https://user-images.githubusercontent.com/1673006/125890827-b1856975-1922-4d87-ad6b-f32f55b19593.png">

**Comment by Aloxaf** [comment]
That's strange.

What's the output of `awk 'length > max_length { max_length = length; } END { print max_length }' <<< $'1\n11\n111'`?

**Comment by tru2dagame** [comment]
```
❯ awk 'length > max_length { max_length = length; } END { print max_length }' <<< $'1\n11\n111'
3
```

**Comment by Aloxaf** [comment]
The width of popup is calculated by these lines, which is expected to fit the content.

https://github.com/Aloxaf/fzf-tab/blob/89a33154707c09789177a893e5a8ebbb131d5d3d/lib/ftb-tmux-popup#L51
https://github.com/Aloxaf/fzf-tab/blob/89a33154707c09789177a893e5a8ebbb131d5d3d/lib/ftb-tmux-popup#L70

Does this often happen?
Does this happen on specific command or randomly?

**Comment by tru2dagame** [comment]
@Aloxaf This happens sometimes. It seems to happen when the tab completion is very very long.

**Comment by tru2dagame** [comment]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/1673006/128645084-3cb9f4c6-cd63-4baa-a471-8311644949f6.png">

```
mkdir test 
cd test

for i in {1..501}; do touch '$_'$i; done

ls <tab>
```

**Comment by tru2dagame** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/1673006/128645134-6ee97326-78eb-4796-ac95-148a1cc1d4e4.png">

It seems number `501` would cause this issue, but number `500` not.

**Comment by Aloxaf** [comment]
That's strange

Can you trigger completion with `C-x .` and provide the log here?

**Comment by tru2dagame** [comment]
```
     +fzf-tab-debug:9> : zsh 5.8
     +fzf-tab-debug:10> zle .fzf-tab-orig-fzf-completion
     +fzf-tab-debug:11> unsetopt xtrace
```

**Comment by Aloxaf** [comment]
https://github.com/Aloxaf/fzf-tab/issues/205#issuecomment-814524654

**Comment by BirkhoffLee** [comment]
@Aloxaf Same here, logs: https://gist.githubusercontent.com/BirkhoffLee/0d28c2e855f4dfc5f2f33216e1e1e488/raw/4123c3cd25c65e5e63d061861c6315880a45fdba/zsh-78389-fzf-tab-1.log

Screenshot: 
<img width="839" alt="CleanShot 2021-09-11 at 23 11 05@2x" src="https://user-images.githubusercontent.com/8148095/132952487-c4f46d60-b185-477f-af75-d32b8dac69b7.png">

**Comment by zbirenbaum** [comment]
I fixed this as a subset of of the issue I mentioned in #235. I need to fork and move some stuff over to the main code as flags rather than functions in my config but there will be a PR fairly soon. Features for pop up and normal will include: set proportion of columns/lines and auto resize on terminal resize. For pop-up specifically, you can also change the proportion of the pop up a preview takes up, which in conjunction with setting proportion of terminal pop up takes up, fixes this issue. 

I am also considering implementing functions for flat values since that is super easy, and the same as above with just one less calculation. but it seems like it would also be less useful than percentages, however I am open to input.

**Comment by Aloxaf** [comment]
Closed, this might be a bug of nawk. I have updated the code to always use gawk now.

**Comment by ins0mniaque** [comment]
I'm having the same bug here, on macOS 12.3. I don't have gawk installed. Here's my awk (nawk) version:
```
# awk --version
awk version 20200816
```

To fix this, I've replaced https://github.com/Aloxaf/fzf-tab/blob/e8145d541a35d8a03df49fbbeefa50c4a0076bbf/lib/ftb-tmux-popup#L41-L53

with

```zsh
# get the size of content, note we should remove all ANSI color code
comp_length=$popup_pad[1]
comp_lines=$popup_pad[2]
for line in ${(f)mapfile[$tmp_dir/completions.$$]}; do
  length=${(m)#${(S)line//$'\x1b['[0-9]#*m}}
  (( length >= comp_length )) && comp_length=$length
  ((comp_lines++))
done
```

and everything works. I also seem to get similar performance to using awk, even with > 20000 entries.


Is there any reason why 500 lines was chosen as the limit?
And is the zsh code above slow enough to warrant the using awk?

**Comment by Aloxaf** [comment]
>  I also seem to get similar performance to using awk, even with > 20000 entries.

That's strange. My test result is pure zsh is much slower than awk.
![image](https://user-images.githubusercontent.com/17017672/160264152-c1d28328-5f48-4955-82d2-17f05dcf29a8.png)

**Comment by ins0mniaque** [comment]
You are right, I messed up my first benchmark. But I don't get as good a performance increase as yours using awk. I guess the version of awk that comes with macOS is just terrible.

```zsh
~ ❯ time (sed 's/\x1b\[[0-9;]*m//g;s/\x00//g' completions | command awk 'length > max_length { max_length = length; } END { print max_length }')
23
( sed 's/\x1b\[[0-9;]*m//g;s/\x00//g' completions | command awk ; )
0.08s user 0.00s system 171% cpu 0.048 total
~ ❯ time (
    for line in ${(f)mapfile[completions]}; do
        length=${(m)#${(S)line//$'\x1b['[0-9]#*m}}
        (( length >= comp_length )) && comp_length=$length
        (( comp_lines++ ))
    done
    echo $comp_length
)
23
( for line in ${(f)mapfile[completions]}; do; length= ; (()) && comp_length= )
0.15s user 0.00s system 99% cpu 0.155 total
~ ❯ wc -l completions
   58110 completions
```

**Comment by Aloxaf** [comment]
Seems to be a bug of BSD sed: https://superuser.com/a/561105/921237

I will use perl instead.

**Comment by Aloxaf** [comment]
Please update and try again.

**Comment by ins0mniaque** [comment]
That was fast! Thanks! Everything works now. It's also a lot faster than using sed, at least on my machine:

```zsh
~ ❯ time (perl -pe 's/\x1b\[[0-9;]*m//g;s/\x00//g' completions | command awk 'length > max_length { max_length = length; } END { print max_length }')
23
( perl -pe 's/\x1b\[[0-9;]*m//g;s/\x00//g' completions | command awk ; )
0.03s user 0.00s system 146% cpu 0.024 total
~ ❯ wc -l completions                                                                                                                                                                               zsh
   58110 completions
```

**Comment by msankhala** [comment]
The below solution worked for me. This may help someone.
If you are facing this problem only with the `cd` command with preview then probably you are using `fzf-preview` instead of `fzf-tmux-popup`. 

You can set the popup-min-size for preview.

```bash
# apply to all command
zstyle ':fzf-tab:*' popup-min-size 80 12
# preview directory's content with eza when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1a --color=always $realpath'
```
