### ISSUE TITLE
[Q]zsh-completions已经卸载，但是补全还是默认这个，安装了fzf没有补全的效果。。。

### ISSUE THREAD

**Issue by adaaaaaa** [Aloxaf/fzf-tab#219]
zi clist                                                                                                                                                            ─╯
100.0% 
afew, android, archlinux-java        zsh-users/zsh-completions [stray, clean with cclear]
artisan, atach, bitcoin-cli          zsh-users/zsh-completions [stray, clean with cclear]
bower, bundle, caffeinate            zsh-users/zsh-completions [stray, clean with cclear]
cap, cask, ccache                    zsh-users/zsh-completions [stray, clean with cclear]
cf, cheat, choc                      zsh-users/zsh-completions [stray, clean with cclear]
chromium, cmake, coffee              zsh-users/zsh-completions [stray, clean with cclear]
composer, conan, concourse           zsh-users/zsh-completions [stray, clean with cclear]
console, cppcheck, dad               zsh-users/zsh-completions [stray, clean with cclear]
debuild, dget, dhcpcd                zsh-users/zsh-completions [stray, clean with cclear]
diana, docpad, drush                 zsh-users/zsh-completions [stray, clean with cclear]
ecdsautil, emulator, envdir          zsh-users/zsh-completions [stray, clean with cclear]
exportfs, fab, fail2ban-client       zsh-users/zsh-completions [stray, clean with cclear]
fast-theme                           zdharma/fast-syntax-highlighting
ffind, fleetctl, flutter             zsh-users/zsh-completions [stray, clean with cclear]
force, fwupdmgr, gas                 zsh-users/zsh-completions [stray, clean with cclear]
ghc, gist, git-flow                  zsh-users/zsh-completions [stray, clean with cclear]
git-journal, git-pulls, git-revise   zsh-users/zsh-completions [stray, clean with cclear]
git-wtf, glances, golang             zsh-users/zsh-completions [stray, clean with cclear]
google, gpgconf, gtk-launch          zsh-users/zsh-completions [stray, clean with cclear]
hledger, homestead, httpie           zsh-users/zsh-completions [stray, clean with cclear]
ibus, include-what-you-use, inxi     zsh-users/zsh-completions [stray, clean with cclear]
jmeter, jmeter-plugins, jonas        zsh-users/zsh-completions [stray, clean with cclear]
jrnl, kak, kitchen                   zsh-users/zsh-completions [stray, clean with cclear]
knife, language_codes, lilypond      zsh-users/zsh-completions [stray, clean with cclear]
lunchy, mc, middleman                zsh-users/zsh-completions [stray, clean with cclear]
mina, mix, mssh                      zsh-users/zsh-completions [stray, clean with cclear]
mussh, mvn, nano                     zsh-users/zsh-completions [stray, clean with cclear]
nanoc, nftables, node                zsh-users/zsh-completions [stray, clean with cclear]
nvm, openssl, optirun                zsh-users/zsh-completions [stray, clean with cclear]
opustools, patool, perf              zsh-users/zsh-completions [stray, clean with cclear]
periscope, pgsql_utils, phing        zsh-users/zsh-completions [stray, clean with cclear]
pixz, pkcon, play                    zsh-users/zsh-completions [stray, clean with cclear]
pm2, port, protoc                    zsh-users/zsh-completions [stray, clean with cclear]
pygmentize, qmk, rails               zsh-users/zsh-completions [stray, clean with cclear]
ralio, redis-cli, rfkill             zsh-users/zsh-completions [stray, clean with cclear]
rkt, rmlint, rmlint.sh               zsh-users/zsh-completions [stray, clean with cclear]
rslsync, rspec, rsvm                 zsh-users/zsh-completions [stray, clean with cclear]
rubocop, sbt, scala                  zsh-users/zsh-completions [stray, clean with cclear]
scrub, sdd, setcap                   zsh-users/zsh-completions [stray, clean with cclear]
setup.py, sfdx, shellcheck           zsh-users/zsh-completions [stray, clean with cclear]
showoff, srm, stack                  zsh-users/zsh-completions [stray, clean with cclear]
subl, subliminal, supervisorctl      zsh-users/zsh-completions [stray, clean with cclear]
svm, tarsnap, teamocil               zsh-users/zsh-completions [stray, clean with cclear]
thor, tmuxinator, tmuxp              zsh-users/zsh-completions [stray, clean with cclear]
tox, trash-empty, trash-list         zsh-users/zsh-completions [stray, clean with cclear]
trash-put, trash-restore, udisksctl  zsh-users/zsh-completions [stray, clean with cclear]
ufw, vagrant, virtualbox             zsh-users/zsh-completions [stray, clean with cclear]
vnstat, wemux, wg-quick              zsh-users/zsh-completions [stray, clean with cclear]
xinput, xsel, yaourt                 zsh-users/zsh-completions [stray, clean with cclear]
yarn, zcash-cli                      zsh-users/zsh-completions [stray, clean with cclear]
zinit                                _local/zinit

怎样才能让fzf正常工作？

**Comment by Aloxaf** [comment]
You doesn't need to uninstall zsh-users/zsh-completions.

Pelase provide your zshrc.

**Comment by adaaaaaa** [comment]
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit's installer chunk
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

plugins=(
	zsh-autosuggestions
	fast-syntax-highlighting
)
# 下面三行注释是我试过很多次都不行之后打上去的。。。
#zinit ice lucid wait='0' atinit='zpcompinit'
#source $HOME/.zinit/plugins/Aloxaf---fzf-tab/fzf-tab.plugin.zsh
#zinit light Aloxaf/fzf-tab

zinit load zdharma/history-search-multi-word
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOME/.zinit/plugins/zdharma---fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
#source $HOME/.zinit/plugins/zdharma---history-search-multi-word/history-search-multi-word.plugin.zsh

@Aloxaf 大佬，请查阅。。。

**Comment by Aloxaf** [comment]
please try this

```zsh
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit's installer chunk
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

zpcompinit; zpcdreplay

zinit light zdharma/history-search-multi-word
zinit light Aloxaf/fzf-tab
zinit light zdharma/fast-syntax-highlighting
zinit light zsh-users/zsh-autosuggestions

```

**Comment by adaaaaaa** [comment]
> zsh-users/zsh-completions

这个要重新安装上去是吗？😅

**Comment by Aloxaf** [comment]
> > zsh-users/zsh-completions
> 
> 这个要重新安装上去是吗？sweat_smile@Aloxaf

Yes
