### ISSUE TITLE
[BUG] `zstyle ':fzf-tab:complete:git-(add|diff|restore):*'` does not work for `git add <tab>`

### ISSUE THREAD

**Issue by fjchen7** [Aloxaf/fzf-tab#220]
I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### Describe the bug
I try the zstyle configuration in [documentation](https://github.com/Aloxaf/fzf-tab/wiki/Preview#git) for `git` completion, but fails.

To be specific, I make this in my configuration

```zsh
zstyle ':fzf-tab:complete:*' fzf-preview 'less $realpath'
zstyle ':fzf-tab:complete:git-(add|diff|restore):*' fzf-preview 'git diff $word'
```

The applied pattern for `git add <tab>` is `':fzf-tab:complete:*'` but not `':fzf-tab:complete:git-(add|diff|restore):*'`, which is not expected.

#### To Reproduce
As the above described.

#### Minimal zshrc
```zsh
zstyle ':fzf-tab:complete:*' fzf-preview 'less $realpath'
zstyle ':fzf-tab:complete:git-(add|diff|restore):*' fzf-preview 'git diff $word'
```

#### Expected behavior

Rather than `':fzf-tab:complete:*'`, `':fzf-tab:complete:git-(add|diff|restore):*'` should be applied for `git add <tab>` at first.

#### Screenshots
N/A

#### Environment:
 - OS: macOS
 - zsh version: 5.8

#### Log
N/A

**Comment by Aloxaf** [comment]
I cannot reproduce this.

What's the output of following code?

```
zstyle ':fzf-tab:complete:*' fzf-preview 'less $realpath'
zstyle ':fzf-tab:complete:git-(add|diff|restore):*' fzf-preview 'git diff $word'
zstyle -s ':fzf-tab:complete:git-add:*' fzf-preview str
echo $str
```

**Comment by fjchen7** [comment]
It outputs `git diff $word`. Now it works.

I think previously I failed for it possibly because of the order to set `zstyle` and `compinit`. I have some my own zsh completions from files or `_gnu_generic`, and it take me some time to work out about the order, thought in the end I still don't know why it could work. Maybe it would be better to give explanation about the this on the documentation. 

Anyway, thanks!
