### ISSUE TITLE
[Q] Disable fzf-tab for a specific command

### ISSUE THREAD

**Issue by Coqueiro** [Aloxaf/fzf-tab#221]
Hi! I really enjoy fzf-tab, but I grew used to how tab completion works for some commands, namely cd. I like the horizontal grid printing the ls. When I want completion, I usually go for my Alt+C. On the other hand, I love how fzf-tab helps me completing things like commands. Is there a way to disable fzf-tab for certain commands?

**Comment by simon-johansson** [comment]
Is there any way of achieving this right now?
