### ISSUE TITLE
[BUG] when user `zstyle ':completion:*' file-list all`, the $realpath cannot work.

### ISSUE THREAD

**Issue by Freed-Wu** [Aloxaf/fzf-tab#222]
#### Describe the bug
when user `zstyle ':completion:*' file-list all`, the $realpath cannot work.

file-list all will make zsh completion from 
![image](https://user-images.githubusercontent.com/32936898/128129005-337c583b-7fa9-4814-b5c3-a60983f85def.png)
to
![image](https://user-images.githubusercontent.com/32936898/128128965-d9573965-af44-45c6-938f-2a34226bbd00.png)

the $realpath cannot be analysized correctly.

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### Expected behavior

when file-list is all,
fzf-tab should split the $word with space, and use the last token to calculate the $realpath.

#### Environment:
 - OS: Arch Linux (however, i think other OS has same problem, too)
 - zsh version: 5.8

**Comment by Aloxaf** [comment]
Thanks for your report! Please update and check again.
