### ISSUE TITLE
[TYPO] issue template has meaningless repeation

### ISSUE THREAD

**Issue by Freed-Wu** [Aloxaf/fzf-tab#223]
See <https://github.com/Aloxaf/fzf-tab/blob/master/.github/ISSUE_TEMPLATE/bug_report.md>, `Describe the bug`, `Environment:`, etc has been repeated twice.

thanks!

**Comment by Aloxaf** [comment]
Thanks for your report!

**Comment by Freed-Wu** [comment]
you are welcome. thank you for your bringing the awesome plugin to us.

i have added some contents for <https://github.com/Aloxaf/fzf-tab/wiki/Preview#preview-gallery>, if you found any contents which i added are incorrect, you can change them.

Great!
