### ISSUE TITLE
[FR] Use more "default" fzf setup. Tab multi select + colours

### ISSUE THREAD

**Issue by ayroblu** [Aloxaf/fzf-tab#225]
**Is your feature request related to a problem? Please describe.**
Hey! I think this is super useful! I was struggling with a few of the changes, notably, the colours don't work well on light backgrounds and the fact that tab is move down and ctrl-space is select / toggle (as per #22)

**Describe the solution you'd like**
Provide an option or something to use a more "default" fzf setup that we can customize with variables etc

**Describe alternatives you've considered**
Colours has a really easy partial solution:
```zsh
zstyle ':fzf-tab:*' default-color $fg[default]
```
Though this doesn't work so well with groups

But I'm not sure how to change the tab to multi selection.

**Comment by ayroblu** [comment]
Oh I realised that this actually works:

```zsh
zstyle ':fzf-tab:complete:*' fzf-bindings 'tab:toggle+down'
```

I think I'm frustrated that this is not the default, but the configuration is not too bad once you know what to look for - closing

**Comment by infused-kim** [comment]
I had exactly the same problems as you as I am also using a light terminal.

Here is my config for anyone else who is struggling with this.

```zsh
# Fix colors for light terminal screens
zstyle ':fzf-tab:*' default-color $fg[default]
zstyle ':fzf-tab:*' fzf-flags --color=light,hl:2,hl+:2

# Enable multi select in tab completions using tab and shift tab
zstyle ':fzf-tab:complete:*' fzf-bindings 'tab:toggle+down,shift-tab:toggle+up'

# Allow switching of group using `,` and `.`
zstyle ':fzf-tab:*' switch-group ',' '.'

# Do continious completion for traversing paths with ` key
zstyle ':fzf-tab:*' continuous-trigger '`'
```
