### ISSUE TITLE
[Q] command options for zstyle fzf-tab context

### ISSUE THREAD

**Issue by Hill-98** [Aloxaf/fzf-tab#229]
I need `systemctl` have `--user` option before enabling fzf-preview

But I'm not sure how to write the context for zstyle.

Any help would be appreciated, thanks.

**Comment by Aloxaf** [comment]
Sorry for the late reply.

What does "before enabling fzf-preview" mean?

**Comment by Hill-98** [comment]
Oh, I didn't make that clear.
I wanted to use zstyle to check if systemctl has --user so that I can show only user services in the preview window.

**Comment by Aloxaf** [comment]
Ummm, can you give me an example?

**Comment by Hill-98** [comment]
![Peek 2021-12-07 23-21](https://user-images.githubusercontent.com/25147395/145056787-9ab3da3c-2e38-4268-953a-4aac86ddbee4.gif)
like this, this is another plugin

**Comment by Aloxaf** [comment]
Closed by https://github.com/Aloxaf/fzf-tab/pull/305
