### ISSUE TITLE
[Q]plugin not work

### ISSUE THREAD

**Issue by captswing** [Aloxaf/fzf-tab#230]
[help wanted]
I have installed plugin in Zinit, but received message when I use tab, the plugin not work.
The message disappear quickly.
![20210828234643](https://user-images.githubusercontent.com/16745461/131508893-0d721e64-4a8f-42d7-98c2-c7906317d41e.png)

[Hardware]
raspberry3b

[OS]
debian10

[Version]
zsh5.7.1
tmux2.8

**Comment by Aloxaf** [comment]
What's your fzf version?
I guess your fzf doesn't support `reload` action.

**Comment by captswing** [comment]
> What's your fzf version?
> I guess your fzf doesn't support `reload` action.

Thanks.
My fzf version is 0.17.5, installed from raspberry source, it's too old.
I installed latest version 0.27.2 of fzf, the plugin works.
