### ISSUE TITLE
[BUG] preview $realpath contains escape characters

### ISSUE THREAD

**Issue by BirkhoffLee** [Aloxaf/fzf-tab#231]
#### Describe the bug

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. Type `cd `
2. Press <kbd>Tab</kbd> and choose a directory with spaces or other special characters

#### Expected behavior
`$realpath` should not include escape characters (i.e. `\`)

#### Screenshots
<img width="1274" alt="CleanShot 2021-09-10 at 21 08 03@2x" src="https://user-images.githubusercontent.com/8148095/132857992-35c5136e-f4ea-4274-a7d5-614a2b0edac4.png">

#### Environment:
 - OS: macOS Catalina
 - zsh version: zsh 5.8 (x86_64-apple-darwin20.1.0)

#### Minimal zshrc
```shell
source ~/.zinit/bin/zinit.zsh

zinit wait"0" silent depth"1" light-mode for \
  multisrc:'shell/{completion,key-bindings}.zsh' \
    @junegunn/fzf \
  atinit"zicompinit; zicdreplay" \
    @Aloxaf/fzf-tab

zstyle ':fzf-tab:complete:*:*' fzf-flags --preview-window 'right:60%:nohidden:wrap'
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls $realpath'
```

#### Log
If applicable, use `C-x .` to trigger completion and provide the log.

If there are only three lines in your log, please make sure your fzf-tab is loaded with the correct order (see the checklist above).

**Comment by BirkhoffLee** [comment]
Current workaround: use `${realpath//\\ / }` instead of `$realpath`. I suspect that this is a particular issue in my environment, since I do not see any relevant issues on this. @Aloxaf could you provide a way so I could debug this? Also is `$realpath` supposed to contain the absolute path to the completion item? It only consists of the relative path on my machine.

**Comment by Aloxaf** [comment]
Fixed.
Thanks for your report!
