### ISSUE TITLE
[Q] Pressing enter runs completed command instead of just outputting

### ISSUE THREAD

**Issue by prurph** [Aloxaf/fzf-tab#232]
**Describe your question**
Submitting as a question because I don't think the issue is with fzf-tab itself, rather my configuration.

When I press enter, instead of the selection only appearing on the command-line, it runs the command. Example:

1. Type `git d` press tab
2. Select `diff` from fzf
3. Hit enter
4. Command `git diff` is run, instead of prompt displaying `git diff` and awaiting further input

This means I cannot fzf-tab complete multiple entries. I think this might be an issue with my terminal setup but I'm unsure how to troubleshoot. I tried disabling all other plugins, unsetting all FZF options, etc, and it still happens, so I must be overlooking something.

If I use fzf directly (eg with Ctrl-R binding to search history) it works as expected. Any thoughts on how to figure out what's going on here? Thanks!

**Comment by Aloxaf** [comment]
Can you trigger fzf-tab with `C-x .` can provide the log file?

**Comment by prurph** [comment]
Thanks for the reply!. Here is the log output: https://pastebin.com/jSX0EC3q. Since I couldn't see the UI using `C-x .` I just picked the first selection with `C-n` and hit enter.

**Comment by prurph** [comment]
I think I discovered the problem--if there are no more completion options left, hitting enter will run the command. This is the case if you're trying to autocomplete git commands from a non-git directory, or if you hit `ls <file>` instead of a directory, etc.. My first issue works properly if I'm actually in a repo, whoops.

I'll close this--sorry for the confusion.
