### ISSUE TITLE
Group descriptions need to be percent-expanded

### ISSUE THREAD

**Issue by romkatv** [Aloxaf/fzf-tab#24]
I had an old completion setting like this:

```zsh
zstyle ':completion:*' format ' %F{yellow}-- %d --%f'
```

With fzf-tab it ended up like this:

![image](https://user-images.githubusercontent.com/1282067/72476985-e27fec80-37ee-11ea-91df-341812e1f876.png)

Perhaps put `${(%)some_variable}` somewhere?

**Comment by Aloxaf** [comment]
This is a known issue but I am not sure how to deal with it.

If I expand it, it will overwrite the group color.
![图片](https://user-images.githubusercontent.com/17017672/72494883-3d9df780-3860-11ea-971b-fc3987289407.png)

I think keep them unexpanded will let users quickly realize that this is the problem of their own settings.

Of course it would be better if there is a better solution.

**Comment by romkatv** [comment]
Fine with me.

**Comment by kakulukia** [comment]
Hmm @romkatv how can you call that an old setting, when its the default installing a fresh copy of prezto? Happened to me yesterday. Took me a  while to figure out whats wrong.

**Comment by romkatv** [comment]
> Hmm @romkatv how can you call that an old setting

When someone says "there is an old proverb", it doesn't mean this proverb is no longer used. It means it was used for the first time a long time ago. Likewise with an old setting, which I had in my zsh configs for a long time.

**Comment by montchr** [comment]
> if anyone have this problem, add these lines to your zshrc
> 
> ```
> zstyle -d ':completion:*' format
> zstyle ':completion:*:descriptions' format '[%d]'
> ```

Using this suggested `[%d]` format did not work for me. However, I noticed that in other comments (e.g. <https://github.com/Aloxaf/fzf-tab/issues/98#issuecomment-643865065>), @Aloxaf suggests a format of `-- %d --`. That format did end up working for me, though I'm not sure why.

**Comment by laur89** [comment]
`zstyle ':completion:*:descriptions' format '[%d]'` fixes most cases, but not corrections. E.g.

    zstyle ':completion:*:*:*:*:corrections' format '%F{yellow}> %d:%f'

still produces `%F{yellow}> corrections:%f` in the prompt. Any suggestions?

**Comment by wookayin** [comment]
Personally, I am using **both** of `fzf-tab-complete` and `expand-or-complete` (the built-in) ZLE widgets for different keybindings. https://github.com/Aloxaf/fzf-tab/issues/24#issuecomment-574986122 works well, but it will show bare simple `[%d]` (with no color) for the `expand-or-complete` widget case.

To make **both** widgets happy, we can use a 'conditional' format whose value is evaluated on runtime when style is looked up:

```zsh
zstyle -d ':completion:*' format
zstyle -e ':completion:*:descriptions' format '
  if [[ "$WIDGET" == "fzf-tab-complete" ]]; then
    reply=("[%d]")
  else
    reply=("%F{yellow}-- %d --%f ")
  fi
'
```
