### ISSUE TITLE
[Q] fzf installation is required?

### ISSUE THREAD

**Issue by braco** [Aloxaf/fzf-tab#240]
I didn't think this package worked for me, it turns out I needed to [install fzf](https://github.com/junegunn/fzf#installation) first. This isn't stated in the docs, is this unusual?

Additionally, without fzf, there were no errors thrown, just empty output from fzf-tab.

**Comment by Aloxaf** [comment]
Oh yes, fzf is required.

**Comment by yavko** [comment]
Its called fzf-tab, meaning it uses fzf...
