### ISSUE TITLE
[BUG] Startup broken on MSYS2

### ISSUE THREAD

**Issue by FrostKiwi** [Aloxaf/fzf-tab#241]
#### Describe the bug
I use MSYS2 with the MinGW64 environment and the ZSH shell. Installting fzf-tab fails, because running `source ~/somewhere/fzf-tab.plugin.zsh` results in `fzf-tab.plugin.zsh:1: command not found: fzf-tab.zsh`
This does not only concern the automatic install method. Same with zinit, see screenshot:
![grafik](https://user-images.githubusercontent.com/60887273/143663038-32270712-b6a3-4db7-b291-658086eda7df.png)

I am not even sure how to debug this. Clearly fzf-tab.zsh is there...
I can make sure:
- [ x] I am using the latest version of fzf-tab
- [ x] this is the minimal zshrc which can reproduce this bug
- [ x] fzf-tab is loaded after `compinit`
- [ x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [ x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### Environment:
 - OS: Windows 10 - MINGW64_NT-10.0-19042
 - zsh version: zsh 5.8 (x86_64-pc-msys)

#### Minimal zshrc
_Literally empty_
Same after installing zinit

#### Log
Failed to load, so no fzf-tab logs

**Comment by Aloxaf** [comment]
How about `source ~/somewhere/fzf-tab.zsh`?

**Comment by FrostKiwi** [comment]
@Aloxaf 
Apparently nothing?
I double checked again, removed my zsh config, installed fzf from git again (since MSYS2 doesn't have it), fzf works but nothing happens after source  fzf-tab.zsh.
No error, no fzf-tab function after I press tab to autocomplete something.

**Comment by Aloxaf** [comment]
I need some trace log. Can you press <kbd>Ctrl+x .</kbd> and provide the output?

![图片](https://user-images.githubusercontent.com/17017672/143993930-78e978ad-81c7-4771-a3dc-306ad7f54305.png)

**Comment by FrostKiwi** [comment]
@Aloxaf 
When I press TAB, ZSH(?) complains with "unsupported key C:\msys64" for a split second. I had to screen record and playback in slowmotion to screenshot this.
![image](https://user-images.githubusercontent.com/60887273/144033397-ba3f47da-8699-418a-9012-12b7b4ea7372.png)
Ctrl + X does not do anything either and also shows no error. In the text editor nano it properly exits the program, so Ctrl + X seems to work. I double checked and alacritty does not have a Keybinding on Ctrl + X that might block it either. When text is in the shell, Ctrl + X seem to select it. I guess selecting text via Ctrl + X is ZSH behaviour? Either way, no logs like you showed in the screen shot are returned.

Extra frustrating is the fact, that I can't even get fzf to work properly half of the time. On one computer it works in alacritty but fails in the MSYS' provided mintty (Upon executing fzf it get's stuck in a manner similar to https://github.com/msys2/MINGW-packages/issues/10113#issuecomment-980633670 ). On another one it suddenly stopped working in Alacritty as well. That needs some extra investigation I guess, but is hopefully not relevant to this issue.

**Comment by Aloxaf** [comment]
> @Aloxaf When I press TAB, ZSH(?) complains with "unsupported key C:\msys64" for a split second. I had to screen record and playback in slowmotion to screenshot this. ![image](https://user-images.githubusercontent.com/60887273/144033397-ba3f47da-8699-418a-9012-12b7b4ea7372.png) Ctrl + X does not do anything either and also shows no error. In the text editor nano it properly exits the program, so Ctrl + X seems to work. I double checked and alacritty does not have a Keybinding on Ctrl + X that might block it either. When text is in the shell, Ctrl + X seem to select it. I guess selecting text via Ctrl + X is ZSH behaviour? Either way, no logs like you showed in the screen shot are returned.

it's `C-x .`
not `C-x`

> Extra frustrating is the fact, that I can't even get fzf to work properly half of the time. On one computer it works in alacritty but fails in the MSYS' provided mintty (Upon executing fzf it get's stuck in a manner similar to [msys2/MINGW-packages#10113 (comment)](https://github.com/msys2/MINGW-packages/issues/10113#issuecomment-980633670) ). On another one it suddenly stopped working in Alacritty as well. That needs some extra investigation I guess, but is hopefully not relevant to this issue.

which version of fzf are you using? msys fzf or windows native fzf?

**Comment by FrostKiwi** [comment]
> it's C-x . not C-x

Ohhhhh. Yeah that works. The log looks a bit bare though:
```
+fzf-tab-debug:9> : zsh 5.8
+fzf-tab-debug:10> zle .fzf-tab-orig-fzf-completion
unsupported key: C:/msys64/
+fzf-tab-debug:11> unsetopt xtrace
```
I am using **not** the windows native version. Since the there is no fzf in either the MSYS packages or the MinGW64 packages, I installed it via git manually as described in the docs here: https://github.com/junegunn/fzf#using-git
It installed itself successfully into ZSH without errors and works flawlessly on this PC with the alacritty terminal. I am using MSYS with it's MinGW64 environment in case that matters.

**Comment by Aloxaf** [comment]
try put these lines to your zshrc (assuming your are using zinit)

```
zpcompinit; zpcdreplay
zinit light Aloxaf/fzf-tab
```

**Comment by Aloxaf** [comment]
not sure why

![image](https://user-images.githubusercontent.com/17017672/144795663-e48a733e-1404-45e9-8a90-2a7f6630d954.png)

**Comment by Aloxaf** [comment]
reported to upstream: https://github.com/junegunn/fzf/issues/2680

**Comment by Aloxaf** [comment]
Please update and try again
