### ISSUE TITLE
[Q] Use ag or rg instead of deafualt 

### ISSUE THREAD

**Issue by yavko** [Aloxaf/fzf-tab#248]
**Describe your question**
How can I use ag or rg with this?

**Comment by Aloxaf** [comment]
emm, how do you use rg/ag with fzf-tab?

**Comment by yavko** [comment]
> emm, how do you use rg/ag with fzf-tab?

Idk in fzf I set it as a env called $FZF_DEFAULT_COMMAND

**Comment by yavko** [comment]
Was this fixed?

**Comment by Aloxaf** [comment]
fzf-tab is just a frontend of zsh compsys. Something like `FZF_DEFAULT_COMMAND` is beyond its limit.

**Comment by yavko** [comment]
👍
