### ISSUE TITLE
[BUG] ffmpeg -zsh: segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Freed-Wu** [Aloxaf/fzf-tab#249]
#### Describe the bug

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### Minimal zshrc

```zsh
# should install zsh-theme-powerlevel10k firstly
# In my PC, `sudo pacman -S zsh-theme-powerlevel10k`
. /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
autoload -Uz compinit && compinit
. /home/wzy/.zinit/plugins/fzf-tab/fzf-tab.plugin.zsh
```

#### To Reproduce

``` shell
# create a new zsh environment without sourcing any zshrc
zsh -f
# source minimal zshrc
. ~/Desktop/test.zsh
# press q because powerlevel10k will start an interface
# type `ffmpeg -`, then press `<tab>`
# you will see segmentation fault
# must use ffmpeg, other program will not result in this bug.
# must use powerlevel10k
# the path of `_ffmpeg` is `/usr/share/zsh/functions/Completion/Unix/_ffmpeg`
```

#### Screenshots

![Screenshot from 2021-12-09 15-43-20](https://user-images.githubusercontent.com/32936898/145355014-90f7fd22-8559-416c-8e18-de4e8aef2cfd.png)

#### Environment:
- OS: 5.15.4-arch1-1
- zsh version: 5.8.1

#### Log
![Screenshot from 2021-12-09 15-51-00](https://user-images.githubusercontent.com/32936898/145355663-fd310f0f-e710-48ae-a3af-4b236f6ba64f.png)

**Comment by Aloxaf** [comment]
see #176
