### ISSUE TITLE
[BUG] continuous completion aborts when only one option in next step

### ISSUE THREAD

**Issue by FalcoGer** [Aloxaf/fzf-tab#255]
#### Describe the bug
When using the continuous completion feature, it stops continuously completing when part of the path only has one option, but should continue if further options are available after that

I can make sure:
- [X] I am using the latest version of fzf-tab
- [X] this is the minimal zshrc which can reproduce this bug
- [ ] fzf-tab is loaded after `compinit` (How? I'm running oh-my-zsh)
- [X] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh) (Loaded last before autosuggestions and syntax highlighting)
- [X] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. Generate a directory structure like this:
```bash
mkdir test
cd test
mkdir -p a/a/a
mkdir -p a/a/b
mkdir b
```
2. enter `cd `
3. Press <kbd>Tab</kbd>
4. check that `a` is selected
5. press <kbd>/</kbd> to enable continuous completion
6. string gets completed to `a/a/` but continuous completion stops there, <kbd>Tab</kbd> needs to be pressed again to do further completing, defeating the point of this feature.

#### Expected behavior
continuous completion should realize that there are further options to be completed (to `a/a/a` and `a/a/b`)

#### Screenshots
N/A

#### Environment:
 - OS: `Linux ********* 5.4.0-92-generic #103-Ubuntu SMP Fri Nov 26 16:13:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - zsh version: `zsh 5.8 (x86_64-ubuntu-linux-gnu)`

#### Minimal zshrc
```bash
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"
HYPHEN_INSENSITIVE="true"
DISABLE_UPDATE_PROMPT="true"
export UPDATE_ZSH_DAYS=1
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd.mm.yyyy"
plugins=(
    fzf                     # fuzzy search in history (ctrl+r)
    fzf-tab                 # fzf support in tab complete
    zsh-autosuggestions     # provide automatic suggestions based on history and completion
    fast-syntax-highlighting
)

# fzf-tab
# https://github.com/Aloxaf/fzf-tab
zstyle ':completion:*:git-checkout:*' sort false
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':fzf-tab:complete:*' fzf-preview 'echo Realpath is: $realpath'

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#104010,underline"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_USE_ASYNC=true

source $ZSH/oh-my-zsh.sh
export EDITOR='vim'

# autocomplete stuff
# The following lines were added by compinstall
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _complete _ignored _correct _approximate
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' file-sort name
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd .. directory
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list '' '+m:{[:lower:]}={[:upper:]} m:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+r:|[._-]=** r:|=**' 'l:|=* r:|=*'
zstyle ':completion:*' menu select=4
zstyle ':completion:*' original false
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion:*' use-compctl true
zstyle ':completion:*' verbose true
zstyle :compinstall filename "$HOME/.zshrc"
autoload -Uz compinit
compinit
# End of lines added by compinstall

# Lines configured by zsh-newuser-install
HISTFILE="$ZSH_CACHE_DIR/.zsh_history"
HISTSIZE=4096
SAVEHIST=8192
setopt autocd nomatch notify beep
unsetopt extendedglob
bindkey -e # -e = emacs mode, -v = vim mode
# End of lines configured by zsh-newuser-install
```

#### Log
N/A

**Comment by Aloxaf** [comment]
Can you try #257 ?

**Comment by FalcoGer** [comment]
Seems to work.
