### ISSUE TITLE
Any way to debug the plugin?

### ISSUE THREAD

**Issue by farzadmf** [Aloxaf/fzf-tab#260]
**Describe your question**
Hi, I've been using your plugin for quite a while now and I love it and basically addicted to it.

I was using Linux before, and now I have to use a Mac. I don't have that many changes in my config files (given that Mac and Linux are similar), however, I'm facing an issue that when I enable this plugin, pressing <kbd>TAB</kbd> basically doesn't do anything.

I'm using `antigen`, and it seems like if I do `antigen reset` and restart a session, it works (not 100% sure though).

I was wondering if you can help me figure out what's missing on my Mac that may cause this issue

**Comment by farzadmf** [comment]
Thank you @Aloxaf for the answer. I **think** I managed to solve the issue by re-reading the `README`, where it mentioned it needs to be before other plugins.

As for the output of the commands, for `bindkey "^I"`, I have:
```
"^I" fzf-completion
```

And for `which ${$(bindkey "^I")[(w)2]}`:
```
fzf-completion () {
	local tokens cmd prefix trigger tail matches lbuf d_cmds
	setopt localoptions noshwordsplit noksh_arrays noposixbuiltins
	tokens=(${(z)LBUFFER}) 
	if [ ${#tokens} -lt 1 ]
	then
		zle ${fzf_default_completion:-expand-or-complete}
		return
	fi
	cmd=$(__fzf_extract_command "$LBUFFER") 
	trigger=${FZF_COMPLETION_TRIGGER-'**'} 
	[ -z "$trigger" -a ${LBUFFER[-1]} = ' ' ] && tokens+=("") 
	if [[ ${LBUFFER} = *"${tokens[-2]}${tokens[-1]}" ]]
	then
		tokens[-2]="${tokens[-2]}${tokens[-1]}" 
		tokens=(${tokens[0,-2]}) 
	fi
	lbuf=$LBUFFER 
	tail=${LBUFFER:$(( ${#LBUFFER} - ${#trigger} ))} 
	if [ "$cmd" = kill -a ${LBUFFER[-1]} = ' ' ]
	then
		tail=$trigger 
		tokens+=$trigger 
		lbuf="$lbuf$trigger" 
	fi
	if [ ${#tokens} -gt 1 -a "$tail" = "$trigger" ]
	then
		d_cmds=(${=FZF_COMPLETION_DIR_COMMANDS:-cd pushd rmdir}) 
		[ -z "$trigger" ] && prefix=${tokens[-1]}  || prefix=${tokens[-1]:0:-${#trigger}} 
		[ -n "${tokens[-1]}" ] && lbuf=${lbuf:0:-${#tokens[-1]}} 
		if eval "type _fzf_complete_${cmd} > /dev/null"
		then
			prefix="$prefix" eval _fzf_complete_${cmd} ${(q)lbuf}
			zle reset-prompt
		elif [ ${d_cmds[(i)$cmd]} -le ${#d_cmds} ]
		then
			_fzf_dir_completion "$prefix" "$lbuf"
		else
			_fzf_path_completion "$prefix" "$lbuf"
		fi
	else
		zle ${fzf_default_completion:-expand-or-complete}
	fi
}
```

Which I think it means that the plugin is loaded, right?

**Comment by Aloxaf** [comment]
It seems that you are using https://github.com/junegunn/fzf/blob/9cb7a364a31bdb882d873807774bdcf6fad0c9e4/shell/completion.zsh#L262, which overrides fzf-tab's key binding.

You should let fzf-tab load after it.

**Comment by farzadmf** [comment]
@Aloxaf  I think I found the underlying issue (I had all sorts of issues with my bindings)

I'm using [zsh-vi-mode](https://github.com/jeffreytse/zsh-vi-mode), and as mentioned [here](https://github.com/jeffreytse/zsh-vi-mode#execute-extra-commands), it disables other bindings when loading

So, I created the `zvm_after_init` function and moved all the bindings there, and **I think** everything is fine now
