### ISSUE TITLE
[BUG] binary crash zsh if configing with group-colors and completion descriptions

### ISSUE THREAD

**Issue by Vonfry** [Aloxaf/fzf-tab#261]
#### Describe the bug
When fzf-tab works with binary `fzftab.so`, it will crash zsh with error `segmentation fault` after setting group-colors and completion descriptions.

I can make sure:
- [X] I am using the latest version of fzf-tab
- [ ] this is the minimal zshrc which can reproduce this bug
- [X] fzf-tab is loaded after `compinit`
- [X] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [X] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
```
zstyle ':completion:*:descriptions' format '%d'
zstyle ':fzf-tab:*' group-colors ''
git <tab>
```

#### Environment:
 - OS: NixOS 21.11 & Kali 2021-04-12 (in vm for test)
 - zsh version:  5.8

#### Link
NixOS/nixpkgs#158120

**Comment by Aloxaf** [comment]
Confirmed

**Comment by Vonfry** [comment]
Sorry, could you test it again? The problem is still existing.
