### ISSUE TITLE
[BUG] directory starting with '3' is pre-selected

### ISSUE THREAD

**Issue by kbd** [Aloxaf/fzf-tab#264]
#### Describe the bug

When typing `cd [tab]`, if the directory contains a sub-directory starting with "3", but only if it's the first directory in alphabetical order(?), the fzf query is pre-filled with "3".

I can make sure:
- [X] I am using the latest version of fzf-tab
- [X] this is the minimal zshrc which can reproduce this bug
- [X] fzf-tab is loaded after `compinit`
- [X] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [X] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce

Here are screenshots showing the behavior:

![Screen Shot 2022-02-18 at 3 37 31 PM](https://user-images.githubusercontent.com/728060/154770611-6030db3c-fe35-49da-87d8-93476c01a0ad.png)

![Screen Shot 2022-02-18 at 3 38 06 PM](https://user-images.githubusercontent.com/728060/154770616-c1c64311-e80e-4dae-a9e6-4d55d1ee8250.png)

As you can see, it pre-enters "3" (I didn't type that). It doesn't happen with `4thparty` if I delete the `3rdparty` directory.

#### Minimal zshrc

The screenshots above were taken with the following .zshrc:

```
PS1='$ '
autoload -Uz compinit
zmodload zsh/complist
compinit
source "$HOME/.config/fzf/fzf.zsh"
source ~/setup/3rdparty/fzf-tab/fzf-tab.plugin.zsh
```

**Comment by Aloxaf** [comment]
Sorry for the late reply. But I cannot reproduce this.

What's your test environment?

**Comment by kbd** [comment]
Just tested it again with the above `.zshrc` and get the same behavior.

![Screen Shot 2022-03-26 at 10 20 52 PM](https://user-images.githubusercontent.com/728060/160266538-b1f05fb2-5f6d-4e1b-a502-f0d74428b71e.png)

Unfortunate that you can't reproduce :(

```
$ fzf --version
0.29.0 (brew)
$ kitty --version
kitty 0.24.4 created by Kovid Goyal
$ zsh --version
zsh 5.8.1 (x86_64-apple-darwin21.3.0)
```

Happens on both my work Mac on Big Sur and my home computer on Monterey.

**Comment by Aloxaf** [comment]
Can you trigger completion with `C-x .` and provide the log?

**Comment by kbd** [comment]
> Can you trigger completion with C-x . and provide the log?

Good I was hoping there was a way to get debug info :)

I've attached the log file.

[zsh-48984-fzf-tab-1.log](https://github.com/Aloxaf/fzf-tab/files/8357001/zsh-48984-fzf-tab-1.log)

**Comment by Aloxaf** [comment]
Can you provide the output of the following code?

```zsh
tmp=3rdparty 
key=4thparty
prefix=(${(s::)tmp})
[[ ${(j::)${${(s::)key[1,$#tmp]}:^prefix}} =~ '^(((.)\3)*)' ]]
echo $MATCH
```

(It is expected to be empty)

**Comment by kbd** [comment]
```
$ cd ~/temp/fzftabtest 
$ tmp=3rdparty
$ key=4thparty
$ prefix=(${(s::)tmp})
$ echo $prefix
3 r d p a r t y
$ [[ ${(j::)${${(s::)key[1,$#tmp]}:^prefix}} =~ '^(((.)\3)*)' ]]
$ echo $MATCH
43
$ 
```

**Comment by Aloxaf** [comment]
Seems that regex implementation on macOS doesn't support backreference well. How about following code?

```
setopt rematch_pcre
tmp=3rdparty 
key=4thparty
prefix=(${(s::)tmp})
[[ ${(j::)${${(s::)key[1,$#tmp]}:^prefix}} =~ '^(((.)\3)*)' ]]
echo $MATCH
```

**Comment by kbd** [comment]
`$MATCH` was indeed blank this time with `rematch_pcre` set.

**Comment by Aloxaf** [comment]
Fixed, please update and try again.

**Comment by kbd** [comment]
Works! Ty for fix, and ty for fzf-tab.

![Screen Shot 2022-03-27 at 11 58 55 PM](https://user-images.githubusercontent.com/728060/160335506-7b74c4ef-280c-4fe4-97af-5c8d987ccf55.png)
