### ISSUE TITLE
[BUG] fzf-tab not following "Highlighted Substring" color

### ISSUE THREAD

**Issue by LampPrinter** [Aloxaf/fzf-tab#265]
#### Describe the bug

fzf-tab is not following the "hl" Highlighted Substring color set for fzf.

I am no coder but I think here you have hardcoded the color
https://github.com/Aloxaf/fzf-tab/blob/master/lib/-ftb-fzf
$fzf_command \
  --color=hl:$(( header_lines == 0 ? 188 : 255 )) \

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
The pic highlights the issue

![Screenshot 2022-02-23 at 11 53 02 PM](https://user-images.githubusercontent.com/7559328/155420035-983b1534-a4aa-4104-acb6-3280f3c81c3a.png)

#### Expected behavior
zsh-interactive-cd displays the highlight color fine

![Screenshot 2022-02-23 at 11 52 26 PM](https://user-images.githubusercontent.com/7559328/155420062-6d97e2f1-d19f-4a2f-88a6-fbca0cfb7180.png)

#### Environment:
 - OS: MacOS
 - zsh version: 5.8.1

**Comment by Aloxaf** [comment]
I hard-code it because default color doesn't work well with fzf-tab's default theme.

You can change it's value by `zstyle ':fzf-tab:*' fzf-flags --color=hl:12`
