### ISSUE TITLE
[Q] How to adjust colors for a light theme?

### ISSUE THREAD

**Issue by pogopaule** [Aloxaf/fzf-tab#267]
I use a [light theme](https://github.com/EdenEast/nightfox.nvim#dayfox).

Sometimes the color of the words in the list have too little contrast and are hard to read:
![grafik](https://user-images.githubusercontent.com/576949/157434194-0e5a0569-6d85-4c6e-b949-ca0e9d3114a1.png)

How can if improve the contrast?

The contrast for completions on e.g. `ls<tab>` are great.
![grafik](https://user-images.githubusercontent.com/576949/157434469-c32163ee-4266-4df8-b078-c5ec9ee62a1d.png)

My config: https://github.com/pogopaule/dotfiles/blob/master/zshrc#L74-L84 

-------------
Edit: I solved the problem above (see my comment below)

One thing I can not solve are the match colors in the case seen on this screenshot. The `ls` in all matches does not contrast with the background. I cannot find any option to change this and from what I see in the code these colors seem to be hardcoded...

![image](https://user-images.githubusercontent.com/576949/157835855-88fa6141-ef69-4dec-84e6-fa24607fd701.png)

**Comment by pogopaule** [comment]
Ok, [RTFM](https://github.com/Aloxaf/fzf-tab/wiki/Configuration#default-color) helps 😊 

This sets the text color to black:
`zstyle ':fzf-tab:*' default-color $'\033[30m'`

**Comment by Aloxaf** [comment]
You can use `zstyle ':fzf-tab:*' fzf-flags --color=hl:12` to change color of matches.

**Comment by pogopaule** [comment]
This is my final config for a light theme in case somebody needs a copy paste solution

```
# see https://github.com/Aloxaf/fzf-tab/wiki/Configuration#default-color
zstyle ':fzf-tab:*' default-color $'\033[30m'
# see https://man.archlinux.org/man/fzf.1.en#color=
zstyle ':fzf-tab:*' fzf-flags --color=light
```
