### ISSUE TITLE
[Q] zstyle ':completion:*' file-sort modification   

### ISSUE THREAD

**Issue by ccb23** [Aloxaf/fzf-tab#272]
Earlier I was using classic zsh completion for all path arguments. There I had the option to sort the completion list by modification date. This is extremely useful for me: 

 `zstyle ':completion:*' file-sort modification`
 
 Is there any option to sort fzf list by modification date, rather then alphabet?

**Comment by Aloxaf** [comment]
```zsh
# disable default sort
zstyle ':completion:*' sort false
# enable file sort
zstyle ':completion:*' file-sort modification
```
