### ISSUE TITLE
fish shell version?

### ISSUE THREAD

**Issue by DevAtDawn** [Aloxaf/fzf-tab#274]
is there a fish shell version of fzf-tab in the works? Interested in creating a pull request for this as iv created some fish functions to achieve something similar
https://github.com/DevAtDawn/fish-fzf-tab

```
function clia
    read -l line; commandline -a $line
    # commandline -a 
end

bind -M insert \et 'fuzzy_complete'

function fuzzy_complete
    complete -C | sort -u | fzf --height 40% --multi --reverse -q (commandline -t) | cut --output-delimiter ' ' -f1 | sed 's/-//g' | clia
    commandline -f end-of-line 
end

```

**Comment by yannk** [comment]
@DevAtDawn I've pasted `fish-fzf-tab` into my fish config, but it doesn't seem to replace the builtin completion from fish. Am I missing something?

**Comment by DevAtDawn** [comment]
@yannk 

right now its bound to ALT+t  (bind -M insert \et 'fuzzy_complete') instead of replacing tab/builtin. You can change \et to whatever you want.

![image](https://user-images.githubusercontent.com/86164137/163069616-49e0637c-c8c5-4559-9d77-d9bb6f0e4831.png)

**Comment by yannk** [comment]
Ah thanks, I got it, and replaced the binding with `\t` to see it in effect.

Note that I had to use 
```
cut -d ' '
```

instead of the long option (gnu version of cut?)

**Comment by yannk** [comment]
@DevAtDawn I had some more issues (token not properly replaced etc...), so I am now using https://github.com/junegunn/fzf/wiki/Examples-(fish)#completion

invoked from ```
bind -M insert \t 'fzf-complete'```

I'll report back if it doesn't work :)
