### ISSUE TITLE
[BUG] Would be nice if tab still autocompleted when only one (filtered) result

### ISSUE THREAD

**Issue by andrewferrier** [Aloxaf/fzf-tab#276]
**Is your feature request related to a problem? Please describe.**
I really like using fzf-tab. However, coming from conventional complete, I find it frustrating that when fzf only has one result listed in the fzf window (typically because I've typed one or two characters which have narrowed down the results list) that <Tab> does not then accept that result.

I've tried configured <Tab> as 'accept' for fzf:

`zstyle ':fzf-tab:*' fzf-bindings 'tab:accept'`

However, this is overly aggressive; when more than one result is listed, <Tab> just selects the currently highlighted one.

**Describe the solution you'd like**
When I hit <Tab>:

* If there is only one result listed (perhaps as a result of filtering), it's auto-accepted.
* When more than one result is listed, <Tab> acts like 'next' and goes down the list of fzf options.

**Describe alternatives you've considered**
I'm not sure if this is an `fzf-tab` bug, it may be in `fzf` - I cannot find an fzf action to bind to my desired behaviour.

**Comment by Aloxaf** [comment]
Seems that this is impossible: https://github.com/junegunn/fzf/issues/459

**Comment by andrewferrier** [comment]
Yeah, OK, I see that. It's a shame (unfortunately I think this makes fzf-tab too tricky to get used to for me), but understand. Thanks for your hard work on this project.
