### ISSUE TITLE
[BUG] zstyle ':fzf-tab:*' accept-line alt+enter doesn't work, and make fzf-tab not work

### ISSUE THREAD

**Issue by zyf0330** [Aloxaf/fzf-tab#277]
#### Describe the bug

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. change accept-line use `zstyle ':fzf-tab:*' accept-line alt+enter`
2. Press <kbd>Tab</kbd>
4. completion candidate list doesn't appear

#### Expected behavior
fzf-tab works normally, and alt+enter works as expected.

#### Environment:
 - OS: Ubuntu 21.10
 - zsh version: 5.8

#### Minimal zshrc
If applicable, add a minimal zshrc to help us analyze.

#### Log
If applicable, use `C-x .` to trigger completion and provide the log.

[zsh-3236201-fzf-tab-2.log](https://github.com/Aloxaf/fzf-tab/files/8581537/zsh-3236201-fzf-tab-2.log)

If there are only three lines in your log, please make sure your fzf-tab is loaded with the correct order (see the checklist above).

**Comment by Aloxaf** [comment]
First, you should use `alt-enter` instead of `alt+enter`. Second, `alt-enter` has been used by `print-query`, you should change one of them to avoid conflict.

Example:

```zsh
zstyle ':fzf-tab:*' accept-line alt-enter
zstyle ':fzf-tab:*' print-query ctrl-space
```

**Comment by zyf0330** [comment]
@Aloxaf Thanks. Actually, I have tried to map print-query to other key, like `ctrl-enter`, but it doesn't work. And I also tried to use `zstyle -d ':fzf-tab:*' print-query` to delete print-query mapping, but it doesn't work too.
So I have to map `print-query` to `ctrl-space`, right?

**Comment by Aloxaf** [comment]
`ctrl-enter` isn't a valid key for fzf. 
You can find the full list at https://man.archlinux.org/man/fzf.1#AVAILABLE_KEYS:_(SYNONYMS)

**Comment by zyf0330** [comment]
Thanks.
