### ISSUE TITLE
[BUG] Colors binary module causes issue in `-ftb-generate-complist`

### ISSUE THREAD

**Issue by igorepst** [Aloxaf/fzf-tab#280]
#### Describe the bug
If and only if the binary module is built and `fzftab.so` is present, I am getting `-ftb-generate-complist:fzf-tab-candidates-generate:21: bad pattern: *#=00;90`

I can make sure:
- [X] I am using the latest version of fzf-tab
- [ ] this is the minimal zshrc which can reproduce this bug
- [X] fzf-tab is loaded after `compinit`
- [X] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [X] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. Build the binary module
2. Add to `.zshrc` either `eval $(dircolors -b)`
or
```
LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.swp=00;90:*.tmp=00;90:*.dpkg-dist=00;90:*.dpkg-old=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:';
export LS_COLORS

```
where the above value of `LS_COLORS` is the direct output of `dircolors -b` on my system
3. Try to complete, for ex., `cd ~/.co<Tab>`
Instead of expected completion behavior I am getting `-ftb-generate-complist:fzf-tab-candidates-generate:21: bad pattern: *#=00;90`, where as you may see, the `LS_COLORS` indeed holds this bad pattern. If the binary module is renamed, there is a fallback to use the shell script and the output is good.
#### Screenshots
![image](https://user-images.githubusercontent.com/1630792/167454968-cbca9c61-bedd-4953-971a-dac2f6132867.png)

#### Environment:
 - OS: Arch Linux
 - zsh 5.8.1 (x86_64-pc-linux-gnu)

#### Log
[zsh-2153-fzf-tab-1.log](https://github.com/Aloxaf/fzf-tab/files/8653559/zsh-2153-fzf-tab-1.log)

Thanks!!!

**Comment by BayLee4** [comment]
I had the same issue, escaping `*#=00;90` to `*\#=00;90` will make it work again. This is not a bug in `fzf-tab` as `*#` really isn't a valid pattern in zsh : `setopt extendedglob && ls *#` outputs `zsh: bad pattern: *#`.

As the man page of `dircolors` states that the `-b` option `output Bourne shell code to set LS_COLORS`, it makes sense that it's not compatible with zsh for all scenarios.

**Comment by igorepst** [comment]
Oh, thanks! Makes sense. Closing...

**Comment by keyb0ardninja** [comment]
@BayLee4 @igorepst 
I'm facing the same problem and I'm using [sorin-ionescu/prezto](https://github.com/sorin-ionescu/prezto)

I have not modified the `LS_COLORS` variable in any way, other than any modification that might be done by prezto. How do I fix this problem?

**Comment by igorepst** [comment]
@keyb0ardninja Instead of using `eval $(dircolors -b)` in `.zshrc`, use `dircolors -b` once, copy the output, change `*#=00;90` to `*\#=00;90` and put `LS_COLORS=... export LS_COLORS` in your `.zshrc`

**Comment by keyb0ardninja** [comment]
@igorepst thanks, it works now!

I wonder, why do we manually need to edit the output of `dircolors`? Is that a bug upstream that should be reported?

**Comment by igorepst** [comment]
It isn't a bug. It is just that we see the **output** of `dircolors`, and there the quoting is absent

**Comment by keyb0ardninja** [comment]
Cool, but in that case, does the editing of the `LS_COLORS` variable in `~/.zshrc` be part of the standard installation process of `fzf-tab`? In that case, we should consider mentioning this in the `README` of this project.

Also, I started encountering this problem only from a couple of months ago. I wonder how did it work without this problem before?
