### ISSUE TITLE
[bug] fzf-tab always change {2} to {word}

### ISSUE THREAD

**Issue by Freed-Wu** [Aloxaf/fzf-tab#282]
In shell:

```
zstyle ':fzf-tab:complete:*' fzf-preview 'echo realpath:$realpath word:$word 1:{1} 2:{2} 3:{3}'
export FZF_DEFAULT_OPTS=
cd /dev/shm
touch a{1..20}
```

Then `less /dev/shm/a<Tab>` the fzf preview window will display `realpath:/dev/shm/a1 word:a1 1: 2:a1 3:`. The `{2}` always change to `$word`.

Thanks.

**Comment by Aloxaf** [comment]
What output do you expect?
`{..}` is a builtin syntax of fzf: https://man.archlinux.org/man/fzf.1#FIELD_INDEX_EXPRESSION.

**Comment by Freed-Wu** [comment]
I think the behavior that `{2}` be changed to `$word` is weird. So I guess it is a bug? My expected behavior is `{2}` will not change.

And if `zstyle ':fzf-tab:complete:*' fzf-preview 'echo realpath:$realpath word:$word {..}'`, the preview-window will display `fork/exec /usr/bin/zsh: invalid argument`. Is it a bug?

Thanks.

**Comment by Aloxaf** [comment]
`{..}` is [FIELD INDEX EXPRESSION](https://man.archlinux.org/man/fzf.1#FIELD_INDEX_EXPRESSION) of fzf. You should use `\{..\}`.
