### ISSUE TITLE
[Q] Why alias for run-help

### ISSUE THREAD

**Issue by ntupe** [Aloxaf/fzf-tab#284]
`run-help` is very useful command for getting help not only for man-pages but also for builtin commands (from `/usr/share/zsh/VERSION/help`). I was very surpised when I could not get this help on my usual `Alt-H` key. After some digging I found that it was aliassed for `man` in you plugin. I don't understand why. Autoloaded function `run-help` calls `man`, it it could not find help in the zsh directory.

**Comment by Aloxaf** [comment]
According to [zsh's manual](https://man.archlinux.org/man/zshall.1#run), `run-help` is normally aliased to man.

What you want is:
https://github.com/zsh-users/zsh/blob/cb59dfb3a6f6cce414c5b852c138d5f6bea6d563/Functions/Misc/run-help#L5-L8
```
unalias run-help
autoload -Uz run-help
```
