### ISSUE TITLE
fzf-tab doesn't fully follow fzf colour scheme.

### ISSUE THREAD

**Issue by sabah1994** [Aloxaf/fzf-tab#287]
Hi, 
First of all a great tool and I am loving it. 

I am using Grubox Dark scheme from https://github.com/junegunn/fzf/wiki/Color-schemes.

I want my fzf-tab to follow the same colour scheme when there is no group defined. Background colour and matched text colour (only in selected line) work other than it's bland. 

fzf on left and fzf-tab on right.
![fzf-tab](https://user-images.githubusercontent.com/73726199/174494644-b57b6189-1e4b-47fd-9152-79dd57136ef7.png)

ls; notice "a" is not highlighted in yellow except the selected line.
![ls](https://user-images.githubusercontent.com/73726199/174495024-7ec737b0-ef4c-4afb-a6c7-a927d04af5ba.png)

My zshrc
# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
#Gruvbox dark colours
export FZF_DEFAULT_OPTS='--height 70% --layout=reverse --border
  --color fg:#ebdbb2,bg:#282828,hl:#fabd2f,fg+:#ebdbb2,bg+:#3c3836,hl+:#fabd2f
  --color info:#83a598,prompt:#bdae93,spinner:#fabd2f,pointer:#83a598,marker:#fe8019,header:#665c54
'
# style for fzf-tab ls
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# Replace zsh tab completion with fzf
# TODO align fzf and fzf-tab colours
source ~/.fzf-tab/fzf-tab.plugin.zsh

Your help would be greatly appreciated.
Thanks.

**Comment by Aloxaf** [comment]
You should use `fzf-flags`. Command line flags has higher priority than environment variable.

```
zstyle ":fzf-tab:*" fzf-flags --height=70% --layout=reverse --border \
--color "fg:#ebdbb2,bg:#282828,hl:#fabd2f,fg+:#ebdbb2,bg+:#3c3836,hl+:#fabd2f" \
--color "info:#83a598,prompt:#bdae93,spinner:#fabd2f,pointer:#83a598,marker:#fe8019,header:#665c54"
```

**Comment by sabah1994** [comment]
@Aloxaf Thnak you
