### ISSUE TITLE
[BUG] Unable to bind key to execute script with fzf-tab while working with fzf

### ISSUE THREAD

**Issue by quanturium** [Aloxaf/fzf-tab#289]
#### Describe the bug
Binding a key to execute a script on selected file and passing that file doesn't work with fzf-tab while it works with fzf. 

I can make sure:
- [X] I am using the latest version of fzf-tab
- [X] this is the minimal zshrc which can reproduce this bug
- [X] fzf-tab is loaded after `compinit`
- [X] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce

```
export FZF_DEFAULT_OPTS="--bind 'ctrl-o:execute:(~/test.sh {})'"
fd | fzf
ctrl + o on a file # test.sh is correctly executed and contains the file path as arg
cat <tab>
ctrl + o on a file # test.sh is NOT executed
```

#### Expected behavior
The expected behavior is that test.sh should be executed with {}. If {} is removed, test.sh is currently executed in both cases. But without {} I'm not able to perform any action on the file

#### Environment:
 - OS: OSX
 - zsh version: 5.8.1

**Comment by Aloxaf** [comment]
You should use zstyle to set it. 
`zstyle ':fzf-tab:*' fzf-flags --bind 'ctrl-o:execute:(~/test.sh {})'`
