### ISSUE TITLE
Show identical keys nearby

### ISSUE THREAD

**Issue by webmastak** [Aloxaf/fzf-tab#29]
Output of paired parameters nearby as in the **fzf-tab-completion** plugin.

~~I have a plugin **git-flow-completion** how to make **fzf-tab** turn off when I use **git**?~~
The second question partially resolved **->** added a function in the plugin and hung in `.zshrc` 
`bindkey '^ T' fzf-tab-toggle` and sent a [pull request](https://github.com/Aloxaf/fzf-tab/pull/30).
Of course, I would like it to be done automatically.

I have **fzf-tab-completion** plugin does not work on the **TAB** key.
But `bindkey '^I' fzf_completion` is not convenient. 
Therefore, I prefer the **fzf-tab** plugin.

This is displayed in **fzf-tab** which is not very convenient:
here the keys are scattered
![https://i.imgur.com/smXYgho.gif](https://i.imgur.com/smXYgho.gif)

This is displayed in **fzf-tab-completion** which is very convenient:
in the example, the keys **-A --all --no-ignore-removal** are located together
![https://i.imgur.com/zePeHQE.gif](https://i.imgur.com/zePeHQE.gif)

**Comment by webmastak** [comment]
I made an exact search for fzf as a temporary solution in the absence of the functionality that I talked about in this issue.

**Comment by webmastak** [comment]
Tell me where in the code the command line arguments are fetched?

**Comment by Aloxaf** [comment]
Sorry for the late reply. 
In fact, fzf-tab used to behave as you expect. But I found it is inconsistent with the default behavior of zsh's interactive search.
![图片](https://user-images.githubusercontent.com/17017672/74619136-7dae0e00-516f-11ea-9f21-7f70d18fe538.png)

To be consistent with zsh, and to improve performance, I changed the list order.

Since this behavior is the same as zsh, I will still keep this as the default. But I'd like to add an extra variable like `FZF_TAB_NO_SORT` for the behavior you expect. What do you think?

**Comment by webmastak** [comment]
Yes, that would be great.

**Comment by Aloxaf** [comment]
For everything. 
It will mess some results like completion of variable name.
![image](https://user-images.githubusercontent.com/17017672/74708193-cc82a300-5256-11ea-9dcf-e12b1f28a50f.png)

Ummm, need a better way to solve this.

**Comment by webmastak** [comment]
This can only be done for arguments? Or be able toggle.

**Comment by Aloxaf** [comment]
It's still under development. I need a better way to meet the needs of different people.
I'm considering switching fzf-tab's configuration from variables to zstyle so that it can be more flexible.
eg. 
```zsh
zstyle ':completion:fzf-tab:-parameter-' sort true
zstyle ':completion:fzf-tab:*:' sort false
```

**Comment by webmastak** [comment]
While it is not clear with **fzf-tab**, I adapted two plugins.

```
## fzf-tab
bindkey '^[[Z' fzf-tab-complete ## Shift+Tab

## fzf-tab-completion
bindkey '^I' fzf_completion ## Tab
```

**Comment by webmastak** [comment]
How are you doing with the development?

**Comment by Aloxaf** [comment]
Please check #46 
You can now set `zstyle ':fzf_tab:*:options' sort false` to just disable sorting when completing options.

**Comment by webmastak** [comment]
I do not understand how to apply it `zstyle ':fzf_tab:*:options' sort false`
It would be better to do a sort switch, for example:
```
disable-sort-fzf-tab() {
    typeset -g _ZSH_FZF_TAB_SORT
    emulate -L zsh
	zstyle ':fzf_tab:*' sort false 
}

enable-sort-fzf-tab() {
    unset _ZSH_FZF_TAB_SORT
    emulate -L zsh
    zstyle ':fzf_tab:*' sort true
}

sort-fzf-tab() {
    if [[ -n "${_ZSH_FZF_TAB_SORT+x}" ]]; then
        enable-sort-fzf-tab
    else
        disable-sort-fzf-tab
    fi
}
zle -N sort-fzf-tab
```
But it does not work.

Even if I just put `zstyle ': fzf_tab: *' sort false` this does not work, the arguments are not selected!

**Comment by webmastak** [comment]
[Here](https://github.com/Aloxaf/fzf-tab/pull/46/commits/1abd98b7ee4d92e72c2b950bf608d605d13ab9d5) the bug is fixed, everything works.
