### ISSUE TITLE
[Q] Width of line sidebar

### ISSUE THREAD

**Issue by KaspianDev** [Aloxaf/fzf-tab#291]
Hey, is it possible to remove spaces before and after line number?
![image](https://user-images.githubusercontent.com/34658474/178143535-86eb1e9d-85cb-4deb-849f-c579e4b2af7a.png)
It seems to waste a lot of space.

Maybe it's also possible to change width/height of the autocomplete box?

**Comment by Aloxaf** [comment]
The content style is controlled by https://github.com/sharkdp/bat. fzf-tab can do nothing with it.
