### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alex-popov-tech** [Aloxaf/fzf-tab#294]
#### Describe the bug

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [?] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. Type 'cat '
2. Press <kbd>Tab</kbd>

#### Expected behavior
it should help me select file

#### Screenshots
<img width="812" alt="CleanShot 2022-07-28 at 12 58 19@2x" src="https://user-images.githubusercontent.com/21224705/181478917-9a297ef2-4cfd-47d8-9433-15064a25b37c.png">
#### Environment:
 - OS: [macos]
 - zsh version: [5.8.1]

#### Minimal zshrc
thats my zshrc https://github.com/alex-popov-tech/.dotfiles/blob/master/zsh/.zsh/plugins#L5
and i injust plugin just before everything else like
```
zinit light Aloxaf/fzf-tab
zinit for \
  light-mode zdharma-continuum/fast-syntax-highlighting \
  light-mode OMZ::plugins/git/git.plugin.zsh \
  light-mode MichaelAquilina/zsh-you-should-use \
  light-mode OMZ::plugins/vi-mode/vi-mode.plugin.zsh
```

#### Log
[If applicable, use `C-x .` to trigger completion and provide the log.
](https://gist.github.com/d5757fb3f6d56ddfdb8cb29c7922bb73
)
If there are only three lines in your log, please make sure your fzf-tab is loaded with the correct order (see the checklist above).

**Comment by Aloxaf** [comment]
You forget to call `autoload -Uz compinit; compinit`, or `zpcompinit; zpcdreplay` as you're using zinit.
