### ISSUE TITLE
How can make '$realpath' work noramlly in windows?

### ISSUE THREAD

**Issue by Freed-Wu** [Aloxaf/fzf-tab#295]
![Screenshot from 2022-08-01 00-09-18](https://user-images.githubusercontent.com/32936898/182035366-30657fe3-5a6e-464d-b0c3-81919c9d1906.png)

```bash
# install fzf by msys2
pacman -S mingw-w64-fzf
```

**Comment by Aloxaf** [comment]
Try https://github.com/Aloxaf/fzf-tab/pull/296

**Comment by Freed-Wu** [comment]
I can confirm it fixes the bug.

![Screenshot from 2022-08-04 17-51-51](https://user-images.githubusercontent.com/32936898/182819517-6f49019b-b344-4b67-a1c0-5b5796972122.png)
