### ISSUE TITLE
[BUG] {_FTB_INIT_} fails (since pull request #296)

### ISSUE THREAD

**Issue by zebolino** [Aloxaf/fzf-tab#306]
#### Describe the bug
Since pull request #296 this fzf binding does not work anymore:
```
# Add shortcut Ctrl-y
zstyle ':fzf-tab:*' fzf-bindings 'ctrl-y:execute-silent({_FTB_INIT_} yankfilter ${realpath} | xsel --input --clipboard)+preview({_FTB_INIT_} echo "Copied content of \"${realpath}\" to clipboard")'
```
_yankfilter_ is a modified version of [.lessfilter](../wiki/Preview#show-file-contents) which pipes the content of the files to stdout without using bat etc.

The error which is shown in the preview window:
```
/tmp/zsh-fzf-tab-user/ftb_preview_init.173195:7: no such file or directory: $1                           │
/tmp/zsh-fzf-tab-user/ftb_preview_init.173195:9: bad set of key/value pairs for associative array                    │
Copied content of "" to clipboard
```

After reverting the changes introduced in #296 (removing the apostrophes) the binding works again.

I can make sure:
- [x] I am using the latest version of fzf-tab
- [ ] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. Type 'll '
2. Press <kbd>Tab</kbd>
3. Select a file to copy content to clipboard
4. Press <kbd>Ctrl</kbd>+<kbd>y</kbd>
5. View error

#### Expected behavior
_${realpath}_ contains the path to the file, so you can use it in the execute-silent() command

#### Environment:
 - OS: Manjaro Linux
 - zsh version: 5.9

#### Minimal zshrc
Relevant lines in .zshrc
```
## fzf-tab
# Defaults for FZF: height and width of preview window
zstyle ':fzf-tab:*' fzf-flags --height 90% --preview-window 60%
# Alt-Space to toggle all, ? to toggle Preview
zstyle ':fzf-tab:*' fzf-bindings 'ctrl-y:execute-silent({_FTB_INIT_} yankfilter ${realpath} | xsel --input --clipboard --display :0)+preview({_FTB_INIT_} echo "Copied content of \"${realpath}\" to clipboard")'
# show file contents in preview
zstyle ':fzf-tab:complete:(exa|vi|vim|cat|git):*' fzf-preview 'less ${realpath}'

plugins=(
  fzf-tab
)
source $ZSH/oh-my-zsh.sh
alias ll="exa --long --group --classify"
```

**Comment by Aloxaf** [comment]
Thanks for your report!
