### ISSUE TITLE
[BUG] Tab's auto complete pops up in anther terminal (with video)

### ISSUE THREAD

**Issue by mong0520** [Aloxaf/fzf-tab#307]
#### Describe the bug

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. Open a terminal and enter tmux
2. open current director with vscode by `code .`
3. in vscode's terminal, type anything and press tab to start fzf-tab, but the fzf-tab pops up in the original terminal.

https://user-images.githubusercontent.com/10734784/184548339-66810c5c-049c-4a17-91cd-5d11c4db55be.mov
#### Environment:
 - OS: MacOS 12.5
 - zsh version: zsh 5.8.1 (x86_64-apple-darwin21.0)

#### Minimal zshrc
If applicable, add a minimal zshrc to help us analyze.
```
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit
...
plugins=(git zsh-autosuggestions git-open fzf-tab jira z zsh-completions)
...
source ~/.oh-my-zsh/plugins/fzf-docker/docker-fzf
source $ZSH/oh-my-zsh.sh
```

#### Log
If applicable, use `C-x .` to trigger completion and provide the log.

If there are only three lines in your log, please make sure your fzf-tab is loaded with the correct order (see the checklist above).

**Comment by Aloxaf** [comment]
This is a known issue (or a feature?). You should unset `TMUX_PANE` so that fzf-tab won't think it is in a tmux pane.

**Comment by mong0520** [comment]
> This is a known issue (or a feature?). You should unset `TMUX_PANE` so that fzf-tab won't think it is in a tmux pane.

It worked after unset `TMUX_PANE` in the startup script of vscode. Thank you.
