### ISSUE TITLE
Ctrl J-K movement

### ISSUE THREAD

**Issue by danihodovic** [Aloxaf/fzf-tab#31]
By default FZF allows you to move around the selection menu with C-J and C-K, fzf-tab does not. Is it possible to enable this?

**Comment by webmastak** [comment]
You can add in the **fzf-tab.zsh** file on **line 101** to the `--bind=` key what you need.

**Comment by Aloxaf** [comment]
You can use `FZF_TAB_OPTS` to control the arguments of fzf.
```
FZF_TAB_OPTS=(
    --ansi  
    --expect='/'
    '--color=hl:$(( $#headers == 0 ? 108 : 255 ))'
    --nth=2,3 --delimiter='\0' 
    --layout=reverse --height=90%
    --tiebreak=begin -m --bind=tab:down,change:top,ctrl-space:toggle --cycle
    '--query=$query' 
    '--header-lines=$#headers' 
)
```

**Comment by danihodovic** [comment]
Thank you!
