### ISSUE TITLE
egrep: warning: egrep is obsolescent; using grep -E

### ISSUE THREAD

**Issue by sseneca** [Aloxaf/fzf-tab#314]
I am seeing this message whenever I open a new terminal

> egrep: warning: egrep is obsolescent; using grep -E

Maybe it's time to replace the occurrences of `egrep` in the codebase with `grep -E` instead?

**Comment by Aloxaf** [comment]
No, fzf-tab doesn't call egrep.

**Comment by sseneca** [comment]
Running `rg egrep` shows a bunch of results but they're all in test files etc. Anyway, since restarting my PC I no longer see that message, so must have been something on my end, apologies
