### ISSUE TITLE
(fzf-flags --color) fg and fg+ don't work[Q]

### ISSUE THREAD

**Issue by Nik-i-Net** [Aloxaf/fzf-tab#315]
(fzf-flags --color) fg and fg+ don't work, other colors (bg, hl, ...) work correctly.
Is it possible to make the priority of flags higher than list-colors?
# .zshrc
![zshrc](https://user-images.githubusercontent.com/91474300/191713704-51ee1992-6201-4b27-baf3-0a93bce11050.png)
# fzf
![fzf](https://user-images.githubusercontent.com/91474300/191713991-d294aebd-e6cd-45bc-9ce8-5426e9fa988c.png)
# fzf-tab
![fzf-tab](https://user-images.githubusercontent.com/91474300/191714177-5cc317d1-7033-4c01-99e2-a906ed3a6d2c.png)
# fzf-tab with disabled list-colors
![fzf-tab-list-colors](https://user-images.githubusercontent.com/91474300/191714378-7acc4568-da90-4651-8406-e6173eec0167.png)

**Comment by Aloxaf** [comment]
![图片](https://user-images.githubusercontent.com/17017672/195492649-49d62cce-593b-471f-992c-a4c93d661321.png)
Cannot reproduce.
