### ISSUE TITLE
[Q] How can I adjust the box size showing the completion results

### ISSUE THREAD

**Issue by cig0** [Aloxaf/fzf-tab#317]
**Describe your question**
Hi :wave: 
For some reason the box that pops up with the completion results doesn't list all the subdirectories available in the parent directory, as shown in this screenshot:
![image](https://user-images.githubusercontent.com/394089/194128237-281263b6-8db7-44c9-9e90-81bde83cf849.png)
Is there a way to enlarge the completion box to some arbitrary value, like it is possible to do with `fzf` with `FZF_DEFAULT_OPTS='--height`?

**Comment by Aloxaf** [comment]
See https://github.com/Aloxaf/fzf-tab/wiki/Configuration#fzf-pad
