### ISSUE TITLE
[BUG] Preview window still displayed for some commands options and arguments

### ISSUE THREAD

**Issue by xfzv** [Aloxaf/fzf-tab#319]
#### Describe the bug

Despite using

```zsh
zstyle ':fzf-tab:complete:*:options' fzf-preview
zstyle ':fzf-tab:complete:*:argument-1' fzf-preview
```

, the preview window is still displayed for some commands options and arguments such as `chezmoi` or `kitty`:

- `chezmoi <TAB>` or `chezmoi -- <TAB>`
![image](https://user-images.githubusercontent.com/78810647/194669785-cce66b77-ad14-4950-98fe-32bc39e96e65.png)

- `kitty -- <TAB>`
![image](https://user-images.githubusercontent.com/78810647/194669773-c63e25e2-7ab5-48e8-8b7b-f816d2ae98fc.png)

---
No issue with most binaries installed from the official Arch repositories, here `lsd -- <TAB>` for example:

![image](https://user-images.githubusercontent.com/78810647/194670187-0449a999-b7a3-43a2-835a-2436673e8676.png)

---

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. On Arch Linux (also happens on my Gentoo install), install `bat` or `lsd` ; `chezmoi` or `kitty` from official Arch repositories
2. Use
```zsh
zstyle ':fzf-tab:complete:*:options' fzf-preview
zstyle ':fzf-tab:complete:*:argument-1' fzf-preview
```
4. Type `lsd --` or `bat --` and press `<TAB>` -> the preview window isn't drawn
5. Type `chezmoi` or `kitty --` and press `<TAB>` -> the preview window is drawn

#### Expected behavior
The preview window shouldn't be drawn for `chezmoi` and `kitty --`

#### Environment:
 - OS: Arch Linux / Gentoo
 - zsh version: 5.9

Are there other `zstyle` that I could use to avoid this?

Thanks!

**Comment by Aloxaf** [comment]
This is not a bug. Setting context when doing completion is just a convention, not a rule.

You can disable preview for these tools individually.
```zsh
zstyle ':fzf-tab:complete:chezmoi:*' fzf-preview
zstyle ':fzf-tab:complete:kitty:*' fzf-preview
```
