### ISSUE TITLE
[Q] Select first item

### ISSUE THREAD

**Issue by Marekkon5** [Aloxaf/fzf-tab#322]
**Describe your question**

Hello, is there an option to automatically autofill the first item from the list? Related:  #247

Normal ZSH / Bash:
`car` `[TAB]` `cargo` gets completed

fzf-tab:
`car` `[TAB]` (menu opens, but the prompt is still just `car`, you have to press enter to autocomplete the first option).

Thank you.

**Comment by p0da** [comment]
--select-1 flag?

**Comment by Marekkon5** [comment]
Where can I add it?

**Comment by p0da** [comment]
Reference: https://github.com/Aloxaf/fzf-tab/wiki/Configuration

**Comment by Aloxaf** [comment]
Do you mean the first item or the common prefix?

**Comment by Marekkon5** [comment]
First item

**Comment by pablospe** [comment]
How to select the common prefix? Is it possible?

**Comment by cohml** [comment]
I have the same question. Automatically completing to the longest unambiguous common prefix would be a nice behavior.

**Comment by Aloxaf** [comment]
#8
