### ISSUE TITLE
[BUG] $realpath is empty for adb.

### ISSUE THREAD

**Issue by Freed-Wu** [Aloxaf/fzf-tab#325]
#### Describe the bug

`$realpath` is empty for adb.

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. Type 'adb pull'
2. Press <kbd>Tab</kbd>

#### Expected behavior

```
test
/sdcard/amap
```

#### Screenshots

only test

![screen-2022-11-04-18-11-34](https://user-images.githubusercontent.com/32936898/199948599-e6a55804-6a3c-4bb0-9a14-16ab1fc17cec.jpg)

#### Environment:
 - OS: 6.0.2-arch1-1
 - zsh version: 5.9

#### Minimal zshrc

```zsh
case $group in
  'file/folder on device')
    echo test
    echo $realpath
    # [[ -f $realpath ]] && adb shell cat $realpath || adb shell ls $realpath
    ;;
  'local file/folder')
    less $realpath
    ;;
esac
```

**Comment by Aloxaf** [comment]
`adb pull`'s completion result is not a valid path in your host machine.

You can use `$ctxt[hpre]$word` to get the full path here.

```zsh
zstyle ':fzf-tab:complete:adb-pull:*' fzf-preview 'echo $ctxt[hpre]$word'
```

**Comment by Freed-Wu** [comment]
Similar for dconf, however, `$ctxt[hpre]$word` cannot work.

```
zstyle ':fzf-tab:complete:dconf-list:*' fzf-preview 'echo $ctxt[hpre]$word'
```

![Screenshot from 2024-04-24 00-25-40](https://github.com/Aloxaf/fzf-tab/assets/32936898/cfa05601-7d59-4707-b9d1-af85750374b1)

Expected behaviour: `/org/gnome/cheese`

Actual: `cheese`
