### ISSUE TITLE
[Q] Difference between fzf-tab-completion and fzf-tab

### ISSUE THREAD

**Issue by mhalano** [Aloxaf/fzf-tab#328]
What are the differences and similarities between [fzf-tab-completion](https://github.com/lincheney/fzf-tab-completion) and fzf-tab? I couldn't understand if both can work together or if fzf-tab do the same as fzf-tab-completion but only on Zsh.

**Comment by Aloxaf** [comment]
Both of them perform well in basic "completion". You can choose according to your own flavor.
