### ISSUE TITLE
press tab with error

### ISSUE THREAD

**Issue by rainbow23** [Aloxaf/fzf-tab#33]
trigger the completion with pressing TAB I get this error:

1. Install zsh 5.7.1  
2. `git clone https://github.com/Aloxaf/fzf-tab.git ~/fzf-tab`
3. `source ~/fzf-tab/fzf-tab.plugin.zsh`
4. put word 'git ' & tab pressed
5. error happened
```
git                                                                                      
compadd:28: number expected
compadd:28: number expected
```
6. press enter and show error message 
`VCS_INFO_get_cmd:6: vcs_comm: assignment to invalid subscript range`
 
My system: OS X EICaptain

**Comment by Aloxaf** [comment]
Strange, can you provide your ~/.zshrc?

**Comment by rainbow23** [comment]
Thanks for your reply.

It seems that the error is probably caused by loading zinit plugin.
Below is my zinit file. 
https://github.com/rainbow23/dotfiles/blob/develop/zplugin.sh#L9-L10
When I Comment out below that fzf-tab worked fine.
```
autoload -Uz _zinit
(($ {+ _ comps})) Commenting && _comps [zinit] = _ zinit
```
Maybe the cause of the error is zinit load 
`zsh-users/zsh-autosuggestions` or  `zsh-users/zsh-completions` or `zsh-users/zsh-syntax-highlighting`

**Comment by Aloxaf** [comment]
As zinit's README say:
> If you place the source below compinit, then add those two lines after the source:
> ```
> autoload -Uz _zinit
> (( ${+_comps} )) && _comps[zinit]=_zinit
> ```
Your `source` is above compinit, so I think you can remove this two line,

**Comment by rainbow23** [comment]
Thanks for your reply.

```
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
```
I delete above comment but `compadd:28: number expected` error happend.
Maybe that error occured in only `OS X EICaptain`.
fzf-tab works fine on `OS X Mojave` and `Ubuntu18`.
I'm going to upgrade `OS X EICaptain` to `OS X Mojave`.
Thank you your support.
