### ISSUE TITLE
[Q] Is it possible to use continuous-trigger with TAB or ENTER?

### ISSUE THREAD

**Issue by pablospe** [Aloxaf/fzf-tab#338]
I would like to accept the selection with TAB (and ENTER), and then continue with the next completion, as it would happened with `/` keybinding (if `continuous-trigger` is set on).

I have tried the following without success:
```
zstyle ':fzf-tab:*' continuous-trigger '\e'
```

**Comment by Schievel1** [comment]
Is it possible to do accept the completion using TAB?

**Comment by pablospe** [comment]
Thanks for the reply, I ended up using:
`zstyle ':fzf-tab:*' continuous-trigger 'ctrl-e'`

for ENTER it would be:
`zstyle ':fzf-tab:*' continuous-trigger 'enter'`

and with TAB:
`zstyle ':fzf-tab:*' continuous-trigger 'tab'`

But this is not the behaviour I wanted, reason why I am using another shortcut (Ctrl-e).

**Comment by pablospe** [comment]
@Aloxaf One question here. If I use:
`zstyle ':fzf-tab:*' continuous-trigger 'enter'`
Is there a way to stop the `continuous-trigger`ing once that one element was selected?

I mean, if I do
```
vi <TAB>
```
and there are
```
a/b/c.txt
a/b/d.txt
```
I would like to go to `c.txt` file while pressing enters (showing me the options without pressing tab again, which it is the continuous-trigger), but once I arrive to one of the files like `c.txt`, I would like to stop the `continuous-trigger`. I always have to do `<ESC>` or `<alt+enter>` to finish the `continuous-trigger`, which it is not intuitive.

**Comment by pablospe** [comment]
For context, I am using: `zstyle ':fzf-tab:complete:(vi|vim|l|ls|code):*' fzf-preview 'less ${(Q)realpath}'`.

Note: I don't observe this behavior if I do `cd \<TAB\>`, which makes me things the previous line has something to do with it.
