### ISSUE TITLE
[BUG] highlight color not respected

### ISSUE THREAD

**Issue by bradleyfrank** [Aloxaf/fzf-tab#343]
#### Describe the bug
It seems the `hl` color will not match my settings. No matter what I change it to, the highlight color is stuck at white. I've tried this in multiple terminals to be sure (Apple Terminal, Hyper, Kitty).

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. Set `hl` color
2. `cd` into directory
3. Begin search, observe substring matches
4. Observe substring matches do not match `hl` color

#### Expected behavior
Substring matches should be the color defined by `hl`.

#### Screenshots

With `export FZF_DEFAULT_OPTS='--color info:33,prompt:33,pointer:166,marker:166,spinner:33,fg:234:regular,fg+:232:regular,bg+:251:regular,hl:33:bold,hl+:33:regular'`

<img width="959" alt="Screenshot 2023-01-21 at 5 07 23 PM" src="https://user-images.githubusercontent.com/6333022/213888819-a4fbbf40-d13b-4943-9a22-dff142cccbb6.png">
<img width="387" alt="Screenshot 2023-01-21 at 5 08 57 PM" src="https://user-images.githubusercontent.com/6333022/213888868-2f91636a-ce97-4c77-8772-eb90f22f0b79.png">

With `export FZF_DEFAULT_OPTS='--color ...hl:200:reverse...'`

<img width="308" alt="Screenshot 2023-01-21 at 5 14 44 PM" src="https://user-images.githubusercontent.com/6333022/213889033-7866bed2-dfaa-4e59-b26e-615d0faf50ac.png">

#### Environment:
 - OS: macOS 13.1
 - zsh version: 5.9 (arm-apple-darwin21.3.0)

#### Minimal zshrc
https://gist.github.com/bradleyfrank/a9b81d10fe380bee251ac2e610103daf

#### Log
If applicable, use `C-x .` to trigger completion and provide the log.

**Comment by bradleyfrank** [comment]
I decided to be explicit and add `zstyle ":fzf-tab:*" fzf-flags --color=hl:33` which fixed it! Curious though why this still might be happening.

**Comment by Aloxaf** [comment]
It is expected.
Commandline arguments have higher priority then environment variable. So you have to use `fzf-flags` to overwrite fzf-tab's default setting.

**Comment by daephx** [comment]
I came across this problem in my own setup and thankfully I found this issue. 
It does seem that explicitly setting the `hl` color in `fzf-flag` does remedy this for now. So Thanks!
Though, I'd much rather it inherit the values I've set in `FZF_DEFAULT_OPTS` to avoid defining the value in multiple places in such a hack-y fashion.

Before finding this issue, I did grep for `hl` and I tried deleting the following line.

https://github.com/Aloxaf/fzf-tab/blob/c7fb028ec0bbc1056c51508602dbd61b0f475ac3/lib/-ftb-fzf#L88

This does allow me to set the `hl` color as I please without any "noticeable" side effects, but I didn't do any rigorous testing and struggle to understand the intended purpose of this condition. Why enforce the values of a full or dull white if there are header-lines or categories present? Al least with my colorscheme these shades are almost indistinguishable and more difficult to parse at a glance compared to my preferred `hl` value.
