### ISSUE TITLE
[BUG] Turn off useless prompts

### ISSUE THREAD

**Issue by wangmings** [Aloxaf/fzf-tab#345]
# How to turn off the unnecessary prompt in the red box in the following picture

![截屏2023-01-28 下午6 01 08](https://user-images.githubusercontent.com/44308153/215319983-f33e11dc-6f9b-45c6-b027-1c882d681331.png)

**Comment by Aloxaf** [comment]
`zstyle -d ':completion:*:descriptions' format`
