### ISSUE TITLE
[FR] Toggle header groups

### ISSUE THREAD

**Issue by qoomon** [Aloxaf/fzf-tab#350]
**Is your feature request related to a problem? Please describe.**
Sometimes the count of groups is overwhelming and annoying e.g. `git <tab>`

**Describe the solution you'd like**
* A keybinding to toggle `fzf` header would be awesome e.g. `F3` or `-`
* An option to disable header by default, that way I can display header with the keybinding on demand.

**Comment by Aloxaf** [comment]
You can disable it totally by: `zstyle -d ':completion:*:descriptions' format`
Or disable it for git: `zstyle ':completion:*:git:*:descriptions' format ''`

**Comment by qoomon** [comment]
@Aloxaf thanks for your reply, however this would be just a workaround for my use case. I like that the different groups are in different colours and I'll loose that feature if I set `format` to `''` And I'd like to have headers disabled by default and show them as a legend if I need them only.

And thanks for this awesome and generic plugin
