### ISSUE TITLE
[Q] How to have fzf-tab be enabled by default instead of needing to use enable-fzf-tab?

### ISSUE THREAD

**Issue by himat** [Aloxaf/fzf-tab#356]
Right now, it seems like I need to run `enable-fzf-tab` every time I open up a new shell in order for hitting `<tab>` to show the fzf menu.
This is very annoying and inefficient. 

Is there a way to have `fzf-tab` enabled by default all the time?

Context
- I'm using zsh and ohmyzsh.
- Plugins line in zshrc: `plugins=(git colorize autojump aws nvm poetry fzf-tab zsh-autosuggestions zsh-syntax-highlighting)`

**Comment by mark2185** [comment]
It _should_ be enabled by default, just adding it to the `plugins` list should be enough. 

Try having it as the only plugin and see if it works, it may be conflicting with something else (e.g. `zsh-autosuggestions`)

**Comment by KevinLTT** [comment]
> Right now, it seems like I need to run `enable-fzf-tab` every time I open up a new shell in order for hitting `<tab>` to show the fzf menu. This is very annoying and inefficient.
> 
> Is there a way to have `fzf-tab` enabled by default all the time?
> 
> Context
> 
> * I'm using zsh and ohmyzsh.
> * Plugins line in zshrc: `plugins=(git colorize autojump aws nvm poetry fzf-tab zsh-autosuggestions zsh-syntax-highlighting)`

I encountered the same problem, have you solved it? @himat

**Comment by himat** [comment]
No, I didn't solve it

**Comment by umarov** [comment]
I have this same issue when I use my Ubuntu servers over ssh. I share the same dotfiles on my macbook pro as well. On my macbook pro, fzf-tab is always enabled and just works. On Ubuntu, I have to call `enable-fzf-tab`. 

```
# Source/Load zinit
source "${ZINIT_HOME}/zinit.zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Add in Powerlevel10k
zinit ice depth=1; zinit light romkatv/powerlevel10k

# Add in zsh plugins
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab
```

these are my plugins
