### ISSUE TITLE
[Q]Double tapping Tab Required

### ISSUE THREAD

**Issue by JustCauseWhyNot** [Aloxaf/fzf-tab#368]
For some reason in the past month or so pressing tab 2x is required in order for tab completion menu to show up. I don't know why the behavior has changed. I narrowed the issue down to this plugin. Here's my [zsh dotfiles](https://github.com/JustCauseWhyNot/dotfiles/tree/main/.config/shells/zsh). I'd like to only have to press tab 1x to bring up the completion menu.

**Comment by Aloxaf** [comment]
fzf-tab should load before fast-syntax-highlighting and zsh-autosuggestions.

```diff
+source $ZDOTDIR/plugins/fzf-tab/fzf-tab.plugin.zsh
source $ZDOTDIR/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source $ZDOTDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh && bindkey '^ ' autosuggest-accept
-source $ZDOTDIR/plugins/fzf-tab/fzf-tab.plugin.zsh
```

If the problem still exists, check the output of `bindkey "^I"`. If it is fzf-tab-complete, then trigger completion with `Ctrl+X .` and upload the log.

**Comment by JustCauseWhyNot** [comment]
I don't really know what you mean with 
>trigger completion with Ctrl+X . and upload the log.

There's not output into the console, and I don't know what & where the log is supposed to be. I also can't seem to complete a completion while pressing cntrl+x.

**Comment by Aloxaf** [comment]
@JustCauseWhyNot Press <kbd>Ctrl+x</kbd>，and then press <kbd>.</kbd>

**Comment by JustCauseWhyNot** [comment]
I'm sorry for being a bozo. But I don't think I'm getting the effect you want. I press tab 1x to run a completion but I've got to press tab(or any key) 2x to for the menu to show. So I press `tab` no menu then I press `Ctrl+x` brings up menu then `.` it doesn't appear to do anything, and finally I press enter to select anything to finish completion. But no debugging output is shown, and if the output is being sent to a log somewhere I don't know which file to look upload.

**Comment by Aloxaf** [comment]
@JustCauseWhyNot What's the output of `bindkey "^I"`

**Comment by JustCauseWhyNot** [comment]
```
❯ bindkey "^I"
"^I" fzf-tab-complete
```

**Comment by JustCauseWhyNot** [comment]
Is this kinda dead? Is there anything I can provide in-order to help troubleshoot?

**Comment by JustCauseWhyNot** [comment]
I'm slightly less dumb now here's the [trace log](https://github.com/user-attachments/files/17669910/zsh-22589-fzf-tab-2.log). Also I'm experiencing this problem with fzf itself when not even using this plugin to auto complete.

**Comment by JustCauseWhyNot** [comment]
I've found the issue. It's with simple terminal.

**Comment by jcam3ron** [comment]
@JustCauseWhyNot what ended up being the issue? I'm seeing the same issue with Ghostty

**Comment by JustCauseWhyNot** [comment]
I'm sorry I don't remember and looking back at my st commits I don't see anything about what was the fix. The only thing I see is I redid the repo/patches the same day I closed this issue. I'm not sure what the issue was. I'm sorry I couldn't give you a better answer

**Comment by jcam3ron** [comment]
No worries, thank you for looking!
