### ISSUE TITLE
[Q] What's this shebang '#!/hint/zsh'?

### ISSUE THREAD

**Issue by mtesseract** [Aloxaf/fzf-tab#376]
Hi. I have seen multiple occurrences in this repo of the shebang line:

```
#!/hint/zsh
```

I couldn't find any comment or explanation on this. I have never seen a directory `/hint` being referenced, I am also not aware of any systems where this is a standard path containing shells. What is the meaning of this? Is it expected that some magical substitution or something similar is going on (when?)?

(Context: I'd like to use the fzf tmux popup code in this repo, on macOS).

Thank you,
Moritz

**Comment by Aloxaf** [comment]
I just want to get syntax highlighting in the editor, without giving the impression that these files are executable.

`/hint` is nothing special, it will be ignored by most editors.
