### ISSUE TITLE
[Q] Problem with zsh: Command not found: _podman, but it's installed.

### ISSUE THREAD

**Issue by snics** [Aloxaf/fzf-tab#382]
**Describe your question**
A clear and concise description of your question.

I have a problem with the "podman" command, which is not found in my Zsh environment. I've tried to execute this command, but every time I get the error message "zsh: command not found: _podman". I'm not sure what the cause of this issue is, as I can execute other commands in Zsh without any problems. This also happens with other commands like "brew".

Do you have any idea what it could be?

**Comment by Aloxaf** [comment]
remove ~/.zcompdump may help.
if you are using zinit, try `zinit cclear `
