### ISSUE TITLE
[BUG] 在最新版本的 fzf-tab 中无法使用 fzf-bindings 参数绑定 tab:accept

### ISSUE THREAD

**Issue by FlowBreeze** [Aloxaf/fzf-tab#383]
#### Describe the bug
@Aloxaf  很抱歉使用中文,因为我觉得母语表达会更加准确些  
在最新版本的 fzf-tab 中无法使用 fzf-bindings 参数绑定 tab:accept

#### this is the minimal zshrc which can reproduce this bug
```.zshrc
# fzf-tab
# tab,space:  将当前选项上屏
zinit wait lucid for \
    depth"1" \
    atload"zstyle ':fzf-tab:*' fzf-bindings 'tab:accept' 'space:accept'" \
    atload"zstyle ':fzf-tab:*' fzf-command sk" \
    Aloxaf/fzf-tab
```

#### To Reproduce
1. 输入 ls
2. 按 tab 访问 fzf-tab
3. 无法使用 `tab` 进行补全

#### Environment:
 - OS: Ubuntu 22.04
 - zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

#### 尝试过

- 在 '~/.local/share/zinit/plugins/Aloxaf---fzf-tab' 下执行 `git checkout f95cdcf` 命令, 再次尝试补全, 运行正常符合预期
- 使用 `echo 1 | sk --bind 'tab:accept,space:accept'` 命令, 尝试使用 tab 补全, 运行正常符合预期

#### Expected behavior
- 可以通过上述配置使用 tab 进行补全
- 如果现在的状态符合预期,请告诉我是否有官方推荐的配置,能达成以前版本直接使用 tab 进行补全的状态

**Comment by GladioFeng** [comment]
遇到了类似的bug，在tmux中无法使用tab键补全出错，刚进入tmux可以用tab补全，但是几次过后就tab键就变成了切换功能了，在正常终端tab键补全未出错

**Comment by GladioFeng** [comment]
好像找到可能的原因了， 把popup-smart-tab 设置为No 就可以了
