### ISSUE TITLE
[BUG] fzf-bindings 'tab:accept' stops working after changing directories and going back

### ISSUE THREAD

**Issue by brunovzky** [Aloxaf/fzf-tab#390]
#### Describe the bug
`zstyle ':fzf-tab:*' fzf-bindings 'tab:accept'` stops working after changing directories and going back

I can make sure:
- [X] I am using the latest version of fzf-tab
- [X] this is the minimal zshrc which can reproduce this bug
- [X] fzf-tab is loaded after `compinit`
- [X] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [X] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. Add `zstyle ':fzf-tab:*' fzf-bindings 'tab:accept'` to your ~/.zshrc file and `source ~/.zshrc`
2. Change directories for two/three times using <kbd>Tab</kbd> to accept the selected option and then use `cd` or `cd ..` to go back one directory
3. Instead of accepting the selected option, <kbd>Tab</kbd> will now cycle between then (as If the bind were not added)
4. After using the `clear` command the bind starts works again

#### Expected behavior
Keep using tab as the binded key

#### Screenshots
https://github.com/Aloxaf/fzf-tab/assets/139287915/d61f6063-2a7c-44ba-affd-9acc907db8ff

#### Environment:
 - OS: MacOS Ventura 13.5.2
 - ZSH Version: zsh 5.9 (x86_64-apple-darwin23.0)

#### Minimal zshrc (My current settings for FZF-Tab)
[[ -z $TMUX ]] && exec tmux
zstyle ':fzf-tab:*' fzf-bindings 'tab:accept'
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup

**Comment by Aloxaf** [comment]
Just disable `popup-smart-tab`: `zstyle ':fzf-tab:*' popup-smart-tab no`

https://github.com/Aloxaf/fzf-tab/blob/b06e7574577cd729c629419a62029d31d0565a7a/lib/ftb-tmux-popup#L75-L77
