### ISSUE TITLE
Allow fuzzy filters before completion is invoked

### ISSUE THREAD

**Issue by focusaurus** [Aloxaf/fzf-tab#4]
**Aside:** I applaud your effort here. A colleague of mine and I have also been pursuing a way to make fzf-style filtering the default in our zsh setup for a while. This gets a lot of it working. Great job!

---

From some brief usage, it seems like a filter before completion has to be a prefix, not a fuzzy filter, but then after completion begins, fuzzy filters are allowed.

For example, if I set up some filenames like this:

```sh
cd $(mktemp -d /tmp/fzf-XXX)
touch alpha-bravo-charlie alpha-charlie-delta alpha-delta-echo bravo-charlie-delta delta-echo-foxtrot
```

If I type `ls a<TAB>` I get fuzzy filtering for the `a*` glob matching filenames. But if I do it fuzzy style like `ls abc<TAB>` I get no candidates because that's a fuzzy filter, not a prefix. Once a prefix filter is active in fzf, I can clear it and then do my fuzzy version (remove "alpha-" and replace with "abc") for example, which works.

Just wondering if others expect to be able to type their fuzzy filter first then hit TAB and have it work. If so, I'd use this constantly for accessing deeply-nested files.

In the above example, I'd love to be able to type `ls abc<TAB>` and have it immediately expand to the only fuzzy match, `alpha-bravo-charlie`.

**Comment by Aloxaf** [comment]
This is an interesting idea, but it is beyond fzf-tab's ability currently. fzf-tab only show your result, it doesn't do the match.

But this can be done by zsh itself. [Here](https://superuser.com/questions/415650/does-a-fuzzy-matching-mode-exist-for-the-zsh-shell/815317) is a zstyle which is your want:
```
# 0 -- vanilla completion (abc => abc)
# 1 -- smart case completion (abc => Abc)
# 2 -- word flex completion (abc => A-big-Car)
# 3 -- full flex completion (abc => ABraCadabra)
zstyle ':completion:*' matcher-list '' \
  'm:{a-z\-}={A-Z\_}' \
  'r:[^[:alpha:]]||[[:alpha:]]=** r:|=* m:{a-z\-}={A-Z\_}' \
  'r:|?=** m:{a-z\-}={A-Z\_}'
```

**Comment by Aloxaf** [comment]
Emmm, after half a day of trial I found the zstyle above is too fuzzy.

Here may be a better solution, only smart case completion and word flex completion:
```bash
zstyle ':completion:*' matcher-list '' \
  'm:{[:lower:]-}={[:upper:]_}' \
  'r:|[.,_-]=** r:|=*'
```

In your example, you can use `a-b-c` to match `alpha-bravo-charlie`, `d-e-f` or `d-f` to match `delta-echo-foxtrot`.
