### ISSUE TITLE
[Q] can not use regex character, such as $ and .

### ISSUE THREAD

**Issue by GladioFeng** [Aloxaf/fzf-tab#403]
**Describe your question**

<img width="450" alt="image" src="https://github.com/Aloxaf/fzf-tab/assets/100987925/65439d9a-c1f5-4765-a58a-7679bb93462f">

regex function does not work, hit $, but it does not work
<img width="418" alt="image" src="https://github.com/Aloxaf/fzf-tab/assets/100987925/04ecee55-261c-42d0-bb67-d2cabe086f87">

**Comment by Aloxaf** [comment]
There are two reasons:
1. fzf doesn't support search with regex: https://man.archlinux.org/man/fzf.1#EXTENDED_SEARCH_MODE
2. fzf-tab will add some non-printable characters as seperator, so `$` won't match suffix.

**Comment by GladioFeng** [comment]
can I modify some setting to make $ match suffix?
^ can match prefix in my remote pc.

**Comment by Sneethe** [comment]
Only fzf search syntax that doesn't work is `$` and its inverse combination `!flac$`.
