### ISSUE TITLE
[Q]  Some programs cannot be completed, how to solve it?

### ISSUE THREAD

**Issue by ghost** [Aloxaf/fzf-tab#407]
**Describe your question**
e.g [asdf](https://github.com/asdf-vm/asdf)

### Just like how used it before
`asdf <tab>`
but didn't get any command line completion.
I have encountered a similar situation before, but I have forgotten the specific procedure.
The solution at that time, i try `a program --help` 
Then let me use <tab> again and I get completion.

**Comment by Aloxaf** [comment]
Please remve `~/.zcompdump` and try again.
