### ISSUE TITLE
[Q] how to get color git Tab as shown in the Readme?

### ISSUE THREAD

**Issue by ssh352** [Aloxaf/fzf-tab#419]
**Describe your question**
A clear and concise description of your question.
<img width="854" alt="Screenshot 2024-02-28 at 11 53 03 PM" src="https://github.com/Aloxaf/fzf-tab/assets/41779116/49fd5b9f-5d3a-4171-a26f-16b9c4c4705f">

I'd like to have output like the Readme shows. Thanks!

**Comment by Aloxaf** [comment]
```zsh
zstyle ':completion:*:descriptions' format '[%d]'
```

**Comment by xkoldxx** [comment]
only brew colors for me in green and blue what am i mssing
