### ISSUE TITLE
Bind to double-tab

### ISSUE THREAD

**Issue by AndrewC-B** [Aloxaf/fzf-tab#42]
I really like this plugin, but I'd prefer to bind it to `tab-tab`. Is this possible? I naively tried replacing `^I` with `^I^I` in the script, but that didn't work.

Any and all help greatly appreciated, and many thanks for this project!

(This is similar to https://github.com/Aloxaf/fzf-tab/issues/8, but perhaps simpler. Feel free to close this issue if it's too similar)

**Comment by Aloxaf** [comment]
`^I` appears twice in the script, you just need to replace the second `^I`.
https://github.com/Aloxaf/fzf-tab/blob/83c98a4dbf703d58795e8d9482135b72c6a0a433/fzf-tab.zsh#L357

Or put the following code below the code that loads fzf-tab

```zsh
bindkey '^I' expand-or-complete
bindkey '^I^I' fzf-tab-complete
```

**Comment by AndrewC-B** [comment]
Thanks heaps! That’s perfect. (Sorry for the late reply - busy week).
