### ISSUE TITLE
[Q] How to sort directory first on completion?

### ISSUE THREAD

**Issue by adetabrani** [Aloxaf/fzf-tab#427]
**Describe your question**

![1712501918_Apr07_21:58:38](https://github.com/Aloxaf/fzf-tab/assets/47938004/9ee78146-fc63-41b7-95b1-7023d3e7346c)

Is it possible to sort directories first then followed by files? I tried adding the following configuration to my .zshrc, but it doesn't seem to work

`
zstyle ':completion:*' list-dirs-first true
`

**Comment by Aloxaf** [comment]
try
```zsh
zstyle ":completion:*" sort false
zstyle ':completion:*' list-dirs-first true
```

**Comment by adetabrani** [comment]
worked, thanks

**Comment by p1r473** [comment]
@Aloxaf  I tried this but then I get this weird thing sorted at the begining
![image](https://github.com/Aloxaf/fzf-tab/assets/9235633/9f44ae6c-47f0-4040-8647-f0a4baae3ad6)
