### ISSUE TITLE
[Q] Custom Height

### ISSUE THREAD

**Issue by rakalex** [Aloxaf/fzf-tab#429]
Is is possible to control the height size or number of items to show? 

when there not much items, it shows just 2 lines.
<img width="2300" alt="image" src="https://github.com/Aloxaf/fzf-tab/assets/1472809/7580cd0a-5d87-4208-8c30-1adf8b072e42">

but when there are many, then it show them as normal
<img width="1112" alt="image" src="https://github.com/Aloxaf/fzf-tab/assets/1472809/f47f204e-e6bc-4892-9d00-60b5fca0bee9">

**Comment by Aloxaf** [comment]
try `zstyle ':fzf-tab:*' fzf-flags --height=10`

**Comment by rakalex** [comment]
no, it doesn't, it fixes the first screen, but as you can see then it breaks the second one with large list.
<img width="1798" alt="image" src="https://github.com/Aloxaf/fzf-tab/assets/1472809/8f211c38-a26c-4d00-aa4e-9c3de4343019">

<img width="1947" alt="image" src="https://github.com/Aloxaf/fzf-tab/assets/1472809/245ba51e-e3f5-4482-8c06-91d995af32ef">

**Comment by SteveRusin** [comment]
@rakalex try this `zstyle ':fzf-tab:*' fzf-flags --height=~40`

Accordingly to the docs `~` is a key here
>     --height=[~]HEIGHT[%]  Display fzf window below the cursor with the given
>                            height instead of using fullscreen.
>                            A negative value is calculated as the terminal height
>                            minus the given value.
>                            If prefixed with '~', fzf will determine the height
