### ISSUE TITLE
Candidates issue with oh-my-zsh

### ISSUE THREAD

**Issue by seagle0128** [Aloxaf/fzf-tab#43]
Hi, Thanks for the great zsh plugin! I really like it.

But I have an minor issue with `oh-my-zsh`. As you know, `oh-my-zsh` also provides completion mechanism. The screenshot is below.

![image](https://user-images.githubusercontent.com/140797/75375830-de74dd80-5909-11ea-9dac-9b7200f29bb3.png)

If enabling `fzf-tab`, it looks like this. The group headers are listed in the candidates as well. Can they be removed for better experience? It's better to colorize the candidates for different groups IMO.

![image](https://user-images.githubusercontent.com/140797/75375941-1c720180-590a-11ea-8f3c-971454df6cb5.png)

**Comment by romkatv** [comment]
See https://github.com/Aloxaf/fzf-tab/issues/24.

fzf-tab is not supposed or guaranteed to work perfectly with any set of completion styles. It's natural and even expected that if you take an existing set of completion styles optimized for some other UI and drop fzf-tab on it, it'll look suboptimal.

P.S.

oh-my-zsh doesn't provide completion mechanism. It just sets a few parameters that Zsh provides. That is Zsh allows you to choose whether to display menu on the first tab or the second, how to display groups, etc. Oh My Zsh simply makes some arbitrary choices.

**Comment by seagle0128** [comment]
Okay. Thanks for your quick reply. I am closing it.

**Comment by romkatv** [comment]
I should have mentioned I'm just another user of fzf-tab (will always do so in the future when commenting here). The owner of the project is the  one in charge here.

**Comment by seagle0128** [comment]
Sorry! I reopen this issue since I found this similar [plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/zsh-interactive-cd) is able to handle the group names correctly. Bu it has less features obviously.

**Comment by seagle0128** [comment]
Aha, I got a patch and it works well in my env. Use `expand-or-complete` instead of `_fzf_tab_orig_widge`.

```elisp
fzf-tab-complete() {
    # complete or not complete, this is a question
    # this name must be ugly to avoid clashes
    local -i _fzf_tab_continue=1 _fzf_tab_should_complete=0
    while (( _fzf_tab_continue )); do
        _fzf_tab_should_complete=0
        _fzf_tab_continue=0
        if (( ${+functions[_main_complete]} )); then
            # hack: hook _main_complete to check whether completion function will be called
            local orig_main_complete=${functions[_main_complete]}
            function _main_complete() { typeset -g _fzf_tab_should_complete=1; }
            {
                zle expand-or-complete
            } always {
                functions[_main_complete]=$orig_main_complete
            }
        fi
        # must run with user options; don't add `emulate -L zsh` above this line
        (( ! _fzf_tab_should_complete )) || zle _fzf_tab_complete
        zle redisplay
    done
}
```

![image](https://user-images.githubusercontent.com/140797/75381243-64495680-5913-11ea-89ab-54fcba514293.png)

**Comment by Aloxaf** [comment]
Sorry I am late here. As @romkatv(thank you so much) says this is an known issue.

But you don't need to hide the headers, you can overwrite the zsh's default settings, eg `zstyle ':completion:*:descriptions' format '-- %d --'`.
