### ISSUE TITLE
Does not work if completions where added with compctl

### ISSUE THREAD

**Issue by doubleloop** [Aloxaf/fzf-tab#44]
For [z.lua](https://github.com/skywind3000/z.lua) plugin, completions are presented with standard zsh menu instead of fzf.

z.lua uses [this code](https://github.com/skywind3000/z.lua/blob/master/z.lua#L2202-L2209) for completions:
```
_zlua_zsh_tab_completion() {
	# tab completion
	local compl
	read -l compl
	(( $+compstate )) && compstate[insert]=menu # no expand
	reply=(${(f)"$(_zlua --complete "$compl")"})
}
compctl -U -K _zlua_zsh_tab_completion _zlua
```

**Comment by Aloxaf** [comment]
Fixed by https://github.com/skywind3000/z.lua/pull/93. LOL

`compctl` is very ancient and won't be support. ( And another reason: AFAIK, there is not an easy way to support it. )
