### ISSUE TITLE
[BUG] Breaks nix completion when quotes are used instead of \

### ISSUE THREAD

**Issue by Artturin** [Aloxaf/fzf-tab#447]
#### Describe the bug

https://github.com/NixOS/nix/blob/master/misc/zsh/completion.zsh

Bisected to acdc37214bf2f8e4b4d86df1e179bf2e226f9e12

I can make sure:
- [x] I am using the latest version of fzf-tab
- [X] this is the minimal zshrc which can reproduce this bug
- [X] fzf-tab is loaded after `compinit`
- [X] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [X] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
in any nix flake (ex: https://github.com/NixOS/nixpkgs)
`nix build ".#<tab>"` doesn't show completions, only turns the `".#"` to `.#` for a second

`nix build .#<tab>` turns `.#` to `.\#` and then a another tab shows completions

#### Environment:
 - OS: NixOS
 - zsh version: 5.9

#### Minimal zshrc

```sh
$ ZDOTDIR=empty zsh
$ autoload -U compinit; compinit
$ source ./fzf-tab/fzf-tab.plugin.zsh
```

#### Log
If applicable, use `C-x .` to trigger completion and provide the log.

**Comment by Aloxaf** [comment]
Can you try #448? It should fix `".#<tab>"`.

As for `.#<tab>`, the behavior is expected, you can disable it by `zstyle ':completion:*' menu yes`.

**Comment by Artturin** [comment]
Awesome, that fixes it. Thank you.
