### ISSUE TITLE
[BUG] Using `--tmux` in an exported `FZF_DEFAULT_OPTS` breaks `ftb-tmux-popup`

### ISSUE THREAD

**Issue by andrewbraxton** [Aloxaf/fzf-tab#455]
#### Describe the bug

Using `--tmux` in an exported `FZF_DEFAULT_OPTS` breaks `ftb-tmux-popup`. Weird thing is that it seems to stay broken even if you `unset FZF_DEFAULT_OPTS`.

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. Enter tmux
1. Type `ls` (or anything)
2. Press <kbd>Tab</kbd>
3. Popup flashes briefly and disappears

#### Expected behavior
Popup appears normally and allows selection

#### Environment:
 - OS: macOS Sonoma 14.5
 - zsh version: 5.9

#### Minimal zshrc

```
autoload -Uz compinit
compinit

export FZF_DEFAULT_OPTS='--tmux'

source ~/.fzf-tab/fzf-tab.plugin.zsh
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
```

**Comment by cameronbrill** [comment]
I am also running into this issue

**Comment by cameronbrill** [comment]
interestingly, if I remove `export FZF_DEFAULT_OPTS='--tmux'` from my `zshrc`, start a tmux session, add `export FZF_DEFAULT_OPTS='--tmux'` to my zshrc, then run `zsh` to restart the shell, both ftb-tmux-popup and the fzf tmux popup work as intended

**Comment by andrewbraxton** [comment]
Yeah, I ran a bunch of the same experiments and got similar confusing results.

**Comment by itahol** [comment]
I have the same problem, but I couldn't resolve it even when trying your trick. Did you figure this out?

**Comment by itahol** [comment]
My current workaround is editing `ftb-tmux-popup` so it runs fzf without "--tmux" in its opts, like so:
```zsh
echo -E "env SHELL=$ZSH_NAME FZF_DEFAULT_OPTS=$BASE_FZF_DEFAULT_OPTS $commands[fzf] ${(qq)fzf_opts[@]} < $tmp_dir/completions.$$ > $tmp_dir/result-$$" > $tmp_dir/fzf-$$
```

Seems to do the job.

**Comment by chris4prez** [comment]
I'm also seeing this issue as well.
