### ISSUE TITLE
[Q] What's the difference between this plugin and the offical fzf implementation?

### ISSUE THREAD

**Issue by matru** [Aloxaf/fzf-tab#460]
Talking about this one, included in fzf repo itself: https://github.com/junegunn/fzf/blob/master/shell/completion.zsh

**Comment by Aloxaf** [comment]
You can give it a try :)

**Comment by matru** [comment]
Sorry, I've been processing tons of plugins and didn't have time to compare each and every. Would've been incredibly helpful if you could explain the differences, but if not, I'll be testing it in a few weeks when I get the time.
