### ISSUE TITLE
fzf-tab hl color setting does not take effect

### ISSUE THREAD

**Issue by Archdsenna** [Aloxaf/fzf-tab#463]
My FZF-TAB color configuration does not fully inherit the FZF_DEFAULT_OPTS color setting of fzf,
This is my fzf configuration:
`export FZF_DEFAULT_OPTS="--color fg:23,fg+:23,bg+:151,hl:1,hl+:1,info:23,border:23,gutter:-1,prompt:29,pointer:9,query:0,header:23        \
        --height=100% --layout=reverse --info=inline --margin=1 --padding=1 --ansi   \
        --preview 'bat --style=numbers --color=always {}' --preview-window=right:50% \
        --pointer '❯'"
`

This is the interface of fzf:
![img_v3_02dg_7b78c216-21e1-44f4-8f66-7198c15a690g](https://github.com/user-attachments/assets/2459460b-9e31-4b07-a33a-ba6aafb82a36)

The following is the interface of fzf-tab:
![img_v3_02dg_5c58bf03-c21f-4874-8ea7-c77af15f046g](https://github.com/user-attachments/assets/b7f35190-b9b8-42eb-9cea-10d482a4629b)

You can see that in the matching result of the list, the color of the current item is displayed correctly, but the matching character of the non-current item is not displayed as expected.

In addition, there is a problem, fzf-tab preview prompt error:
`fork/exec /bin/zsh: invalid argument`
![image](https://github.com/user-attachments/assets/20e1e5ef-1dff-43e5-a1c9-e32c73ae5fd9)

How do I configure hl(not the current list of matching character colors) color in fzf-tab to color 1 out of 256 colors?

**Comment by Dzx1025** [comment]
I have this similar problem.

<img width="1717" alt="tab" src="https://github.com/user-attachments/assets/c509f129-d452-4fcd-b2d7-5575e3df95c9">

<img width="1717" alt="fzf" src="https://github.com/user-attachments/assets/7e343c4f-616a-469d-99d8-e050d867a0d0">

The font is hard to see. And changing the fg value only works for the fzf.

```
export FZF_DEFAULT_OPTS=" \
--color=bg+:#ccd0da,spinner:#dc8a78,hl:#d20f39 \
--color=fg:#4c4f69,header:#d20f39,info:#8839ef,pointer:#dc8a78 \
--color=marker:#7287fd,fg+:#4c4f69,prompt:#8839ef,hl+:#d20f39 \
--color=selected-bg:#bcc0cc \
--multi"
```

<img width="1271" alt="completion styling" src="https://github.com/user-attachments/assets/b05db0dd-f47d-4fcd-ae4d-f8d933d7b0d1">

**Comment by Aloxaf** [comment]
Don't use `FZF_DEFAULT_OPTS` and `--preview`, use `fzf-flags` and `fzf-preview` instead.

```zsh
zstyle ':fzf-tab:*' fzf-flags --color fg:23,fg+:23,bg+:151,hl:1,hl+:1,info:23,border:23,gutter:-1,prompt:29,pointer:9,query:0,header:23 --height=100% --layout=reverse --info=inline --margin=1 --padding=1 --ansi --preview-window=right:50% --pointer '❯'
zstyle ':fzf-tab:*' fzf-preview 'bat --style=numbers --color=always $realpath'
```

**Comment by rodhash** [comment]
Hi @Aloxaf 

What if we want to set the color for the tmux popup border? The `border` attribute above changes the color inside the tmux pop, right?

This cmd below works but outside of `fzf-tab`:
```sh
tmux display-popup -S fg=red
```

The idea is to customize the border style for completions like `cd confi<TAB>`


Thanks.

**Comment by rodhash** [comment]
Ouch .. just found in the docs (popup-style).
