### ISSUE TITLE
[Q] How to make `fzf-tab` respect options from `FZF_DEFAULT_OPTS_FILE`?

### ISSUE THREAD

**Issue by kfernandez31** [Aloxaf/fzf-tab#467]
Hi, I have the following in my `$FZF_DEFAULT_OPTS_FILE`:
```sh
--border=double
--preview-window=border-double
```

And this in my `.zshrc`:
```sh
# -- snip --
zinit light Aloxaf/fzf-tab
zinit snippet OMZP::fzf
zstyle ':fzf-tab:complete:*' fzf-preview " [[ -d \$realpath ]] && eza $(tr -s '\n' ' ' < $EZA_DEFAULT_OPTS_FILE) -1a --color=always --ignore-glob '.DS_Store|.idea|.vscode' \$realpath || bat --style=numbers --color=always \$realpath"
```

The options for `fzf` work just fine with the regular commands such as ctrl+t, shown below:

<img width="844" alt="image" src="https://github.com/user-attachments/assets/708f26bd-2dfa-4d6f-adc5-bf45612bf452">

However, when pressing the tab key, we can see that the preview window's border is different:
<img width="848" alt="image" src="https://github.com/user-attachments/assets/3af91bd0-85cf-434e-8c4d-944c27b5ba4f">

This leaves me with the question - what should I do to make `fzf-tab` respect the options from their configuration file?

Thanks in advance for the response!

**Comment by kfernandez31** [comment]
Turns out you can configure that with `fzf-flags`. I wish this was better documented though, had to crawl dots to get it right:
```sh
# Fzf-tab
zstyle ':completion:*' menu no # don't use zsh's native completion menu
zstyle ':fzf-tab:complete:*' fzf-preview \
   '[[ -d $realpath ]] && { echo "       Directory: \e[1m$(basename "$realpath")\e[0m" && eza $(<$EZA_DEFAULT_OPTS_FILE) -1a --color=always --ignore-glob ".DS_Store|.idea|.vscode" $realpath } || bat --color=always $realpath'
zstyle ':fzf-tab:complete:*' fzf-flags                                                                                 \
    --height=40%                                                                                                       \
    --preview-window=right:60%:wrap:cycle:border-double                                                                \
    --bind="tab:toggle-down"                                                                                           \
    --bind="ctrl-p:change-preview-window(down,90%,wrap,cycle,border-double|hidden|right,50%,wrap,cycle,border-double)" \
    --bind="ctrl-v:execute(bat --paging=always --color=always {+})"

```

**Comment by mauromotion** [comment]
Thanks, I was having the same issue but not only for the border, for the whole custom colors I was using instead. I'm pretty sure something changed (or broke) with a recent update because I'm 100% sure I was getting the right colors and shapes until not too long ago. Well now we fixed it ourselves I guess.

**Comment by poslat-pismo** [comment]
```zsh
zstyle ':fzf-tab:complete:*' fzf-flags --border=none $(xargs <<< $FZF_DEFAULT_OPTS)
```
