### ISSUE TITLE
[BUG] FZF tab completion does not activate on similar file names

### ISSUE THREAD

**Issue by ItzYeho** [Aloxaf/fzf-tab#470]
#### Describe the bug
When trying to complete entries that have the same starting substring, fzf completion will not be triggered, and thus only a regular zsh menu completion is possible. This is unlike [lincheney's solution](https://github.com/lincheney/fzf-tab-completion) which works flawlessly, but lacks features that I need.

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. Create an empty directory, and create in it two files with identical starting names. For instance:
```sh
mkdir test
touch aaae
touch aaad
```
2. Go inside the directory, type `cat` and press <kbd>Tab</kbd>

#### Expected behavior
FZF is opened and I am able to complete what I want.

#### Screenshots
![image](https://github.com/user-attachments/assets/0357b9e2-1dde-4368-a7b3-7407fbc8fc1a)

How it should be:
![image](https://github.com/user-attachments/assets/58e01c75-cbe8-41b8-9476-62c2e4040737)

#### Environment:
 - OS: Arch Linux
 - zsh version: 5.9

#### Minimal zshrc
```zsh
# Completion engine settings
zstyle ':completion:*' completer _oldlist _expand _complete _ignored _match _correct _approximate _prefix
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=** r:|=**' 'l:|=* r:|=*'
zstyle ':completion:*' menu select

# Load completions engine
autoload -Uz compinit
compinit -d ~/.cache/zcompdump
zinit cdreplay -q

# Load FZF-tab
zinit light Aloxaf/fzf-tab
```

#### Log
`Aloxaf/fzf-tab`
![image](https://github.com/user-attachments/assets/fe6c3c13-83fa-4af1-9e9b-2b149824d2f2)

`lincheney/fzf-tab-completion`
![image](https://github.com/user-attachments/assets/35782010-eb07-43bf-a0ba-a053ec2faee5)

`fzf builtin completion`
![image](https://github.com/user-attachments/assets/9ee001b2-6512-48b4-83d0-5265e4dcd20e)

**Comment by Aloxaf** [comment]
Just set `zstyle ':completion:*' menu no`

**Comment by ItzYeho** [comment]
Nope, this does not fix it.

**Comment by Aloxaf** [comment]
Oh, I didn't read the code carefully. You use many custom completers, which may cause bug (eg. https://github.com/Aloxaf/fzf-tab/issues/56).

I tested your configuration and removing `_oldlist` can fix it.

**Comment by ItzYeho** [comment]
That works! But I don't think it's an ideal solution. Ideally fzf-tab should work in all of the default completers offered by zsh. As I've mentioned in the issue, lincheney's solution does indeed manage to hook the _oldlist request.
