### ISSUE TITLE
[Q] Always show fzf-tab even with 1 directory

### ISSUE THREAD

**Issue by kritag** [Aloxaf/fzf-tab#471]
I have aliased `l`to `ls`which in turn is aliased to `eza --icons --group-directories-first`. When I hit <kbd>Tab</kbd> to complete a path I wish to have the fzf-preview completion window show up even if there is only one directory where I run the command from, and not just have that directory automatically pasted to my command line. How can this be achieved?

**Comment by Aloxaf** [comment]
This can't be achieved.
