### ISSUE TITLE
[BUG] ssh+tmux+vnc - menu get displayed in the ssh client

### ISSUE THREAD

**Issue by pbosab** [Aloxaf/fzf-tab#473]
#### Describe the bug
connecting through ssh, launching a vnc session from inside tmux, if I open a terminal in the vnc client the window of fzf-tab get displayed in the tmux session of the ssh client. if I go back to the ssh client and "escape" it, I will get the correct display in the vnc client.

I can make sure:
- [X] I am using the latest version of fzf-tab
- [ ] this is the minimal zshrc which can reproduce this bug
- [X] fzf-tab is loaded after `compinit`
- [X] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [X] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### Screenshots
![Screenshot 2024-09-26 163241](https://github.com/user-attachments/assets/8045517c-4d27-483b-ac0c-d88b391fc09a)

#### Environment:
 - OS: arch
 - zsh version: 5.9

**Comment by Aloxaf** [comment]
It looks like you are using VNC to connect to local machine.

This is not a bug. tmux sets some environment variables when starts up to make sure nested program (eg, tmux -> zsh -> emacs -> zsh) know it's in tmux environment.
If you start a GUI program in tmux, you should unset these variables to prevent the program inside from mistakenly thinking it's still in the tmux.

```shell
TMUX= TMUX_PANE= vnc
```
