### ISSUE TITLE
[Q]How to show dot files/directory (.config, e.g.) with 'ls -al <tab>' (or 'cd <tab>')?

### ISSUE THREAD

**Issue by louis-hsu** [Aloxaf/fzf-tab#476]
1. Initial folder structure:
<img width="748" alt="Screenshot 2024-10-03 at 18 14 24" src="https://github.com/user-attachments/assets/6c9af9d5-c5ed-4bfc-bb74-d919b867f9aa">

2. After type 'ls -al \<tab\>':
<img width="751" alt="Screenshot 2024-10-03 at 18 15 12" src="https://github.com/user-attachments/assets/7db4b3ed-9c82-4e1e-b279-6212ef2dd525">
All dot-files/directories are ignored

3. But type 'ls -al .\<tab\>':
<img width="754" alt="Screenshot 2024-10-03 at 18 16 24" src="https://github.com/user-attachments/assets/b7aab890-e802-4df4-9323-9de696305493">
It shows dot-files/directories specifically

'cd \<tab\>' acts similarly 

Would like to know how to configure 'fzf-tab' so both 'ls -al' and 'cd' can show dot-files/directories directly. Thanks

**Comment by Aloxaf** [comment]
Well, fzf-tab just use results from zsh compsys.

So the real question is: https://unix.stackexchange.com/questions/308315/how-can-i-configure-zsh-completion-to-show-hidden-files-and-folders
