### ISSUE TITLE
[BUG] Behavior of suffix matching changes

### ISSUE THREAD

**Issue by jrwrigh** [Aloxaf/fzf-tab#481]
#### Describe the bug
When trying to tab complete (i.e. fuzzy find) a file by it's suffix, the suffix is auto-added, but then completion stops working.

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
```
$ touch {a,b}_{c,d}.sh
$ ls
 a_c.sh   a_d.sh   b_c.sh   b_d.sh
$ls sh<Tab>
$ls _.sh
 ```
I've tracked down the behavior to #413 
#### Expected behavior
Using commit 02ce77c (right before #413 was added), the following behavior occurs:
![fzf-tab_good](https://github.com/user-attachments/assets/aba6f86c-0d94-48c1-90d4-78b88f1f6cfb)

#### Current Behavior
Using acdc372 (and `master`), I see:
![fzf-tab_bad](https://github.com/user-attachments/assets/dd53594d-70be-47a7-a60d-edde1c04ca67)
I pause about a second between pressing tab above.

Note that it adds the `_` from above. If the files are just named `a.sh b.sh c.sh d.sh`, then this behavior doesn't occur.

#### Environment:
 - OS: Manjaro
 - zsh version: 5.9

#### Log
[zsh-70945-fzf-tab-1.log](https://github.com/user-attachments/files/17513030/zsh-70945-fzf-tab-1.log)

**Comment by Aloxaf** [comment]
This is consistent with the behavior of zsh itself.
If you want to disable this behavior, you can set  `zstyle ':completion:*' menu yes`

**Comment by jrwrigh** [comment]
That command doesn't disable the behavior. I added it to my .zshrc and manually ran the command and it has no effect.

Can confirm that this is consistent with zsh behavior, however dumb it maybe. Maybe it's a bug in upstream? I can't imagine anybody would desire to have that kind of behavior.
