### ISSUE TITLE
Conflict with zdharma/fast-syntax-highlighting

### ISSUE THREAD

**Issue by b0o** [Aloxaf/fzf-tab#53]
fzf-tab doesn't trigger properly on `<tab>` when loaded after the [fast-syntax-highlighting](/zdharma/fast-syntax-highlighting) plugin. Prior to b856498 the plugin worked when loading in either order. 

I traced the issue to the following subset of the change: https://github.com/Aloxaf/fzf-tab/commit/b856498fe21642af5fc33154b39a5b18999759c4#diff-3de94c7df288cd22645487b69fdd019cL358-R363

Reverting that fixes the issue, but I do not completely understand why it was changed in the first place or how to fix it.

**Comment by romkatv** [comment]
It seems like fast-syntax-highlighting either cannot deal with copied widgets or with widgets whose names start with a period. I suggest filing a bug against fast-syntax-highlighting.

**Comment by romkatv** [comment]
> I do not completely understand why it was changed in the first place or how to fix it.

The previous version of the highlighted code was a hack. It was using undocumented implementation details of zsh-autosuggestions. The new code doesn't rely on implementation details of any project.

**Comment by Aloxaf** [comment]
Umm...It's really difficult to deal with widgets...

I have a new idea: hook `_main_complete` to call `_fzf_tab_complete` directly so that I won't suffering from widgets bind hell.

**Comment by Aloxaf** [comment]
> zsh-syntax-highlighting.zsh wraps ZLE widgets. It must be sourced after all custom widgets have been created (i.e., after all zle -N calls and after running compinit). Widgets created later will work, but will not update the syntax highlighting.

I guess you load f-sy-h before call compinit, results in f-sy-h wrap the wrong widget.

**Comment by b0o** [comment]
> I guess you load f-sy-h before call compinit, results in f-sy-h wrap the wrong widget.

Ah, this seems to fix the issue for me. Thank you for looking into this, @Aloxaf!

**Comment by Aloxaf** [comment]
I have added a note to README to tell users load fzf-tab after compinit.

Close if have no question.
