### ISSUE TITLE
file-sort by access/modification time not working

### ISSUE THREAD

**Issue by tastytea** [Aloxaf/fzf-tab#58]
**Version:** commit adcd317370b1dd3853d861c39fbb1b5bdb9c0568 (current git master)

### Setup

``` zsh
autoload -Uz compinit
compinit
antibody bundle Aloxaf/fzf-tab
zstyle ':completion:*' file-sort access
zstyle ':fzf-tab:*' extra-opts '--no-sort'
mkdir a
mkdir c
mkdir b
```

### Problem

Without fzf-tab the output of `ls <TAB>` is sorted by access time (`b c a`), with fzf-tab the output is sorted alphabetically (`a b c`).

**Comment by Aloxaf** [comment]
You can set `sort` tag to false to let fzf-tab respect to the original order.

```zsh
zstyle ':completion:complete:ls:argument-rest' sort false
```

**Comment by tastytea** [comment]
Thanks. Because the `fzf` command is given the argument  `--layout=reverse`, the `file-sort` completion needs to be reversed to get the right order:

``` zsh
zstyle ':completion:*' file-sort access reverse
zstyle ':completion:complete:*:argument-rest' sort false
```

The `fzf` argument `--no-sort` seems to be unnecessary.

**Comment by Aloxaf** [comment]
You can also add `--tac` to `extra-opts` to reverse the list.

**Comment by webmastak** [comment]
As I understand it, you went the way statically calling the plugin sort or nosort? Option switch did not implement?

**Comment by romkatv** [comment]
> As I understand it, you went the way statically calling the plugin sort or nosort?

No. See https://github.com/Aloxaf/fzf-tab/issues/58#issuecomment-597420425.

**Comment by webmastak** [comment]
> > As I understand it, you went the way statically calling the plugin sort or nosort?
> 
> No. See [#58 (comment)](https://github.com/Aloxaf/fzf-tab/issues/58#issuecomment-597420425).

And how it will help me to change sorting on the fly?

**Comment by romkatv** [comment]
> And how it will help me to change sorting on the fly? What I showed in the screenshots.

Wish I knew what you mean. Fortunately you have your fork.

**Comment by webmastak** [comment]
> Wish I knew what you mean. Fortunately you have your fork.
Toggle plugin from sort to nosort when you type something either without modifying the .zshrc file.

**Comment by romkatv** [comment]
@webmastak https://github.com/Aloxaf/fzf-tab/issues/58#issuecomment-597420425 appears to do what you are asking for. If not, you can always use your fork.

**Comment by webmastak** [comment]
> @webmastak [#58 (comment)](https://github.com/Aloxaf/fzf-tab/issues/58#issuecomment-597420425) appears to do what you are asking for. If not, you can always use your fork.

Could you explain in more detail how to implement this?

**Comment by romkatv** [comment]
> Could you explain in more detail how to implement this?

```zsh
function toggle-fzf-tab-sort() {
  if (( _sort_fzf_tab )); then
    zstyle ':fzf-tab:*'    extra-opts '--sort'
    zstyle ':completion:*' sort       'true'
    unset _sort_fzf_tab
  else
    zstyle ':fzf-tab:*'    extra-opts '--no-sort'
    zstyle ':completion:*' sort       'false'
    _sort_fzf_tab=1
  fi
}
zle -N toggle-fzf-tab-sort
bindkey '^T' toggle-fzf-tab-sort
```

**Comment by webmastak** [comment]
Thanks, I'll try.

**Comment by webmastak** [comment]
After comparing the version of the plugin which is in [my fork](https://github.com/webmastak/fzf-tab) and the current one. I noticed that when sorting is disabled, the results are different and the plugin in my fork shows better.  Can I fix it somehow?

Current plugin:
![https://i.imgur.com/1pndRPW.png](https://i.imgur.com/1pndRPW.png)

My fork:
![https://i.imgur.com/xsUCaQS.png](https://i.imgur.com/xsUCaQS.png)

**Comment by romkatv** [comment]
@webmastak Your fork has diverged too much. It's a lot of work go through all the changes, guess what config you are using, just to answer your question. If you ask better questions, you'll get better answers.

**Comment by webmastak** [comment]
> @webmastak Your fork has diverged too much.

I understand this, but there is a general template by which the results are displayed.
Which block of code in the plugin is responsible for sorting the results?

**Comment by Aloxaf** [comment]
@webmastak It's a bug. I introduced GNU sort in https://github.com/Aloxaf/fzf-tab/commit/d7ed42b475cff69e62e641b456672b536ac2cacb and it seems always doesn't work as I expect...
I give it a simple fix in f0627fe580532466b4b3b4595b70b9dc87a5dc89, before I find the right way to use GNU sort.

**Comment by webmastak** [comment]
Thanks a lot.  Your plugin is the best. :+1:

**Comment by mxmilkiib** [comment]
I'd like to get the list sorted this way, but I'm not seeing an effect after [adding](https://github.com/mxmilkiib/dotfiles/blob/master/zsh/.zshrc#L198) the suggested config. Might I be misunderstanding what is required or the order? I have tried commenting my own completions.zsh and even the junegunn/fzf parts, but files are still being ordered alphabetically.

**Comment by Aloxaf** [comment]
@mxmilkiib You should also specify the file sort: `zstyle ':completion:*' file-sort access`

And make sure you're using `ls` not something like `exa`.

**Comment by mxmilkiib** [comment]
Thanks, whoopy, I realise I somehow broke that link, the `file-sort access` bit was on 191.

I was looking for `file-sort modification` anyway.

From this modification order;
![image](https://user-images.githubusercontent.com/108225/97606051-42a2f080-1a07-11eb-93ea-d9244642e0c5.png)

(and this access order 
![image](https://user-images.githubusercontent.com/108225/97606549-d1177200-1a07-11eb-9b0f-0437fedd0eb7.png))


Without fzf-tab, and with `file-sort modification` I get;

![image](https://user-images.githubusercontent.com/108225/97605103-2783b100-1a06-11eb-9e02-21d74b707577.png)

Without fzf-tab, and with `file-sort access`;

![image](https://user-images.githubusercontent.com/108225/97605252-53069b80-1a06-11eb-8b4c-2d55431f41b4.png)

With fzf-tab, and with either of the sort, I get;

![image](https://user-images.githubusercontent.com/108225/97605469-9103bf80-1a06-11eb-9f44-3a11ce3b0913.png)

**Comment by Aloxaf** [comment]
@mxmilkiib 

`zstyle ':completion:complete:ls:argument-rest' sort false` only disable sorting for `ls`. You should use `zstyle ':completion:complete:*:argument-rest' sort false` if you want to disable it for every commands.
