### ISSUE TITLE
bad option: -c errors

### ISSUE THREAD

**Issue by ahmedelgabri** [Aloxaf/fzf-tab#59]
After this commit https://github.com/Aloxaf/fzf-tab/commit/adcd317370b1dd3853d861c39fbb1b5bdb9c0568, I'm getting these errors 

```
enable-fzf-tab:functions:36: bad option: -c
enable-fzf-tab:functions:39: bad option: -c
enable-fzf-tab:functions:46: bad option: -c
```

**Comment by blaenk** [comment]
I tried this plugin for the first time earlier today and was getting these errors and wasn't sure if it was my setup or what. Thankfully I refreshed the issues and saw that you created this.

I can confirm that 56adfa43b6cab964249c740302c8b57d129201f0 works so I'll pin to that and subscribe to this issue to hear of a future fix.

**Comment by Aloxaf** [comment]
`functions -c` may only work on the newer version of zsh. I will fall back to use `$functions`.

**Comment by Aloxaf** [comment]
Does it work now?

**Comment by blaenk** [comment]
Yes, thanks.

**Comment by ahmedelgabri** [comment]
> `functions -c` may only work on the newer version of zsh. I will fall back to use `$functions`.

FYI, I do have the latest version of `zsh` `zsh 5.8 (x86_64-apple-darwin19.3.0)`

Thanks for the fix anyway @Aloxaf

**Comment by Aloxaf** [comment]
Fix another bug: https://github.com/Aloxaf/fzf-tab/commit/3acebec6578eb0bdaac9335000c29c9ec0e9c2f3

macOS's zsh is strange....
