### ISSUE TITLE
Completion in a brace-expansion context does not seem correct

### ISSUE THREAD

**Issue by relastle** [Aloxaf/fzf-tab#6]
Hi, this project is absolutely fantastic. I'm so impressed. 😄 

I'm just wondering brace expansion using `fzf-tab` seems not perfect.

![out](https://user-images.githubusercontent.com/6816040/71558136-163ee080-2a93-11ea-9681-348c31e548cc.gif)

As shown in the GIF above, although completion source is correct, a resulting buffer after accepting the completion is not correct.

I think correct resulting buffer will be 

```zsh
ls ./fzf-tab/{.gitignore
```

Thank you for the cool project, again.

**Comment by Aloxaf** [comment]
I'm glad this plugin can help you.

The bug has been detected, thanks for your report!

**Comment by Aloxaf** [comment]
There doesn't seem to be a simple way to detect whether it is in a brace-expansion context: no API and the related [code](https://github.com/zsh-users/zsh/blob/4a2a15d8dc8d310d537ababc2abba0fe444276a8/Src/Zle/zle_tricky.c#L1081) is a "nightmare".
I did a simple fix to make sure the result won't be too strange. To completely fix it, AFAIK, I might have to write a binary module to get the inner state.

**Comment by relastle** [comment]
Thank you for the quick response.

Currently, this pattern is a rare case that can not be handled correctly, as far as I have been using "fzf-tab". Except for it, fzf-tab can deal with almost all cases by just a light-weighted single script, which is so surprising.

I hope you keep this great work.
