### ISSUE TITLE
Shift+Tab toggles result entries but Tab does not

### ISSUE THREAD

**Issue by levito** [Aloxaf/fzf-tab#60]
**Describe the bug**
When results are shown, <kbd>Tab</kbd> goes down and does not toggle (fzf-tab default configuration), but <kbd>Shift+Tab</kbd> goes up and also toggles a result entry (fzf default).

**To Reproduce**
1. Type 'ls'
2. Press <kbd>Tab</kbd><kbd>Tab</kbd><kbd>Shift+Tab</kbd>
3. See error

**Expected behavior**
Either <kbd>Tab</kbd> should toggle and go down and <kbd>Shift+Tab</kbd> and go up, or <kbd>Tab</kbd> and <kbd>Shift+Tab</kbd> should just go down and up

**Environment (please complete the following information):**
 - OS: macOS 10.14.6
 - zsh version  5.7.1
 - fzf-tab version https://github.com/Aloxaf/fzf-tab/commit/00effd94fa46c244a2825efe5d84cda64957a31f

**zshrc**
https://github.com/levito/dotfiles/blob/master/.zshrc#L44

**Comment by Aloxaf** [comment]
Fixed. Thanks for your report.

**Comment by danihodovic** [comment]
thanks @Aloxaf !
