### ISSUE TITLE
[BUG] _fzf_tab__main_complete:95: permission denied

### ISSUE THREAD

**Issue by kdeldycke** [Aloxaf/fzf-tab#61]
Hi! I'm just trying out `fzf-tab` and it seems like a great addition to Zsh!

But when I write `cd dot` then press <kbd>tab</kbd>, I get these errors:
```
╭─    ~ ······················································ ✔  18:40:59  
╰─ cd dot_fzf_tab__main_complete:44: command not found: _setup
_fzf_tab__main_complete:95: permission denied: 
_fzf_tab__main_complete:134: command not found: _complete
_fzf_tab__main_complete:134: command not found: _ignored
❯ cd dot
```

I'm currently running this on macOS Caralina, with latest `zsh`, `fzf` and `fd` packages installed from `brew`.

All Zsh plugin are managed by `zinit` with the following configuration:
```
export FZF_DEFAULT_COMMAND="fd --type f --hidden . $HOME"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type d --hidden --exclude .git . $HOME"
zinit light Aloxaf/fzf-tab

zinit light zsh-users/zsh-completions

zinit light zdharma/fast-syntax-highlighting

ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_USE_ASYNC=1
#ZSH_AUTOSUGGEST_MANUAL_REBIND=1
zinit light zsh-users/zsh-autosuggestions

zinit light zdharma/zsh-diff-so-fancy

zinit ice depth=1; zinit light romkatv/powerlevel10k
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

The code above is an excerpt of my dotfiles, available at: https://github.com/kdeldycke/dotfiles/blob/master/dotfiles/.zshrc#L123-L144

**Comment by Aloxaf** [comment]
You haven't setup compsys.

As a zinit user, you can put `zicompinit; zicdreplay` below the line that loads zsh-completions, and also let fzf-tab load just after compsys has setup.

An example: https://github.com/Aloxaf/dotfiles/blob/master/zsh/.config/zsh/zshrc.zsh#L114-L120

**Comment by kdeldycke** [comment]
Ooooh. That's perfect! Thanks a lot for you help! 😃
