### ISSUE TITLE
[BUG] Git completion gets deleted

### ISSUE THREAD

**Issue by gbrlsnchs** [Aloxaf/fzf-tab#63]
**Describe the bug**
When I type the first path segment of a directory as an argument for a Git command, the path gets deleted from prompt.

**To Reproduce**
1. Create a testing directory
2. `cd` into that directory and initialize a Git repo with `git init`
3. `mkdir foo`
4. `touch foo/bar`
5. Type `git add foo`
6. Press <kbd>Tab</kbd>
7. See error: `foo` gets deleted and the cursor goes back one step

This always happens when you type the exact name of the directory. If you type only part of it, you get the right completion. If you put the final slash after `foo`, it also works as expected.

**Expected behavior**
It should complete with a slash in order to allow subsequent completions.

**Screenshots**
I made an asciicast of the problem:
[![asciicast](https://asciinema.org/a/wDgNQm8oqbrfqA4Bm7IVhhoKy.svg)](https://asciinema.org/a/wDgNQm8oqbrfqA4Bm7IVhhoKy)

**Environment (please complete the following information):**
 - OS: Void Linux
 - zsh version: `zsh 5.8 (x86_64-unknown-linux-gnu)`
 - fzf-tab version: https://github.com/Aloxaf/fzf-tab/commit/f0627fe580532466b4b3b4595b70b9dc87a5dc89

**zshrc**
```zshrc
prompt_cmd() {
  eval "$PROMPT_COMMAND"
}

precmd_functions=(prompt_cmd)

source /usr/share/google-cloud-sdk/completion.zsh.inc
source $XDG_DATA_HOME/antigen/antigen.zsh

antigen use oh-my-zsh
antigen bundle git
antigen bundle vi-mode
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle Aloxaf/fzf-tab
antigen theme lambda
antigen apply

source /usr/share/doc/fzf/completion.zsh
source /usr/share/doc/fzf/key-bindings.zsh

_gen_fzf_default_opts() {
    local gruvbox_bg0='#282828'
    local gruvbox_bg1='#3c3836'
    local gruvbox_bg3='#665c54'
    local gruvbox_red='#cc241d'
    local gruvbox_green='#98971a'
    local gruvbox_yellow='#d79921'
    local gruvbox_blue='#458588'
    local gruvbox_purple='#b16286'
    local gruvbox_aqua='#689d6a'
    local gruvbox_gray='#a89984'
    local gruvbox_gray_alt='#928374'
    local gruvbox_red_alt='#fb4934'
    local gruvbox_green_alt='#b8bb26'
    local gruvbox_yellow_alt='#fabd2f'
    local gruvbox_blue_alt='#83a598'
    local gruvbox_purple_alt='#d3869b'
    local gruvbox_aqua_alt='#8ec07c'
    local gruvbox_orange='#d65d0e'
    local gruvbox_fg1='#ebdbb2'
    local gruvbox_fg4='#a89984'

    export FZF_DEFAULT_OPTS="
      --color=bg+:$gruvbox_bg1,bg:$gruvbox_bg0,spinner:$gruvbox_yellow,hl:$gruvbox_yellow
      --color=fg:$gruvbox_fg1,header:$gruvbox_bg3,info:$gruvbox_blue,pointer:$gruvbox_blue
      --color=marker:$gruvbox_orange,fg+:$gruvbox_fg1,prompt:$gruvbox_fg4,hl+:$gruvbox_yellow
    "

    export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --glob '!.git'"
}

_gen_fzf_default_opts
```

**Comment by Aloxaf** [comment]
Thanks for your report!
Fixed. Please update fzf-tab and try again.

**Comment by gbrlsnchs** [comment]
That was fast, thank you very much, it's working now! :heart:
