### ISSUE TITLE
[BUG] Ctrl+j can't use to select the next completion.

### ISSUE THREAD

**Issue by roachsinai** [Aloxaf/fzf-tab#66]
Hi, it's first time to use fzf-tab, it's great!!! But, I got a bug.

**Describe the bug**

When I echo someting to fzf, I can use <c-j> and <c-k>  to select the entry I want. But <c-j> not work for fzf-tab, but <c-k> works well. Check the gif below, I firstly show <c-k> works, then <c-j> failed.

![Ctrl ij](https://user-images.githubusercontent.com/9500049/77317567-67830700-6d46-11ea-9e96-bcbf5432fb9c.gif)

**To Reproduce**
1. Type `vim `
2. Press <kbd>Tab</kbd>
4. Use <c-j> to select entry.

**Expected behavior**

<c-j> choose the next entry, not accep the current entry.

**Details**

```
hmank ~/c/G/dotfiles master » bindkey '^j'                       
"^J" history-substring-search-down
hmank ~/c/G/dotfiles master » bindkey '^k'
"^K" history-substring-search-up
```
Not sure, but the defalt vi-mode, <c-j> seems to `accept line`, but I have remap it to `history-substring-search-down`.

**Environment (please complete the following information):**
 - OS: Manjaro
 - zsh version: zsh 5.8 (x86_64-pc-linux-gnu)
 - fzf-tab version: https://github.com/Aloxaf/fzf-tab/commit/dc909ab196f291a27cf2d056288f785c32794ea2

**zshrc**

```
# vim mode
bindkey -v

# allow ctrl-h, ctrl-w, ctrl-? for char and word deletion (standard behaviour)
bindkey '^?' backward-delete-char
bindkey '^x' backward-delete-char
bindkey '^l' vi-forward-char
bindkey '^h' vi-backward-char
bindkey '^f' vi-forward-word
bindkey '^b' vi-backward-word
bindkey '^k' history-substring-search-up
bindkey '^j' history-substring-search-down
bindkey '^d' backward-kill-word

bindkey '^ ' autosuggest-execute

# allow ctrl-a and ctrl-e to move to beginning/end of line
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line
# bindkey "${terminfo[khome]}" beginning-of-line
# bindkey "${terminfo[kend]}" end-of-line
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
# https://superuser.com/a/1079579/913345
# Search backwards and forwards with a pattern, -M setting mode
bindkey -M vicmd '/' history-incremental-pattern-search-backward
bindkey -M vicmd '?' history-incremental-pattern-search-forward
# set up for insert mode too
bindkey -M viins '^R' history-incremental-pattern-search-backward
# S: search
bindkey -M viins '^S' history-incremental-pattern-search-forward

# vi-mode, fzf and fzf-tab must in order:
# fzf remap ^T, ^I of vi-mode
# fzf-tab remap fzf ^T
# https://github.com/junegunn/fzf/wiki/Configuring-fuzzy-completion#caveats
source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh
export FZF_COMPLETION_TRIGGER=''
bindkey '^T' fzf-completion
bindkey '^I' $fzf_default_completion

source $HOME/.zshrc.d/plugins/fzf-tab/fzf-tab.plugin.zsh
bindkey '^T' toggle-fzf-tab
```

**Comment by Aloxaf** [comment]
Ah, sorry.
As an emacs user. I make fzf use emacs keybindings (C-n/p for navigating and C-j for accepting). This seems to confuse vim users. I have removed it to use fzf's default keybindings.

BTW. You can use `command` tag to change fzf's commandline arguments: https://github.com/Aloxaf/fzf-tab/blob/master/README_CN.md#command

**Comment by roachsinai** [comment]
Thanks a lot!
