### ISSUE TITLE
[BUG] Preview for cd not working

### ISSUE THREAD

**Issue by jandamm** [Aloxaf/fzf-tab#71]
**Describe the bug**
I'm trying to use your example in the README.md to preview a folder with exa when using cd.
```zsh
# give a preview of directory by exa when completing cd
zstyle ':fzf-tab:complete:cd:*' extra-opts --preview=$extract'exa -1 --color=always ${~ctxt[hpre]}$in'
```
Then I'm just seeing what exa without a path shows. (Current dir)

I also changed it to the following:
```zsh
# give a preview of directory by exa when completing cd
zstyle ':fzf-tab:complete:cd:*' extra-opts --preview=$extract'echo hi${~ctxt[hpre]}$in'
```
Then I just see `hi` in the preview. So the path is just not expanded.

**To Reproduce**
1. Type 'cd'
2. Press <kbd>Tab</kbd>

**Expected behavior**
I would expect to see `exa $completion_path` instead of `exa`

**Environment (please complete the following information):**
 - OS: macOS 10.15.4
 - zsh version 5.8 (x86_64-apple-darwin19.3.0)
 - fzf-tab version [e.g. https://github.com/Aloxaf/fzf-tab/commit/47ed49e72161aee919eeec3491fe57ad5040ead9]

**zshrc**
https://github.com/jandamm/dotfiles/blob/master/zsh/init.zsh
https://github.com/jandamm/dotfiles/blob/master/zsh/after/fzf-tab.zsh

**Comment by jakubfijalkowski** [comment]
I think this might be the same case as in [this issue](https://github.com/Aloxaf/fzf-tab/issues/69). Did you forget about defining `extract` variable?

**Comment by jandamm** [comment]
Of course I did 🙈 
I just skipped these lines as it said "experimental". I wasn't aware the following lines depend on it.

Thanks for the help 👍

**Comment by Aloxaf** [comment]
I will make it more clear :laughing:
