### ISSUE TITLE
nvim -t infinite loop

### ISSUE THREAD

**Issue by MenkeTechnologies** [Aloxaf/fzf-tab#72]
**Describe the bug**
nvim -t <tab> leads to infinite loop of
_tags:comptags:36: nesting level too deep
_tags:comptags:60: nesting level too deep
_tags:comptags:67: nesting level too deep

**To Reproduce**
1. Type 'nvim -t '
2. Press <kbd>Tab</kbd>

**Expected behavior**
tags will be in menucompletioon

**Screenshots**
<img width="279" alt="Screen Shot 2020-04-05 at 12 47 29 AM" src="https://user-images.githubusercontent.com/18195247/78467087-1294a880-76d7-11ea-98aa-1acf23c94c40.png">

**Environment (please complete the following information):**
 - OS: macoS
 - zsh version 5.8
 - fzf-tab version [e.g. https://github.com/Aloxaf/fzf-tab/commit/56adfa43b6cab964249c740302c8b57d129201f0]

**zshrc**
If applicable, add a minimal zshrc to help us analyze.

**Comment by Aloxaf** [comment]
I can't reproduce this. Can you provide your zshrc?

Does `vim -t` have the same problem?

**Comment by MenkeTechnologies** [comment]
good to know its on my end.  my zshrc is a little crazy.  i have a framework called zpwr and incorporated fzf-tab as a plugin.

https://raw.githubusercontent.com/MenkeTechnologies/zpwr/master/install/.zshrcv

**Comment by Aloxaf** [comment]
That's really crazy and hard to debug.

Can you run the code below and then try to reproduce the bug and then provide the output of /tmp/fzf-tab-debug.txt?

```zsh
select-first() {
  read input
  echo $input
}

zstyle ':fzf-tab:*' command select-first

fzf-tab-debug() {
  local -i debug_fd=1
  exec {debug_fd}>&2 2>|/tmp/fzf-tab-debug.txt
  setopt xtrace
  local -i _fzf_tab_continue=1
  while (( _fzf_tab_continue )); do
    _fzf_tab_continue=0
    IN_FZF_TAB=1
    {
      zle .fzf-tab-orig-$_fzf_tab_orig_widget
    } always {
      IN_FZF_TAB=0
    }
    zle redisplay
  done
  unsetopt xtrace
}
zle -N fzf-tab-debug
bindkey "^I" fzf-tab-debug
```

**Comment by NightMachinary** [comment]
I can't reproduce this with `nvim -t` either.

**Comment by jingzi28** [comment]
I have the same problem, after reading some guidance, it seems the there are too much data and got overflow, what I did is simply closed all the open tabs, and reopen a zsh terminal, that problem is gone.
