### ISSUE TITLE
[FR] Ignore headers if only one group

### ISSUE THREAD

**Issue by mitinarseny** [Aloxaf/fzf-tab#74]
Firstly, let me thank you for developing such a nice plugin!

I have following lines in my `~/.zshrc`:
```sh
FZF_TAB_COMMAND=(
    fzf
    --ansi   # Enable ANSI color support, necessary for showing groups
    --expect='$continuous_trigger' # For continuous completion
    --nth=2,3 --delimiter='\x00'  # Don't search prefix
    --layout=reverse --height='${FZF_TMUX_HEIGHT:=30%}' --min-height=12
    --tiebreak=begin -m --bind=tab:down,btab:up,change:top,ctrl-space:toggle --cycle
    '--query=$query'   # $query will be expanded to query string at runtime.
    '--header-lines=$#headers' # $#headers will be expanded to lines of headers at runtime
)
zstyle ':fzf-tab:*' command $FZF_TAB_COMMAND
```
It would be nice to disable headers at all when there is only one group as it seems to me as a waste of space. So, in the following example there should be no line `-- local directory --`:
![image](https://user-images.githubusercontent.com/10659110/78997970-557bd380-7b50-11ea-9229-c5aba8de2c3e.png)

**Comment by Aloxaf** [comment]
> Firstly, let me thank you for developing such a nice plugin!
Thanks!


> It would be nice to disable headers at all when there is only one group as it seems to me as a waste of space.

You can use `single-group` tag to control what will be shown when there is only one group:
```zsh
zstyle ':fzf-tab:*' single-group 'color'
```
