### ISSUE TITLE
[BUG] slash isn't shown when completing cd directories with '..' and env variables

### ISSUE THREAD

**Issue by mitinarseny** [Aloxaf/fzf-tab#75]
**Describe the bug**
When using fzf-tab and trying to complete directories with current typed path already contains `..` or some env vars, fzf-tab does not show trailing slash after directory names:
![image](https://user-images.githubusercontent.com/10659110/79077327-7f2c2a80-7d09-11ea-89fb-efc18230cbbd.png)
![image](https://user-images.githubusercontent.com/10659110/79077340-90753700-7d09-11ea-9f1a-a60851c50017.png)
But built-in completion does it:
![image](https://user-images.githubusercontent.com/10659110/79077360-c4e8f300-7d09-11ea-8f0d-c80d2e446f52.png)
![image](https://user-images.githubusercontent.com/10659110/79077378-dcc07700-7d09-11ea-80f1-115464f9cb16.png)

**Environment:**
 - OS: `macOS`
 - zsh version: `zsh 5.8 (x86_64-apple-darwin19.3.0)`
 - fzf-tab version: https://github.com/Aloxaf/fzf-tab/tree/fca05e66d1c397cb5e72e8b185b1c3d1a0fc063d

**zshrc**
```zsh
command -v fzf > /dev/null || disable-fzf-tab
FZF_TAB_COMMAND=(
    fzf
    --ansi   # Enable ANSI color support, necessary for showing groups
    --expect='$continuous_trigger' # For continuous completion
    --nth=2,3 --delimiter='\x00'  # Don't search prefix
    # '--color=hl:$(( $#headers == 0 ? 108 : 255 ))'
    --layout=reverse --height='${FZF_TMUX_HEIGHT:=30%}' --min-height=12
    --tiebreak=begin -m --bind=tab:down,btab:up,change:top,ctrl-space:toggle --cycle
    '--query=$query'   # $query will be expanded to query string at runtime.
    '--header-lines=$#headers' # $#headers will be expanded to lines of headers at runtime
)
zstyle ':fzf-tab:*' command $FZF_TAB_COMMAND
zstyle ':fzf-tab:*' insert-space false

# white color is there is no group
zstyle ':fzf-tab:*' $'\033[37m'

# do not show groups if only one available
zstyle ':fzf-tab:*' single-group ''
```

**Comment by Aloxaf** [comment]
Thanks for your report.

Please update and try again.
