### ISSUE TITLE
[FR] 补全排序

### ISSUE THREAD

**Issue by ficapy** [Aloxaf/fzf-tab#76]
能否参考一下bash_history/zsh_history的输入历史，对补全结果进行排序
比如我执行git checkout TAB，我极有可能想输入的是我最近输入过的分支

**Comment by ficapy** [comment]
又想了一下，其实这种场景可能直接使用fzf插件更好，对于历史输入过的命令。即使输入了git checkout。这个时候可以直接用fzf  CTRL+R。它会参照最近输入过的命令提供选择
fzf-tab 对没有输入过的命令进行补全还是很好的
我关闭该issue了

**Comment by Aloxaf** [comment]
可以试一下 https://github.com/zsh-users/zsh-autosuggestions

**Comment by ficapy** [comment]
zsh-autosuggestions这个我也装了，但是只能提供最近的一个
提供更多历史结果还是fzf更方便
