### ISSUE TITLE
[BUG] Preview shows error.

### ISSUE THREAD

**Issue by mmqmzk** [Aloxaf/fzf-tab#77]
**Describe the bug**
Preview shows `fork/exec /usr/bin/zsh: invalid argument`, even if disable preview in by adding `--no-preview` in `FZF_TAB_OPTS`.

**To Reproduce**
1. Type 'ls '
2. Press <kbd>Tab</kbd>

**Expected behavior**
The preview shows correctly or can be disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/2217694/80276201-93b0ef80-8719-11ea-8049-8428a7fdecf2.png)

**Environment (please complete the following information):**
 - OS: 
    1. Ubuntu 20.04 Windows subsystem for Linux
	2. ubuntu 19.10
 - zsh version 
	1. 5.8 (wsl)
	2. 5.7.1 (ubuntu 19.10)
 - fzf-tab version current HEAD

**zshrc**

```bash
export PREVIEW="$HOME/zfuncs/preview.zsh"

export FZF_TAB_OPTS=(-1 --cycle --inline-info --ansi --height 40% \
	--border --layout=reverse  --expect=/ --no-preview)

 export FZF_TAB_OPTS=(-1 --cycle --inline-info --ansi --height 40% \
	--border --layout=reverse  --expect=/ --priview '$PREVIEWE {}')

# Both two above show preview error, the preview.zsh file is my custom preview script and has the right permissions.
```

This is fzf opts, which works well in other situations.

```bash
export FZF_DEFAULT_OPTS="--multi --cycle --inline-info --ansi --height 100% \
   --border --layout=default --preview '$PREVIEW {}' --preview-window \
   'right:70%:wrap' $FZF_PREVIEW_KEY_BIND"

 export FZF_COMPLETION_OPTS="-1 --cycle --inline-info --ansi --height 60% \
   --border --layout=reverse --preview '$PREVIEW {}' --preview-window \
   'right:70%:wrap'  $FZF_PREVIEW_KEY_BIND"
```

**Comment by Aloxaf** [comment]
You should trim the input of `--preview` because it contains some non-printable characters.

```zsh
local extract="
# trim input(what you select)
local in=\${\${\"\$(<{f})\"%\$'\0'*}#*\$'\0'}
"
FZF_TAB_OPTS=(-1 --cycle --inline-info --ansi --height 40% \
	--border --layout=reverse  --expect=/ --priview '$extract;$PREVIEWE {}')
```

**Comment by mmqmzk** [comment]
Thanks for the reply.
I tried the config above. It seems not to work.
I also tried to change the quoting,

```bash
local extract="local in=\"\${\${\"\$(<{f})\"%\$'\0'*}#*\$'\0'}\""
export FZF_TAB_OPTS=(-1 --cycle --inline-info --ansi --height 40% \
  --border --layout=reverse  --expect=/ --priview "'$extract;$HOME/preivew.zsh \"$in\"'")
```

![image](https://user-images.githubusercontent.com/2217694/80494955-dbde4500-8999-11ea-8ffa-2f8faaf58251.png)


The preview script can be simplified like [this](https://gist.github.com/mmqmzk/da63e780913db7baf09342d66c83cee8/raw/preview.zsh):
```bash
#!/usr/bin/env zsh
[[ -e "$1" ]] && file "$1" && exit 0
echo "$1"
```

Always the same error as I mentioned.

**Comment by Aloxaf** [comment]
How about this then:

```zsh
local extract="
# trim input
local in=\${\${\"\$(<{f})\"%\$'\0'*}#*\$'\0'}
# get ctxt for current completion
local -A ctxt=(\"\${(@ps:\2:)CTXT}\")
# real path
local realpath=\${ctxt[IPREFIX]}\${ctxt[hpre]}\$in
realpath=\${(Qe)~realpath}
"
zstyle ':fzf-tab:*' extra-opts --preview=$extract'/tmp/preview.zsh $realpath'
```

**Comment by mmqmzk** [comment]
Never mind, I tried using zstyle, and it works.

```bash
zstyle ':fzf-tab:complete:*:*' extra-opts --preview=$extract";$PREVIEW \$in"
```

Thanks again.

**Comment by Aloxaf** [comment]
BTW I suggest using `$realpath`  (

**Comment by RusticBard** [comment]
> Never mind, I tried using zstyle, and it works.
> 
> ```shell
> zstyle ':fzf-tab:complete:*:*' extra-opts --preview=$extract";$PREVIEW \$in"
> ```
> 
> Thanks again.

can you tell me what should I add to my zshrc to make the preview work? thanks in advance :)
