### ISSUE TITLE
[BUG] Error msg "scalar parameter IN_FZF_TAB created globally in function fzf-tab-complete"

### ISSUE THREAD

**Issue by rjcoelho** [Aloxaf/fzf-tab#80]
**Describe the bug**
Error message is displayed on the first time only. Everything else works

**To Reproduce**
1. Type 'ssh'
2. Press <kbd>Tab</kbd>
fzf-tab-complete:5: scalar parameter IN_FZF_TAB created globally in function fzf-tab-complete

**Expected behavior**
No error msg

**Environment (please complete the following information):**
 - OS: Darwin
 - zsh version zsh 5.8 (x86_64-apple-darwin18.7.0)
 - fzf-tab version [e.g. https://github.com/Aloxaf/fzf-tab/commit/56adfa43b6cab964249c740302c8b57d129201f0]

**zshrc**
If applicable, add a minimal zshrc to help us analyze.

**Comment by Aloxaf** [comment]
You might have set `warn_create_global`.
Please update and try again.
