### ISSUE TITLE
[BUG] Groups show "%B" and "%b" instead of "[" and "]"

### ISSUE THREAD

**Issue by pcattori** [Aloxaf/fzf-tab#81]
**Describe the bug**
Instead of:

```
[alias] [main porcelain command] [plumbing internal helper command]
```

`fzf-tab` shows:

```
%Balias%b %Bmain porcelain command%b %Bplumbing internal helper command%b
```

**To Reproduce**
1. Type 'git st'
2. Press <kbd>Tab</kbd>

**Expected behavior**
 The `%B` and `%b` tokens should not be shown. `[` and `]` should be shown instead.

**Screenshots**

![Screen Shot 2020-05-08 at 10 36 29 AM](https://user-images.githubusercontent.com/1477317/81416800-3bfe8500-9118-11ea-9468-3fc33c5938b0.png)

**Environment (please complete the following information):**
 - OS: MacOS 10.15.4
 - zsh version: zsh 5.7.1 (x86_64-apple-darwin19.0)
 - fzf-tab version https://github.com/Aloxaf/fzf-tab/commit/607a28b8950a152e3e799799c45c1110d10e680f

**zshrc**
If applicable, add a minimal zshrc to help us analyze.

**Comment by Aloxaf** [comment]
Please add this line to zshrc and try again:
```zsh
zstyle ':completion:*:descriptions' format '[%d]'
```

**Comment by pcattori** [comment]
@Aloxaf Thanks that fixed it! Is this something that should work out-of-the-box without configuration?

**Comment by Aloxaf** [comment]
No, it depends on how you set descriptions format, which is empty by default.
