### ISSUE TITLE
[BUG] Does not work on zsh 5.1.1

### ISSUE THREAD

**Issue by commiyou** [Aloxaf/fzf-tab#82]
1. docker run -it -v fzf-tab:/fzf-tab -v fzf-bin:/usr/local/sbin zshusers/zsh:5.1.1 zsh
2. autoload -U compinit promptinit; compinit; source /fzf-tab/fzf-tab.plugin.zsh
3. ls <keyboard>tab</keyboard>

**Comment by romkatv** [comment]
Personal advice: don't support old zsh versions. They are a drag. Set minimum supported version either at 5.7.1 or 5.4.2.

**Comment by commiyou** [comment]
solved by [zsh-bin](https://github.com/romkatv/zsh-bin)
