### ISSUE TITLE
[BUG] Backslash is added automatically to directory names

### ISSUE THREAD

**Issue by n0ibe** [Aloxaf/fzf-tab#83]
A backspace character seems to be added automatically to directory names, even if it's not there in the default completion:

Default completion menu, no backslash
![portion_2020:05:10@02:19:06](https://user-images.githubusercontent.com/59321248/81488103-a7556d80-9264-11ea-97de-d040638502a1.png)

Fzf completion menu, backslash is added
![portion_2020:05:10@02:16:28](https://user-images.githubusercontent.com/59321248/81488109-bf2cf180-9264-11ea-98f0-59e6fc1aa847.png)

how can I get rid of that?

**Comment by Aloxaf** [comment]
That's strange.

Here is my test result:
![图片](https://user-images.githubusercontent.com/17017672/81627846-ac1b4c80-9431-11ea-8c5c-443886433fee.png)

Can you provide your zshrc?

**Comment by nhooyr** [comment]
Can confirm I see slashes.

I believe there is a zle option to disable/enable file type indicators.

**Comment by Aloxaf** [comment]
@nhooyr You can use `setopt no_list_types` to turn off it now.

**Comment by nhooyr** [comment]
Awesome!
