### ISSUE TITLE
[BUG] No headers

### ISSUE THREAD

**Issue by webmastak** [Aloxaf/fzf-tab#84]
**Describe the bug**
The code has:
```
...
'--header-lines=$#headers' # $#headers will be expanded to lines of headers at runtime
...
```
Where is said - **headers will be expanded to lines of headers at runtime**

But the screenshot shows that they are not there:
![https://i.imgur.com/rx5MDAc.png](https://i.imgur.com/rx5MDAc.png)

When docker prints headers:
![https://i.imgur.com/YZ2VNyF.png](https://i.imgur.com/YZ2VNyF.png)

**Comment by Aloxaf** [comment]
This is group description. You should enable it manually by `zstyle ':completion:*:descriptions' format '[%d]'`

**Comment by webmastak** [comment]
Thanks It works. :)

Another question - how to configure how many groups will be shown? For example, for docker.

There are two of them in the screenshot, for example, only need a group of [repositories] that is highlighted in green.
![https://i.imgur.com/8sHtlWu.png](https://i.imgur.com/8sHtlWu.png)
