### ISSUE TITLE
[BUG] per command  extra-opts  doesn't work as espected

### ISSUE THREAD

**Issue by ensarman** [Aloxaf/fzf-tab#85]
**Describe the bug**
I have configured zstyle extra-opts as you describe in the README.md but I'm not able to make it work :(  

```
zstyle ':fzf-tab:complete:cd:*' extra-opts '--preview="ls --color=always -CXQ {}" --preview-window=up:30%'
```
i've tried with 

```
zstyle ':fzf-tab:complete:_cd:*' extra-opts '--preview="ls --color=always -CXQ {}" --preview-window=up:30%'
```
and that doesn't work at all 

**To Reproduce**
1. Type 'cd '
2. Press <kbd>Tab</kbd>

**Expected behavior**
- It supposed we have to see the preview of the contents of the folder
- the preview must be in the top but it is not a problem, it could be in the actual place 

**Screenshots**
![image](https://user-images.githubusercontent.com/9279265/82136899-60252a80-97d8-11ea-9e0d-51278bee0edb.png)

**Environment (please complete the following information):**
 - OS: archlinux
 - zsh vesion 5.8
 - fzf-tab version https://github.com/Aloxaf/fzf-tab/commit/f3809cc1517fb366e70a9285ae78309baed5c7af

**zshrc**
https://pastebin.com/dgJua23Q

the ~/.oh-my-zsh/custom/zsh-tab-config.sh
only contains the zstyle string I've specified in the description

**Comment by Aloxaf** [comment]
Try this:
```zsh
local extract="
# trim input
local in=\${\${\"\$(<{f})\"%\$'\0'*}#*\$'\0'}
# get ctxt for current completion
local -A ctxt=(\"\${(@ps:\2:)CTXT}\")
# real path
local realpath=\${ctxt[IPREFIX]}\${ctxt[hpre]}\$in
realpath=\${(Qe)~realpath}
"
zstyle ':fzf-tab:complete:cd:*' extra-opts --preview=$extract'exa -1 --color=always $realpath'
```

**Comment by ensarman** [comment]
:o  it was a litle hacky :P but it works... I never thought in to put a script inside a string and put that string to be executed by the completion, and I discovered the exa command :P  your solution may work to another cases... 

thanks!!!
