### ISSUE TITLE
[FR] automatically insert common prefix

### ISSUE THREAD

**Issue by romkatv** [Aloxaf/fzf-tab#89]
Setup:

```zsh
mkdir -p /tmp/foo/{bar1,bar2}
```

Currently, when I type `ls /tmp/foo/<TAB>`, I get this:

```text
❯ ls /tmp/foo/
> bar
  2/2
> bar1/
  bar2/
```

And if I press <kbd>Ctrl-C</kbd>, I get this:

```text
❯ ls /tmp/foo/
```

What I would like is for `bar` to be inserted automatically when I type `ls /tmp/foo/<TAB>`. There are two ways it could work, and both would work for me.

1. Just insert `bar` and not trigger `fzf`. In other words, `fzf` triggers only where there is no common prefix (empty `query`).
2. Insert `bar` and then immediately trigger `fzf`.
```text
❯ ls /tmp/foo/bar
> bar
  2/2
> bar1/
  bar2/
```
Note `bar` in the command line. If I now hit <kbd>Ctrl-C</kbd>, `bar` should be retained.
```text
❯ ls /tmp/foo/bar
```

Is (1) and/or (2) possible? I think I've seen a similar question with your answer but I cannot find it.

The reason I want this is that I often want to insert long file prefixes and then manually add `*`. In the example above my goal was perhaps to execute `ls /tmp/foo/bar*`

**Comment by Aloxaf** [comment]
> I think I've seen a similar question with your answer but I cannot find it.

Maybe #8?

> Is (1) and/or (2) possible?

Yes, it's easy to finish basic support -- just insert `$query` if it exists. But when it comes to a complex scene, it will be hard to deal with prefix/suffix. eg. `print ${ZSH\t` will turn into `print ${ZSH_}`, in which `}` is not expected.

It may take some time to come up with a workaround.

**Comment by romkatv** [comment]
> > I think I've seen a similar question with your answer but I cannot find it.
> 
> Maybe #8?

Thanks! Yes, that was the issue I was looking for. The offered solution doesn't work very well. I'll try to come up with something better. Will let you know if I succeed.
