### ISSUE TITLE
No completion is inserted when the cursor is not at the end of BUFFER

### ISSUE THREAD

**Issue by romkatv** [Aloxaf/fzf-tab#9]
To reproduce:

1. Type `gre` followed by space.
2. Move cursor one position to the left so that it ends up positioned on the space right after `gre`.
3. Press TAB.
4. Select `grep` in fzf that pops up.

Expected: `BUFFER` contains `grep `.

Actual: `BUFFER` contains `gre `.

Similar case where completion doesn't get inserted: `(gre)` (cursor after `gre`).

This fails a bit differently: `(gr)` (cursor after `gr`). It ends up as `(grep`. That is, completion gets inserted but `)` disappears.

**Comment by Aloxaf** [comment]
Thanks for your report.
But I can't reproduce that. Here is the `~/.zshrc` I have tried:
```zsh
autoload -Uz compinit; compinit
source ~/Coding/shell/fzf-tab/fzf-tab.zsh
```
Could you provide a minimal zshrc which can reproduce this bug?

**Comment by Aloxaf** [comment]
You can also take a look at #10. It should have better compatibility.

**Comment by romkatv** [comment]
I can confirm that https://github.com/Aloxaf/fzf-tab/pull/10 has fixed the issue. Thank you very much!
