### ISSUE TITLE
Colors don't change

### ISSUE THREAD

**Issue by NightMachinary** [Aloxaf/fzf-tab#90]
**Describe the bug**
I have set all the colors to a bluish-black but no colors change at all.
Also, I think adding support for a `light` mode in the default settings is a good idea.

**To Reproduce**
1. Type '...'
2. Press <kbd>Tab</kbd>

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/36224762/82627927-c3f88a80-9c00-11ea-9f45-ee0a7273b614.png)
![image](https://user-images.githubusercontent.com/36224762/82628049-091cbc80-9c01-11ea-921f-22e8d340ecd6.png)

![image](https://user-images.githubusercontent.com/36224762/82628053-0f129d80-9c01-11ea-8b4d-2cc79226696f.png)

**Environment (please complete the following information):**
 - OS: macOS Catalina
 - zsh --version
zsh 5.8 (x86_64-apple-darwin19.3.0)
 - fzf-tab version: Just installed via antibody, so it should be at HEAD

**zshrc**

```
antibody bundle Aloxaf/fzf-tab
FZF_TAB_COMMAND=(
    fzf
    --ansi   # Enable ANSI color support, necessary for showing groups
    --expect='$continuous_trigger' # For continuous completion
    # '--color=hl:$(( $#headers == 0 ? 108 : 255 ))'
    --color=light
    --nth=2,3 --delimiter='\x00'  # Don't search prefix
    --layout=reverse --height='${FZF_TMUX_HEIGHT:=75%}'
    --tiebreak=begin -m --bind=tab:down,btab:up,change:top,ctrl-space:toggle --cycle
    '--query=$query'   # $query will be expanded to query string at runtime.
    '--header-lines=$#headers' # $#headers will be expanded to lines of headers at runtime
)
zstyle ':fzf-tab:*' command $FZF_TAB_COMMAND
zstyle ':fzf-tab:*' $'\033[38;5;19m'
FZF_TAB_GROUP_COLORS=()
for i in {1..16} ; do
    # FZF_TAB_GROUP_COLORS+="$(colorfg 10 255 10)"
    FZF_TAB_GROUP_COLORS+=$'\033[38;5;19m'
done
zstyle ':fzf-tab:*' group-colors $FZF_TAB_GROUP_COLORS
```

**Comment by NightMachinary** [comment]
I also tested with
```
FZF_TAB_COMMAND=(
    fzf
    --ansi   # Enable ANSI color support, necessary for showing groups
    --expect='$continuous_trigger' # For continuous completion
    '--color=hl:$(( $#headers == 0 ? 108 : 255 ))'
    # --color=light
    --nth=2,3 --delimiter='\x00'  # Don't search prefix
    --layout=reverse --height='${FZF_TMUX_HEIGHT:=75%}'
    --tiebreak=begin -m --bind=tab:down,btab:up,change:top,ctrl-space:toggle --cycle
    '--query=$query'   # $query will be expanded to query string at runtime.
    '--header-lines=$#headers' # $#headers will be expanded to lines of headers at runtime
)
```
Same result.

![image](https://user-images.githubusercontent.com/36224762/82628309-bbed1a80-9c01-11ea-95d8-1a01522ad38f.png)

**Comment by NightMachinary** [comment]
Also, adding an option to disable colors entirely is another good idea.

**Comment by Aloxaf** [comment]
You haven't set group descriptions so `group-colors` tag won't work ( because there is no group at all ), please use `no-group-color` instead.

```zsh
zstyle ':fzf-tab:*' no-group-color $'\033[38;5;19m'
```

**Comment by NightMachinary** [comment]
@Aloxaf You're right! The readme needs that fixed; I copied from there.
![image](https://user-images.githubusercontent.com/36224762/82659212-91b94e00-9c3d-11ea-83af-a530d60eb73c.png)

**Comment by Aloxaf** [comment]
Fixed. Thanks for point out that.

**Comment by gordonpn** [comment]
@Aloxaf @NightMachinary 

Is it a possible that a recent change in the code caused the colors to not take effect anymore?

I have the following line in my `.zshrc` and the colors don't seem to apply.

`zstyle ':fzf-tab:*' no-group-color $'\033[38;5;19m'`

![image](https://user-images.githubusercontent.com/4203037/97810153-d3641100-1c3f-11eb-93c2-8f1f67889a97.png)

**Comment by Aloxaf** [comment]
@gordonpn
Oh, sorry for the inconvenience I caused. I renamed that tag to default-color because I think no-group-color is a little confusing.

**Comment by gordonpn** [comment]
@Aloxaf 
It works as expected now, thank you for your work!

**Comment by ztlevi** [comment]
@Aloxaf How can we change the matched string during search? I couldn't find the option.

See the example, the `dcstart`'s `d` and `a` is white color.

![image](https://user-images.githubusercontent.com/16655096/122587320-4667ae00-d090-11eb-8014-39f6dece2f77.png)

**Comment by Aloxaf** [comment]
@ztlevi 
It's in fzf's manual: https://man.archlinux.org/man/fzf.1#Display. Example: `zstyle ':fzf-tab:*' fzf-flags '--color=hl:cyan'`

**Comment by ztlevi** [comment]
Got it. Thanks! BTW, it should use color code.
