### ISSUE TITLE
[FR] Add a visual cue that the completion engine is working

### ISSUE THREAD

**Issue by NightMachinary** [Aloxaf/fzf-tab#91]
Sometimes completions get a while to get generated. A prime example is `vim scp://..` which needs to read from a remote system. In these situations, having a nonintrusive visual cue that the completion is underway is helpful.

**Comment by Aloxaf** [comment]
I think what you need is [`expand-or-complete-with-dots`](https://github.com/ohmyzsh/ohmyzsh/blob/b721053c87b4662c65452117a8db35af0154a29d/lib/completion.zsh#L62-L72)

**Comment by NightMachinary** [comment]
Thanks!
