### ISSUE TITLE
[BUG] Pre-populated fzf query is not a common prefix

### ISSUE THREAD

**Issue by romkatv** [Aloxaf/fzf-tab#94]
To reproduce:

1. Run this command:
```zsh
docker run -e TERM -w /root -it --rm alpine sh -c '
  apk add zsh bash git
  git clone --depth=1 https://github.com/Aloxaf/fzf-tab.git
  git clone --depth=1 https://github.com/junegunn/fzf.git
  fzf/install --bin
  export PATH="/root/fzf/bin:$PATH"
  touch a1 A1
  cat >~/.zshrc <<\END
zmodload zsh/zutil
zstyle ":completion:*" matcher-list "m:{a-zA-Z}={A-Za-z}"
autoload -Uz compinit
compinit
source ~/fzf-tab/fzf-tab.zsh
END
  exec zsh'
```
2. When prompt appears, type `: A` and press <kbd>Tab</kbd>.

Expected:

![image](https://user-images.githubusercontent.com/1282067/82733508-969d0100-9d14-11ea-8203-a3cefcf119f6.png)

Actual:

![image](https://user-images.githubusercontent.com/1282067/82733454-20000380-9d14-11ea-814a-c75a81ac6430.png)

Note that in the "actual" screenshot fzf is called with a pre-populated query "A". Only one element out of two matches it, so it looks rather confusing.

I would expect no elements to be hidden in the fzf list.

**Comment by Aloxaf** [comment]
Umm, in fact this is the expected behavior.

The default strategy for generating the query string is: first try to find a common prefix, if it doesn't exist, use the input instead.

You can change it to `zstyle ':fzf-tab:*' query-string prefix` then it will work as you expected.

**Comment by romkatv** [comment]
Thanks for the quick response. Yes, that does exactly what I need. Thanks!
