### ISSUE TITLE
[BUG] %F{default}%B%{%}%{%}%b%f 

### ISSUE THREAD

**Issue by 20jam** [Aloxaf/fzf-tab#98]
**Describe the bug**
After hitting tab, the under the prompt I have:
%F{default}%B%{%}--- local directory ---%{%}%b%f

**To Reproduce**
1. Type '...'
2. Press <kbd>Tab</kbd>

**Expected behavior**
idk, this %F{default}%B%{%}%{%}%b%f shouldn't be visable

**Screenshots**

![](https://i.imgur.com/TUHBEeH.png)

**Environment**
 - OS: Arch Linux
 - zsh version: 5.8
 - fzf-tab version: Last

**zshrc**
```
# Fzf-tab
# git clone https://github.com/Aloxaf/fzf-tab
source ~/.config/zsh/plugins/fzf-tab/fzf-tab.plugin.zsh

```

**Comment by Aloxaf** [comment]
Please add this line to zshrc and try again:

```zsh
zstyle ':completion:*:descriptions' format '-- %d --'
```

See #24

**Comment by 20jam** [comment]
THANK YOU!! Great plugin, it needs some time to get used to it though

**Comment by megalithic** [comment]
Same, that fixed the same issue for me on zsh/macos. thanks!
