### ISSUE TITLE
[BUG] When hitting TAB, the expression to be completed is pasted in fzf query

### ISSUE THREAD

**Issue by FreddieOliveira** [Aloxaf/fzf-tab#99]
**Describe the bug**
Depending on the completion kind, the expression to be completed is pasted in fzf query after TAB key is pressed.

**To Reproduce**
1. Type `ls ~/.oh/c/p`
2. Press <kbd>Tab</kbd>
3. fzf opens with `~/.oh/c` already pasted as a query, needing a manual cleaning

**Expected behavior**
It's expected to fzf open with a clean query, to select between ~/.oh-my-zsh/`cache/` and ~/.oh-my-zsh/`custom/`

**Screenshots**
![Screenshot_20200620-204743_Fennec_F-Droid](https://user-images.githubusercontent.com/9597536/85213635-7df22c00-b350-11ea-88ba-bf488b51acd4.png)

**Environment**
 - OS: Linux
 - zsh version: 5.8
 - fzf-tab version: commit d92299baafdf197c93a88e54f9bbc1c8bb31d427

**Comment by FreddieOliveira** [comment]
I find out that preventing `_fzf_tab_find_query_str()` to be called by deleting this line:

https://github.com/Aloxaf/fzf-tab/blob/d92299baafdf197c93a88e54f9bbc1c8bb31d427/fzf-tab.zsh#L395

solves the problem, which makes me think if that's actually an intended behavior.

**Comment by Aloxaf** [comment]
You can set `zstyle ':fzf-tab:*' query-string prefix first`
